### ISSUE TITLE
TypeError: L.GridLayer is undefined

### ISSUE THREAD

**Issue by nassarofficial** [tangrams/tangram#109]
I keep getting this error after make run-tests:

TypeError: L.GridLayer is undefined
  at /home/nassar/Desktop/tangram-master/dist/tangram.debug.js:21887

Im using Ubuntu, Firefox 23...

**Comment by bcamper** [comment]
Thanks - it looks like the Leaflet dependency is failing to load. To clarify, are you seeing this in the browser spawned by the test suite? Are you able to run the demo (index.html in root) manually in a browser after `make`?

**Comment by bcamper** [comment]
cc @iwillig maybe you could help look at this, it's possible Leaflet is not always loading when the test suite runs.

**Comment by iwillig** [comment]
Of course.

**Comment by iwillig** [comment]
@nassarofficial 
Thanks for your report. Couple of questions for you. 

Does this happen every time you run the test suite? 50% of the time? 
We don't support Firefox out of the box so I am assuming you installed the karma firefox plugin and you are running the test suite with something like, 
```
 npm install karma-firefox-launcher 
```
To start the test suite with Firefox
```shell
./node_modules/karma/bin/karma start --browsers Firefox --no-watch
```
And to run the test suite. 
```shell
make run-tests
```
I just want to make sure I am reproducing your steps correctly. 
I have a more current version of Firefox and can't reproduce your issues. However, I don't think that should matter. 

Is there anything else unique about your setup I should take into account. 

Thanks

**Comment by nassarofficial** [comment]
Thank You this worked, but I got another error:
make: *** No rule to make target `/home/nassar/Desktop/TraffiSense', needed by `dist/tangram.debug.js'.  Stop.

**Comment by iwillig** [comment]
I am guessing that you made some local modifications to the make file. Do you mind sharing those changes in a gist? 

Thanks

**Comment by nassarofficial** [comment]
I didnt do any changes to the make file, plus the index.html is providing me with the controls, and no tiles only a black page..

**Comment by iwillig** [comment]
Strange, what `make` command where you running when you encountered that error?

**Comment by nassarofficial** [comment]
I just did npm install... Then make, and this is what I get:
    at /home/nassar/Desktop/TraffiSense Web/tangram/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at Object.oncomplete (fs.js:107:15)
make: *** No rule to make target `/home/nassar/Desktop/TraffiSense', needed by `dist/tangram.debug.js'.  Stop.

**Comment by iwillig** [comment]
Do  you mind trying to remove the space in the `TraffiSense Web` folder name, 
So in shell, 

```shell
mv "TraffiSense Web" TraffiSenseWeb
```

**Comment by nassarofficial** [comment]
Surprisingly it worked after I removed the space. Although i get an error while compiling:
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: Cannot find module 'unruly' from '/home/nassar/Desktop/TraffiSenseWeb/tangram/src'


Now when I run make tests i keep getting, although I installed Leaflet plugin, I get this on Firefox and Chrome :

Chromium 37.0.2062 (Ubuntu) Leaflet plugin .addTo(map) "before each" hook FAILED
	Error: timeout of 2000ms exceeded

**Comment by bcamper** [comment]
Hi @nassarofficial, sorry about that, we no longer use the `unruly` module, but we had a lingering reference to it that I have removed (https://github.com/tangrams/tangram/commit/8fe8e198b62fb0ef23bf3e536d9b015173c62f43).

Could you please pull from master and give it another try?

We will open a separate issue to deal with the space problem.

**Comment by bcamper** [comment]
Follow up, apparently `make` doesn't support spaces very well! I've added a small tweak to escape spaces (https://github.com/tangrams/tangram/commit/6c7e7ce3f1f2138c84b8c811148a27a9f83dca02), after you see if the package will build in your current directory without spaces, it would be great if you could give it a try under your original directory name, with spaces.

Thanks for your patience.

**Comment by nassarofficial** [comment]
Great it now compiles really well, when i run make tests i just get: Karma v0.12.31 - connected, and in the index.html a black page with no tiles.. Thank you all for your prompt responses

**Comment by bcamper** [comment]
Glad to hear it compiles.

So, aside from running the tests, you are saying that it is not rendering for you properly? If you run a local webserver such a `python -m SimpleHTTPServer 8000` and then go to `http://localhost:8000/`, you get a black screen? If so, could you please try loading it with the console open and sending the output?

Regarding tests: if you want to do a single test run, you should be able to do `make test`. This should start Karma in a Chrome instance, run the test suite, and then close that Chrome. What output does that command generate for you?

Alternatively, you can run `make karma-start` to start the Chrome instance, then run `make run-tests` to run the test suite once, without closing Chrome at the end (this is more useful for active development where you are rebuilding and re-running the tests frequently).

**Comment by nassarofficial** [comment]
Yes, as I mentioned I get Karma v0.12.31 - connected with a blank page, how can I access tangram? I've tried everything.

**Comment by bcamper** [comment]
OK, let's back up a bit, I think our readme may be misleading :) You don't need to worry about the `npm`, `make`, or test commands (Karma etc.) unless you want to actually change the code behind the library. (The blank page you are seeing doesn't necessarily indicate a test error, since Karam doesn't present a visual interface -- the test output would be on the command line.) We will update the docs to reflect that.

If you just want to see the demo and play around with it, you should be able to simply start a local server and run the example. Let me know if this works for you:

run `python -m SimpleHTTPServer 8000`
go to `http://localhost:8000/` in your browser

Sorry for any possible confusion.

**Comment by nassarofficial** [comment]
Great, it worked finally thank you all for your help and fast response! Im glad you added it in the Readme!

**Comment by bcamper** [comment]
Great, good to hear :) Sorry for the confusion.
