### ISSUE TITLE
Feature Request: Change dynamically appearance of the map

### ISSUE THREAD

**Issue by mattrei** [tangrams/tangram#178]
Hi,

I wonder if it is possible or ever intended in tangram to change the appearance of a map dynamically.

I have the following use case: I have a moving object on the map that travels routes from A to B on the map. That is quite easy thanks to leaflet-routing-machine and Greensocket Tweening library. However now that we have Tangram I wonder if we can add support for WebGL Models or Shader Objects that interact with the map, for instance, that a car the travels along the route may change the appearance of travelled route. For instance I use a dark (night) style of the map and a car with lights would lighten up the way. 

Thanks for your suggestions of how to implement that.
Best,
Matthias

**Comment by meetar** [comment]
Hi Matthias –

Our JavaScript API already allows many aspects of the map styling to be changed dynamically. Here's a demo showing examples of changing lights and cameras with a JavaScript interface: https://github.com/tangrams/lights-cameras-demo

Our shading system also allows real-time updates through the use of special shader variables called uniforms, which can also be changed through the API: https://github.com/tangrams/tangram-docs/blob/gh-pages/pages/shaders.md#uniforms

However we don't currently support the inclusion of pre-existing 3D geometry in the map, so for the moment you're limited to sprites, either through Tangram's icons draw style (https://github.com/tangrams/tangram-docs/blob/gh-pages/pages/styles.md) or possibly using Leaflet markers with custom icons.
