### ISSUE TITLE
Tangram layer with base layer

### ISSUE THREAD

**Issue by juliomalegria** [tangrams/tangram#190]
Hi again :)

I was playing with the simple demo today. What I wanted to do was to add a base layer on the back of the vector rending.
You can see my code [in this gist](https://gist.github.com/juliomalegria/5a5127e2d5648015f837), but basically what I did was copied the simple demo, and added an extra base layer (`toner_lite`) and a map control.

What I realized was that if I don't include the base layer, everything works. Once I enable the base layer (from the code or from the UI) the vector data dissapears and there's no way to add it again. At first I thought it was something related to the `order` (base layer drawing on top of the polygons), but changing the order to 1000+ in the `scene.yaml` didn't do the trick.

Is it possible to add a base layer to a Tangram layer? How can I do it?

**Comment by meetar** [comment]
Hi Julio! I believe this has to do with the ways Leaflet and Tangram both
handle z-order internally. We'll take a look at it.

**Comment by juliomalegria** [comment]
Awesome, thanks! :+1:

**Comment by juliomalegria** [comment]
Any ETA for this one?

**Comment by meetar** [comment]
It looks like a combination of z-index and WebGL alpha considerations – I've got in working in this branch, and you're welcome to check it out: https://github.com/tangrams/tangram/tree/meetar/underlay

…but this is a quick hack, and without further testing I'm not sure this is the best way to do this. This is a use case we'd like to support, so we will be adding this functionality to the library eventually, but I don't have an ETA, sorry!

**Comment by juliomalegria** [comment]
Thanks for replying @meetar.
So what would be fastest (doesn't matter if it's hacky) way to fix this issue for me? Would `.bringToBack()` solve it? Not sure if I'm looking at the right stuff on your branch.

**Comment by meetar** [comment]
Unfortunately the branch includes all the things that had to be changed in
the library and scene setup to make it work. It's not a particularly simple
fix, but you're welcome to use its current state as a starting point.

At the very least you'd need to make the same changes to your index.html
and main.js, as well as referencing the branch's compiled version of the
Tangram library in your index.html – for the moment, you can link straight
to it with rawgit like so:
https://rawgit.com/tangrams/tangram/bc04f5431f0ea82a6b7642345540267f8c3c7bda/dist/tangram.min.js

**Comment by bcamper** [comment]
I would say we should be able to get to this within the next couple months.
It's definitely a helpful feature for those who want to use existing base
maps.

**Comment by bcamper** [comment]
Hi @juliomalegria -- we have released [v0.4.0](https://github.com/tangrams/tangram/releases/tag/v0.4.0), which includes proper support for transparent backgrounds. I tried a modified version of your gist (with our own building layer) and it appears to work, please let us know if you have any issues.

![screen shot 2015-11-03 at 10 52 11 am](https://cloud.githubusercontent.com/assets/16733/10912799/0dcb97da-8219-11e5-9c45-e3be58aec406.png)

**Comment by juliomalegria** [comment]
Awesome! That was fast! I'll try it tonight :+1:
