### ISSUE TITLE
Export Map.

### ISSUE THREAD

**Issue by antoniomdk** [tangrams/tangram#194]
Hello, I creating a 3D scene with babylon.js and I would like to integrate a 3D map inside. I mean, using a Tangram 3D map with a free fly camera, and adding 3D markers... Is it possible?

**Comment by meetar** [comment]
Tangram isn't currently designed to integrate with any other 3D libraries. You might be able to export 3D map data using something like https://github.com/meetar/manhattan-project, and then import those OBJ files into your own project.

**Comment by antoniomdk** [comment]
Perfect! but Is there any way to integrate Tangram with babylon.js/three.js without export a obj file to get everything online?. I just need to add babylon.js object inside the map.

**Comment by meetar** [comment]
No, Tangram isn't designed to interface with other 3D libraries at this time.

**Comment by antoniomdk** [comment]
Ok, Perfect, thank you so much!
