### ISSUE TITLE
Disable webgl for camera type: flat

### ISSUE THREAD

**Issue by parinporecha** [tangrams/tangram#195]
Hi, I'm creating a map application for which I'm thinking of using tangram for client-side styling. I want it to run on old browsers which might not have webgl support. Since only `flat` camera type needs to be supported, is there a way to disable webgl and use only leaflet to render the tiles?

**Comment by meetar** [comment]
Tangram doesn't have any mechanism for that – it uses WebGL for everything it draws to screen, so disabling it would mean nothing would ever be drawn. However, you could still serve a different Leaflet-only version of your map to clients with no WebGL support.

**Comment by parinporecha** [comment]
> However, you could still serve a different Leaflet-only version of your map to clients with no WebGL support.

Part of the reason I want to use Tangram is because it abstracts out tile styling to the `.yaml`. Can you suggest Leaflet-only libraries with such a feature?

**Comment by bcamper** [comment]
Hi @parinporecha -- you could check out a demo of this Canvas-only renderer, working with Mapzen vector tiles served from Mapzen (though not developed by people at Mapzen): https://github.com/mapzen/hoverboard

However, while promising, that project is fairly light-weight on the styling side and shouldn't be considered a full-blown rendering solution.

Out of curiosity, which devices/browsers is it that you are concerned about WebGL support for? Support is by no means universal, but it is quite broad at this point and only growing by the day.

**Comment by parinporecha** [comment]
> Hi @parinporecha -- you could check out a demo of this Canvas-only renderer, working with Mapzen vector tiles served from Mapzen (though not developed by people at Mapzen): https://github.com/mapzen/hoverboard

@bcamper , yes I looked at hoverboard, MVT, VECNIK and couple of other canvas libraries, but most of them are experimental and do not support either labels or advanced styling features.
> Out of curiosity, which devices/browsers is it that you are concerned about WebGL support for? Support is by no means universal, but it is quite broad at this point and only growing by the day.

A lot of the browsers will be on Ubuntu LTSP, and supporting them is part of the use case.

**Comment by bcamper** [comment]
Yes, unfortunately that is more or less the state of things right now :)  Most new vector renderers are WebGL-based. I think there would be a decent audience for Canvas-only rendering, but we simply don't have enough time to devote to it right now! Good luck though...
