### ISSUE TITLE
Leaflet.Hash disables mouse zooming

### ISSUE THREAD

**Issue by meetar** [tangrams/tangram#199]
_From @almereyda on October 6, 2015 22:4_

As long as Leaflet.Hash is loaded, mouse scrolling will yield:

```
mapzen.com/tangram/tangram.min.js:10 Uncaught TypeError: e._move is not a function
```

How to proceed from here?

* Does Tangram need an update to be compatible with https://github.com/mlevans/leaflet-hash
* or do we need to send a PR to https://github.com/mlevans/leaflet-hash to make it work properly again?

It seems someone is stealing events here.

_Copied from original issue: tangrams/generic-demo#1_

**Comment by meetar** [comment]
Thanks for the issue – I'm seeing this error whether leaflet.hash is loaded or not. Tangram was just upgraded to use the new Leaflet v 1.0 beta, and we've been making modifications to the library to accommodate. This will be addressed in the next Tangram release, so I'll move this issue there and rename it.

**Comment by meetar** [comment]
The issue is resolved when using the latest Tangram release (https://github.com/tangrams/tangram/releases/tag/v0.3.3) and Leaflet v1.0 beta.

**Comment by almereyda** [comment]
> Modifications to scroll-wheel zoom behavior to fix issues with animated styles in Chrome

Oh! This may even mean `map.flyTo` works again?

**Comment by bcamper** [comment]
@almereyda I was not aware it was broken, but it will be fixed in the next release! :)
