### ISSUE TITLE
Tangram 0.4: Promise rejection

### ISSUE THREAD

**Issue by patriciogonzalezvivo** [tangrams/tangram#215]
This error happens on Tangram 0.4 and not in Tangram .3

![screen shot 2015-11-11 at 10 52 36 am](https://cloud.githubusercontent.com/assets/346914/11095387/b99a3306-8862-11e5-9272-09cf96acbae5.png)

Here is a link to the project. To replicate the error just change the version to 0.4 in the index.html
https://github.com/patriciogonzalezvivo/InvisibleTracks

**Comment by bcamper** [comment]
Yep, same issue you reported before for ISS demo. Happens when you modify
data sources at runtime. Will be fixed in 0.4.1.

**Comment by patriciogonzalezvivo** [comment]
Ho! Sorry I didn’t realize I report the same bug before

**Comment by bcamper** [comment]
Fixed in 0.4.1
