### ISSUE TITLE
clipping of some lines on non-tiled geojson polygons

### ISSUE THREAD

**Issue by burritojustice** [tangrams/tangram#244]
Some lines are being dropped -- and not just along straight tile edge boundaries.

see near Old Saybrook and Branford, CT

http://tangrams.github.io/tangram-play/?scene=https://gist.githubusercontent.com/anonymous/78d5327116ac44d26a07/raw/50bfb7e5b086a2697c6b1ccbe5fe97fff12dec13/transitland-operators.yaml#10/41.4556/-72.7487

![image](https://cloud.githubusercontent.com/assets/3979711/12965795/efb04096-d00d-11e5-90c3-39a1b8557424.png)

see near Mount Diablo:

http://tangrams.github.io/tangram-play/?scene=https://gist.githubusercontent.com/anonymous/78d5327116ac44d26a07/raw/50bfb7e5b086a2697c6b1ccbe5fe97fff12dec13/transitland-operators.yaml#11/37.8095/-122.0760

![image](https://cloud.githubusercontent.com/assets/3979711/12965762/a6afa3d2-d00d-11e5-9f73-499a056e76e5.png)

**Comment by bcamper** [comment]
Turns out this is a bug that has been fixed in master, but not yet released: https://github.com/tangrams/tangram/commit/749e7666a6b1f038dec6e4e45b53393098bf6e21

I need to cut a 0.5.1 release which will fix this. Will close the issue then.

**Comment by bcamper** [comment]
Verified fixed by https://github.com/tangrams/tangram/releases/tag/v0.5.1

**Comment by burritojustice** [comment]
thanks!
