### ISSUE TITLE
Label Placement Parameters

### ISSUE THREAD

**Issue by hasan9206** [tangrams/tangram#249]
I am using Tangram to render Vector Tiles I have created using the Postgres source with TileStache, and it is working much better than I had hoped it would, kudos for a job well done!

I went through the documentation and was able to get most of the things without much issues, the problem I am facing now is that I can't figure out how to alter my label placements, I have looked through the various label demos but I have not been able to understand how the label placements works (particularly the labels for polygons, my land polygons have really weird label placements, they appear 2-3 times in some polygons while they appear once in a random location in another similar polygon).

![screenshot from 2016-02-22 14 35 02](https://cloud.githubusercontent.com/assets/7081695/13214461/994e9e06-d971-11e5-8a91-32f49ffdebfb.png)

Is there a listing of the label placement parameters available, or is there some documentation about it that I could read through?

**Comment by nvkelso** [comment]
Each polygon part in N tiles is being labeled. Instead you'll want to calculate a singe, de-duplicated label position point feature on the server and include it in the tiles. Then label using that point, and not on the polygons.

**Comment by bcamper** [comment]
Hi @hasan9206, glad it is mostly working anyway :)  To elaborate on what @nvkelso said, your source polygons are being split across separate tiles, and Tangram has no knowledge of the original polygon anymore (and generally, tiles are processed independently and sometimes on different threads from one another). So each source polygon us being labeled for each tile it intersects. 

Style parameters are currently documented here, but as you have noted, not necessarily grouped in the most convenient way for finding "all parameters relevant to label placement": https://mapzen.com/documentation/tangram/draw/#style-parameters

We can try to address this with a better documentation structure in the future. For now, these are the ones that can affect label placement (these mostly apply to sprites/points as well, except where they are text-specific, e.g. word wrapping):

[`align`](https://mapzen.com/documentation/tangram/draw/#align)
[`anchor`](https://mapzen.com/documentation/tangram/draw/#anchor)
[`collide`](https://mapzen.com/documentation/tangram/draw/#collide)
[`move_into_tile`](https://mapzen.com/documentation/tangram/draw/#move_into_tile)
[`offset`](https://mapzen.com/documentation/tangram/draw/#offset)
[`priority`](https://mapzen.com/documentation/tangram/draw/#priority)
[`repeat_distance`](https://mapzen.com/documentation/tangram/draw/#repeat_distance)
[`repeat_group`](https://mapzen.com/documentation/tangram/draw/#repeat_group)
[`text_source`](https://mapzen.com/documentation/tangram/draw/#text_source)
[`text_wrap`](https://mapzen.com/documentation/tangram/draw/#text_wrap)
[All `font` parameters](https://mapzen.com/documentation/tangram/draw/#font-parameters)

**Comment by hasan9206** [comment]
Thank You for the quick reply, really appreciate the help. @bcamper I love how easy it is to make 3-D maps using Tangram, and how simple the whole structure is to understand.

I found a few of the parameter you listed but I wasn't able to find all of them so it's a big help to have them all listed in a place, thanks for that.

I had an inkling that the polygons were being cut across tiles but it's good to have confirmation. I am thinking about creating a point layer from the polygon layer (using centroids and transferring all attributes pertaining to labels) but I'm not sure how I should deal with the River Polygons, Is there a way to use repeat_distance to label the rivers using one point (label)?

**Comment by nvkelso** [comment]
You can add a transform after the clipped river polygon tile geometry is created to set a label position point for it. But sometimes river centerlines are available, and Tangram does know how to space labels along those lines (and you'll get a better visual result where the label follows the flow of the river instead of labeling horizontally).

**Comment by hasan9206** [comment]
@nvkelso I was thinking about trying to get the labels to follow the flow of the river and the direction of the roads ( where they are not straight lines ) but I don't know how to do that yet.

I'm not sure what you mean by adding a transform, what exactly am I looking to transform here?

**Comment by nvkelso** [comment]
After you know what polygon geometry is included in the tile, you can post-process that.

You might also try the `label_centerlines` project from @ungarj (better for pre-processing before tiling):

* https://github.com/ungarj/label_centerlines

Tangram does allow similar text placements, see this issue for documentation (which seems to be lacking in the documentation repo, sorry!):

* https://github.com/tangrams/tangram/pull/182

**Comment by hasan9206** [comment]
If I use centerlines to label my polygons will Tangram be able to recognize the centerlines across multiple tiles? What I mean is will it solve my problem of multiple labels for polygons across multiple tiles? and what about smaller polygons, won't it be better to just use their centroids?

The text placements are exactly what I am looking for, Thank you!

**Comment by nvkelso** [comment]
Yes, centerlines are used in Mapzen vector tiles for river labels now (across multiple tiles) in Tangram. But your feature needs to be representable with a centerline (usually physical geography features like rivers or mountain ranges). Sometimes it's better as a point (centroid) if the feature is small, or if the feature is more cultural. It depends on your use case.

**Comment by hasan9206** [comment]
That makes sense, thank you for all the help @nvkelso , really appreciate it!

I should be able to get this done now.
