### ISSUE TITLE
More flexible hosting/bundling of library

### ISSUE THREAD

**Issue by bcamper** [tangrams/tangram#252]
There are significant limitations in the way Tangram currently loads its web workers. These mainly restrict others' desire to host or bundle the library, rather than loading it from the "official" Mapzen URLs.

Current library design:
- The same code is executed on both main and worker threads. This is because there is so much overlap of core code that needs to be executed by both. Many objects such as `Style` get instantiated in both thread types (albeit with some differences in behavior). There are a handful of switches (using `Utils.isMainThread` and `Utils.isWorkerThread`) to control behavior that differs across threads, usually where some code is applicable to one thread but not the other. Having one library file also simplifies distribution/hosting (rather than having to host and load a separate file built for worker execution).
- To instantiate its workers, Tangram needs a full copy of its own code. It currently accesses its code by looking for the `<script>` tag that it was loaded from. It restricts this search to known/expected library names: either `tangram.min.js` or `tangram.debug.js`.

Limitations of this approach:
- Tangram **must** be loaded from a file called either `tangram.min.js` or `tangram.debug.js`. For instance, copying it to a file called `tangram.js` will cause it to fail (because it cannot find the expected `<script>` tag.
- Tangram must be able to access its code in isolation from other code, which means it cannot be bundled with other JS dependencies (e.g. via a minifier or even simple `cat` bundle).
- It's possible for frameworks to modify the DOM _before_ Tangram searches for its `<script>` tag. For example, there was an apparent case where Webpack was removing `<script>` tags before Tangram executed, causing it to fail (but note this is speculative and would need to be verified with current versions, nonetheless the possibility remains).

Possible solutions:
1. Without changing current functionality, Tangram could have an option to provide an alternate URL from which its worker code should be loaded (instead of trying to infer that URL). Currently this could mean simply pointing back to the same URL that Tangram itself is being loaded from (since the main and worker thread bundles are the same); in option 4 below, the worker URL could point to a different bundle. There is actually an existing [internal option](https://github.com/tangrams/tangram/blob/master/src/scene.js#L53) for this which only needs to be exposed in the Leaflet plugin. However, this solution is incomplete, as it allows Tangram to be hosted under different filenames, but _not_ easily bundled with other code.
2. Tangram could "self-execute", meaning the library code could itself be placed in a variable that is `eval`'ed on the main thread, and then that same variable could be used to load the workers. Here is a [branch](https://github.com/tangrams/tangram/compare/self-loading) showing this approach. Initial tests are functional, however there are unanswered questions as to whether this is advisable, especially as it relates to library load/start-up time, and VM optimization paths (e.g. will a large `eval`'ed library still receive optimal treatment by the VM, does this differ for AOT compilation, etc.). This option would enable hosting under different filenames and/or bundling with other code, while preserving single-file distribution.
3. A utility such as [webworkify](https://github.com/substack/webworkify) could be used to load the worker code. This shares some aspects with the self-executing approach above, except that only the worker portions of the code are stringified (and then loaded into the worker via object URL). This has the downside of duplicating any shared code between the threads. Since the current library design actually _maximizes_ rather than minimizes code overlap, this would likely cause a large amount of library bloat without re-architecting (it is worth trying though). This option would enable alternate hosting filenames and bundling w/other code, as above.
4. Tangram could build separate bundles for the main thread and worker threads. Doing this efficiently would mean re-architecting to separate main/worker code as for `webworkify`. It would enable the main bundle to be hosted under different names and/or bundled w/other code, but it would require that the worker bundle is still distributed alongside the library, as a separate file, and its URL configured as in option 1 above.

**Comment by bcamper** [comment]
cc @louh you may find this of interest.

**Comment by dmvaldman** [comment]
Some recently updated work is being done on https://github.com/tangrams/tangram/tree/bundle

The new idea is to intercept the source code of Tangram before the bundling happens in Browserify and attach it to the Tangram object.

Previously, another fruitful direction was to wrap Tangram in a function and call `arguments.callee.toString()` within the function. This would provide the source code to Tangram. This would have to be assigned to a global variable, however, so the above approach is being used instead.

**Comment by bcamper** [comment]
Released in [v0.12.0](https://github.com/tangrams/tangram/releases/tag/v0.12.0)
