### ISSUE TITLE
Bundle multi-file scenes and resources

### ISSUE THREAD

**Issue by bcamper** [tangrams/tangram#253]
Bundle multiple scene files and related assets into a single file for easier distribution and less network overhead. Becomes more important as we add scene "include" functionality, increasing the number of network requests to load a scene.
- Multi-document YAML
  - Meta info about "file system" in first document
  - Custom logic to resolve paths, etc.
  - Doesn't support images/binary assets (without inefficient methods like base64 images)
- JSON wrapper with meta info
  - Individual scenes stored as YAML or JSON (just text, either works, and technically YAML is a superset of JSON anyway)
  - Stringified JSON scenes are smaller than YAML due to whitespace removal
  - Doesn't support images/binary assets as above
- Binary format
  - Protobuf, flatbuffers, etc.
  - Supports any asset type, and could reduce payload through custom data structures
  - Significant downside of needing to design format, encoder/decoder, less accessible (not human openable, debuggable, etc.)
- Zip archive
  - Natively preserves file paths, supports images/binary assets, easily readable by machines and openable by humans
  - Reasonable size improvements (compressed text), though we're already gzipping on server
  - Possibly less custom logic to resolve paths, etc. (still necessary, but can go through zip reader API vs. designing our own metata/format)
  - https://github.com/Stuk/jszip - large new depedency (75k minified), may increase value of conditionally loaded modules, e.g. only load TopoJSON, MVT, Zip, etc. libraries/modules as needed (currently the first two are always loaded with the library, regardless of whether they are needed for the scene's data sources. See #255.

**Comment by bcamper** [comment]
cc @blair1618 initial notes for now

**Comment by bcamper** [comment]
also cc @louh for future Play ramifications

**Comment by blair1618** [comment]
Have you tried to emit the scene file in YAML using "flow" notation? I imagine it would be the same or smaller than JSON since it has the same basic structural syntax, but doesn't need quotation marks.

**Comment by bcamper** [comment]
@blair1618 I have not, I'll see if js-yaml supports that option.

**Comment by nvkelso** [comment]
I think this got solved by @patriciogonzalezvivo's Bundler work?

- https://github.com/tangrams/bundler

**Comment by bcamper** [comment]
Yep - should probably have been closed with addition of zip bundles back in v0.9.0. The ES team has considered a pre-parsed binary version of the scene too, but with their recent huge improvements to YAML/scene parsing speed, that may no longer be necessary (or might be limited to an internal caching format). Closing this one. cc @matteblair

**Comment by matteblair** [comment]
Agreed, I don't see a need to pursue a new cache format at this time.
