### ISSUE TITLE
overzooming tiles distorts some shader patterns

### ISSUE THREAD

**Issue by nvkelso** [tangrams/tangram#259]
In the [Eraser Map scene file](https://github.com/tangrams/eraser-map/blob/nvkelso/v0.8-tiles-sort_key-orders/eraser-map.yaml), when I update the sources block's max_zoom from 18 to 16, the landuse dot patterns in the shader seem to freeze size at zoom 16 and then get larger and larger, like they're treated in meter space instead of pixel space.

/cc @sensescape 

**observed:**
<img width="547" alt="screen shot 2016-03-02 at 17 03 16" src="https://cloud.githubusercontent.com/assets/853051/13481557/7eaf70a8-e09b-11e5-8368-21d100efafe8.png">

**expected:**
<img width="612" alt="screen shot 2016-03-02 at 17 03 25" src="https://cloud.githubusercontent.com/assets/853051/13481556/7e97fe8c-e09b-11e5-8030-cd66773f5c89.png">

**Comment by blair1618** [comment]
I wonder - does the `modelPosition` accessor in our shaders account for over-zooming? I think right now it may be returning 0 and 1 at the limits of the larger tile that is being over-zoomed, but for re-styling it may be more useful to return 0 and 1 at the limits of the simulated tile at the higher zoom level.

**Comment by bcamper** [comment]
This makes sense, I'll give it a try.

**Comment by bcamper** [comment]
Will be fixed by https://github.com/tangrams/tangram/pull/266. Verified in desktop and mobile browsers.

**Comment by nvkelso** [comment]
Will the fix be part of the v0.5 Tangram series? All the new v2.0 scene file slippy map demos are pegged to that, and all suffer from this problem (especially building outlines at high zooms).

**Comment by bcamper** [comment]
It's in the 0.6 release I'm prepping now... but we'll want to update our
demos to use that for proxy tiles anyway ;)

On Wed, Mar 9, 2016 at 8:10 PM, Nathaniel V. KELSO <notifications@github.com

**Comment by bcamper** [comment]
Released with 0.6.0.
