### ISSUE TITLE
Investigate line width precision loss

### ISSUE THREAD

**Issue by bcamper** [tangrams/tangram#267]
@blair1618 noticed that lines seem to lose some of their width when overzoomed multiple levels (particularly now that we are overzooming from z16). For example, a 10px line renders consistently from z16-20, but starting at z21, it slims down to around 8px, and at z24 it disappears entirely. This appears to be an issue with precision, given that we are encoding line extrusion vector and width information in a signed short (16-bit int). I verified that hypothesis by switching back to using raw floats in the VBO, which showed no overzooming artifacts.

Given internal tile scale of [0, 4096], we start to run up against the limits of a short as the compounding effects of 2^z overzooming kicks in. The "slimming" effect is likely when the values start to get quantized to an insufficient bit-range, finally disappearing when they collapse into a single point and/or zero width.

We can probably tune the storage of these attributes to address this.

**Comment by nvkelso** [comment]
+1, I've noticed this as well. Setting to a meter unit often solves the problem?

/cc @sensescape

**Comment by bcamper** [comment]
What is a reasonable max zoom we should be supporting? There's some built-in limit (not yet exactly known) between how many zoom levels we can overzoom a given tile, e.g. if we stop requesting at z16, we can use it up to maybe z21 but I don't know how much further. (Another way to solve in the future would be to support tile zoom *ranges*, so use z16 up to z20 or z21 and then request another tile if needed; not ideal server-side either but there's series of tradeoffs.)

**Comment by nvkelso** [comment]
Zoom 16 overzooming does have limitation:

20/48.85744/2.34749

<img width="707" alt="screen shot 2016-03-09 at 13 39 41" src="https://cloud.githubusercontent.com/assets/853051/13651493/70c6f2d4-e5fc-11e5-8165-dba15cb8d09c.png">

Almost all our maps stop at zoom 20 at this point, supporting zoom 21 would be nice. But we'd need a different tile approach to support local areas with increased detail like you mention. That's probably useful to pursue in the mid-zooms anyhow. Once that's working should be easy to extend to zoom 21 tiles.

**Comment by nvkelso** [comment]
Same area in OSM:
https://www.openstreetmap.org/edit#map=21/48.85752/2.34733

<img width="466" alt="screen shot 2016-03-09 at 13 43 45" src="https://cloud.githubusercontent.com/assets/853051/13651635/04c83efc-e5fd-11e5-8bc4-ce1288793420.png">

/cc @zerebubuth @rmarianski

**Comment by nvkelso** [comment]
Aroundish: http://vector.mapzen.com/osm/all/16/33195/22546.topojson?api_key=vector-tiles-HqUVidw

**Comment by rmarianski** [comment]
Do we still see this issue with topojson? We're not cutting any precision there. And at z16, we've started using more precision with json too.

**Comment by bcamper** [comment]
The limits of the source data are relevant, but a separate issue from the
limits of internal buffer layout/packing.

**Comment by nvkelso** [comment]
@rmarianski Yes, the screenshots above are with TopoJSON.

**Comment by bcamper** [comment]
Was able to hack together a quick fix by storing the line width in the VBO in the meter scale of the *style zoom* (e.g. z20 overzoomed from z16), instead of the *tile zoom* (z16). But that solution likely involves some unnecessary math operations and I need to verify where else the values are used and may be affected by any change.

**Comment by bcamper** [comment]
Fixed by #310.
