### ISSUE TITLE
equal distance line patterns

### ISSUE THREAD

**Issue by patriciogonzalezvivo** [tangrams/tangram#269]

**Comment by patriciogonzalezvivo** [comment]
On process in this branch https://github.com/tangrams/tangram/tree/uv_y_meters

**Comment by patriciogonzalezvivo** [comment]
![screen shot 2016-03-10 at 3 08 39 pm 2](https://cloud.githubusercontent.com/assets/346914/13683244/abf18b44-e6d3-11e5-8b8b-8bea5ef7126f.png)
![screen shot 2016-03-10 at 3 08 21 pm](https://cloud.githubusercontent.com/assets/346914/13683243/abea276e-e6d3-11e5-9088-cebc1dfb1eef.png)
![screen shot 2016-03-10 at 3 07 43 pm](https://cloud.githubusercontent.com/assets/346914/13683245/abfc7540-e6d3-11e5-8a38-f25b89f103ca.png)
![screen shot 2016-03-10 at 3 07 29 pm](https://cloud.githubusercontent.com/assets/346914/13683246/abfddc14-e6d3-11e5-8bc1-776b84399862.png)
![00](https://cloud.githubusercontent.com/assets/346914/13683248/ac0b53da-e6d3-11e5-8e2d-38b6d2d4dd54.gif)
![00](https://cloud.githubusercontent.com/assets/346914/13683247/ac0a8a22-e6d3-11e5-8b5a-482f3c892189.png)

**Comment by patriciogonzalezvivo** [comment]
Caps and Joins are still been stretch. Why? 
- Caps: we don't actually know the length of them after the vert shader
- Joins: are trick because one side stretch while the other don't... is like runners on Olympic games... the one closer to the turn run less distance.

Other weird behavior is on tile edges. Lines length start from 0 every time. Maybe this could be solve on the server ???

**Comment by patriciogonzalezvivo** [comment]
TODOs:
- Lot of optimization to do: there are a lot of new distance calculation been made... that means a lot of Sqrt to calculate : / I bet @blair1618 and @bcamper have some smart ideas of how to improve that.
- The scale is hardcoded on the CPU side only... we should talk about how this can be set on the scene file and what's a cross platform approach for the GPU side of this

**Comment by patriciogonzalezvivo** [comment]
@nvkelso  : )

**Comment by zerebubuth** [comment]
@patriciogonzalezvivo - this is awesome!

> Other weird behavior is on tile edges. Lines length start from 0 every time. Maybe this could be solve on the server ???

Yes! mapzen/vector-datasource#486 is tracking this issue for adding to buildings. It should be essentially the same thing to add it to roads. Although probably not all roads... that would add a lot of data to the tile. Would it be enough to add `start_texture_offset` and `end_texture_offset` or something to roads which are cut at the boundary? Are you doing anything at the moment to adjust the spacing to an integer number of repeats?

**Comment by patriciogonzalezvivo** [comment]
I think with `start_texture_offset ` is enough. right?

you mean the spacing of the dash pattern? Is very basic right now... I'm just doing something like this in the color block:

```glsl
vec2 st = v_texcoord.xy;
st.y *= 40.96;
st = fract(st);
color.rgb += step(.5,st.y);
```

**Comment by bcamper** [comment]
@patriciogonzalezvivo see my comment over there, meant to make it here :) https://github.com/mapzen/vector-datasource/issues/486#issuecomment-195409820

Does it look right?

**Comment by zerebubuth** [comment]
> you mean the spacing of the dash pattern?

Yeah, I was thinking of the slight adjustments that sometimes get made to ensure that the line starts and ends on a dash. For example, if the pattern was 3 units on, 3 units off and the line was 20 units long, then to get exactly 3 repeats + one "end dash" the dashes would have to be about 2.857 units long.

**Comment by bcamper** [comment]
@zerebubuth, yep, I'm thinking that if there's an optional hint in the data that provides the starting position of the line relative to its prior segment (in some consistent but pattern-independent scale, like mercator meters?), then we could calculate the offset into the pattern at the start of each line. For features without that hint, it would just start the pattern at zero for each line.

**Comment by zerebubuth** [comment]
To make the adjustment to an integer number of dashes, wouldn't it also need the total line length (for any cut line)?

Also, using mercator meters has the disadvantage that for more zoomed-out tiles, the number will get larger and the least significant digits will be mostly noise. I also find it difficult to intuitively understand how long a particular number of mercator meters means for a feature. Is it worth considering using "pixels" (i.e: 256ths of a tile) as the length measurement? It has the advantage that we only need integer or one decimal place of precision, and is (to me, at least) more intuitive when inspecting the tile.

**Comment by meetar** [comment]
Agreed re: meters – I like the pixels idea!

**Comment by bcamper** [comment]
Using something like "tile pixels" (which is a unit of measure already used across Tangram styling anyway) makes sense, you're right the limitations of mercator meters make it a bad choice here.

Ah, I hadn't been thinking of adjusting the pattern length itself, partially because I'm thinking of this as a generic feature with user-defined patterns (though including some built-in ones). We might be able to get away with stretching them a bit, or padding the line start/end with whitespace (wouldn't work for all patterns though)? I can see why we would need the entire (uncut) line length for that. I had only been thinking of ensuring continuity of patterns across line breaks before, not of eliminating the final fractional pattern at the end of the line.

**Comment by nvkelso** [comment]
Illustrator has options for absolute and stretched, including adjustments at "corners" so the dash is centered there.

**Comment by bcamper** [comment]
Basic patterns first ;)

**Comment by patriciogonzalezvivo** [comment]
Adding ratio adjustment expose to the style here https://github.com/tangrams/tangram/commit/37c4493813e4391cd3ad04f879edc04eda500526 
![00](https://cloud.githubusercontent.com/assets/346914/13758061/d65fe880-e9fd-11e5-9e58-754116243e7a.gif)

TODO: 
- I'm using 4096 as a hardcoded number for normalizing the Y. Should be review
- What ever number we use in the `builders.js` should be multiplied on the fragment shader

**Comment by patriciogonzalezvivo** [comment]
[uvs.yaml.zip](https://github.com/tangrams/tangram/files/172769/uvs.yaml.zip) How the scene.yaml looks like for now

**Comment by bcamper** [comment]
@patriciogonzalezvivo please open a PR? I'd prefer to keep implementation-specific discussion there. Thanks!

**Comment by bcamper** [comment]
Initial linear UV calculation added via #275, but will keep this issue open for discussion on built-in line patterns.

**Comment by bcamper** [comment]
Additional line pattern support shipping in 0.8.
