### ISSUE TITLE
Tile coordinates now report at NaN

### ISSUE THREAD

**Issue by nvkelso** [tangrams/tangram#270]
did Tangram v0.6 mess up the lat-lng to tile coordinate magic?

I used to be able to cmd-click in all my maps to get the raw tile data

For instance:
http://indyhurt.github.io/nyr-fitness/map/#19/37.76825/-122.45218
cmd-click near the `Funky Door Yoga`

in v0.6 I get: 
http://vector.mapzen.com/osm/all/undefined/NaN/NaN.topojson?api_key=vector-tiles-HqUVidw

but if I downgrade to v0.5 Tangram I get:
http://vector.mapzen.com/osm/all/19/83809/202660.topojson?api_key=vector-tiles-HqUVidw

Which is the expected behavior. I use this feature constantly through the day, is it possible to roll a patch update to fix the issue soon?

**Comment by bcamper** [comment]
I don't know how that was implemented, as it's not a Tangram feature, so I can't currently comment. Can you show where that code is?

**Comment by meetar** [comment]
This is something I added client-side to the main.js – and it's almost certainly something which I should fix client-side, so I'll take a look at it there.

Leaving this open for now, will post updates here.

**Comment by bcamper** [comment]
Is this still valid? Not a Tangram bug anyway AFAIK.

**Comment by nvkelso** [comment]
Peter and I fixed it up in all the demos that I care about.
