### ISSUE TITLE
POI detail on mouse hover/ click

### ISSUE THREAD

**Issue by hasan9206** [tangrams/tangram#272]
I have been trying to replicate the mouse over/click function I have seen in many of your examples ( where you get the name/details of the POI on mouse hover / click ).
![screenshot from 2016-03-12 12 24 52](https://cloud.githubusercontent.com/assets/7081695/13721596/c13ab63a-e84d-11e5-9072-e3ef1d81cf6f.png)

But I have had no success at all! I have tried to modify the function in the [JavaScript Files](https://github.com/tangrams/refill-style-more-labels/blob/gh-pages/main.js) but it just doesn't seem to work. 

I think the main issue is that I am using tiles that I have created and not the `OSM` tiles and will have to modify the code accordingly. I'd really appreciate it if you could guide me a little bit about how I should go about modifying the function or writing my own.

**Comment by nvkelso** [comment]
Inside the Tangram scene file you can mark features in their `draw` section as `interactive: true`. Those features are then available for mouseOver and tap events. 

But you'll need additional code to actually add the user interface. The JavaScript function that does this is initFeatureSelection(): https://github.com/tangrams/refill-style-more-labels/blob/gh-pages/main.js#L80-L170, which is added when the window is loaded: https://github.com/tangrams/refill-style-more-labels/blob/gh-pages/main.js#L178.

That function assumes your feature has a `name`, https://github.com/tangrams/refill-style-more-labels/blob/gh-pages/main.js#L101. Clicking the object will print out all the feature properties here: https://github.com/tangrams/refill-style-more-labels/blob/gh-pages/main.js#L142.

**Comment by bcamper** [comment]
@hasan9206: also, soon we will be making this integration much simpler, allowing you to pass `click` and `hover` events to the `Tangram.leafletLayer`, so that you don't have to add this boilerplate mouse/event-handling code yourself.

**Comment by hasan9206** [comment]
I got it working by adding `interactive: true` in the draw section of the POI icons I have. 

@bcamper that sounds great!

Thanks for all the help!

**Comment by bcamper** [comment]
Good to hear, @hasan9206. Branch for improving selection events is here if you are interested, https://github.com/tangrams/tangram/compare/selection-events, we will be opening a PR soon.

**Comment by gggauravgandhi** [comment]
I am looking for solution to same problem. I am able to find feature, but don't know how to provide a distinct style to it. 

@nvkelso All links mentioned in your post are invalid(404), please update if possible. 

Thanks.

**Comment by nvkelso** [comment]
@gggauravgandhi Restarting https://github.com/tangrams/tangram/issues/272#issuecomment-195823326 but with new links:

Inside the Tangram scene file you can mark features in their `draw` section as `interactive: true`. Those features are then available for mouseOver and tap events. 

But you'll need additional code to actually add the user interface. The JavaScript function that does this is initFeatureSelection(): https://github.com/tangrams/refill-style-more-labels/blob/gh-pages/index.html#L271-L296, which is added when the window is loaded: https://github.com/tangrams/refill-style-more-labels/blob/gh-pages/index.html#L693-L715.

That function assumes your feature has a `name`, https://github.com/tangrams/refill-style-more-labels/blob/gh-pages/index.html#L286-L290. Clicking the object will print out all the feature properties here: https://github.com/tangrams/refill-style-more-labels/blob/gh-pages/index.html#L656-L659.
