### ISSUE TITLE
Switch map type based on WebGL support

### ISSUE THREAD

**Issue by amnesia7** [tangrams/tangram#285]
Is it possible/is there a straightforward way to switch between using tangram or normal OSM map tile images based on webGL support (using Modernizr)?

Thanks

**Comment by bcamper** [comment]
Hi @amnesia7 -- this is timely, we've just been discussing adding a raster fallback parameter to Tangram's Leaflet layer so this can happen automatically. That will be in a future release, but in the meantime @louh should be able to provide an example of how he's done this in other Mapzen demos. It involves adding a bit of fallback code.

**Comment by louh** [comment]
Hi @amnesia7 -- 

Yes, you can detect WebGL support and either use Tangram or normal raster map tiles.

Your logic should look something like this:

```js
// Initialize Leaflet
var map = L.map('map');
var layer;

// Now, let's check whether Modernizr detects WebGL:
if (Modernizr.webgl === true) {
    // WebGL is enabled! `layer` should be Tangram, so initialize it with
    // a Tangram scene file.
    layer = Tangram.leafletLayer({
        scene: 'https://mapzen.com/carto/cinnabar-style/2.0/cinnabar-style.yaml'
    });
} else {
    // WebGL is not enabled! `layer` must be Leaflet, so initialize it with a
    // Leaflet Tile layer.
    layer = L.tileLayer('http://{s}.tile.osm.org/{z}/{x}/{y}.png');
}

// Now, add the layer to the map!
layer.addTo(map);
```

Hope that helps!

**Comment by amnesia7** [comment]
Thanks @louh 

@bcamper you can close this issue if you don't need to keep it open for the future release you mentioned
