### ISSUE TITLE
Different color being displayed.

### ISSUE THREAD

**Issue by hasan9206** [tangrams/tangram#286]
I have been facing a weird issue for a while now ( it has persisted over all three Tangram versions I have used 0.4, 0.5 and now 0.6.1 ). Sometimes the colors I assign in the scene file (the yaml) are not correctly displayed in the map. They are a few shades lighter for some reason. 

I have compared the hex codes of the two (the codes I assigned in the scene file and the code in tangram and they are not the same).  This is the color I've assigned to the `Parks`  in the Cartographic Layer ('#b5c899')
 ![screenshot from 2016-04-08 10 16 45](https://cloud.githubusercontent.com/assets/7081695/14374751/0c869002-fd73-11e5-94f3-db0afcc157a2.png)
And this is the color being displayed:
![screenshot from 2016-04-08 10 20 14](https://cloud.githubusercontent.com/assets/7081695/14374787/876de270-fd73-11e5-8017-d10a705b67ca.png)
This difference in this case is not that big but it still poses consistency issues and in other cases (when I assigned color to buildings) the difference can be much more noticeable.

Is this an issue on my end? What can I do to try to get consistent colors?

P.S: Great job on the updated documentation, really makes this clear and easy to understand. Also loving the new feature in the 0.6.1 build.

**Comment by nvkelso** [comment]
I suspect this is caused by your lighting setup. Brett or Peter to give more details.

**Comment by meetar** [comment]
Yes, it's likely this is light-related – if you have lights in your scene,
they will be applied to all geometry and will affect colors. If you only
want your lights to apply to certain layers, you can make a new `style`
with `lighting: false` and apply that style to the problem layers, as seen
in the example in the documentation:

https://mapzen.com/documentation/tangram/styles/#lighting

Or you could remove the lights entirely, and the scene will have default
"flat" light everywhere, which will true up your color values – but this
will also remove the shading on any extruded geometry, such as buildings.



On Fri, Apr 8, 2016 at 7:53 AM, Nathaniel V. KELSO <notifications@github.com
> wrote:

> I suspect this is caused by your lighting setup. Brett or Peter to give
> more details.
>
>
> > On Apr 8, 2016, at 01:23, Muhammad Hasan Mustafa <

**Comment by hasan9206** [comment]
Yes that was it! I had the lighting set up and it was messing with the colors I had. I have now disabled lighting on all layers where I don't want shadows to be displayed. 

Thanks for the quick reply @nvkelso and @meetar . Really appreciate it!
