### ISSUE TITLE
Consider adding uniform caching

### ISSUE THREAD

**Issue by bcamper** [tangrams/tangram#287]
We currently have a lot of redundant GL state changes for setting uniforms. We could reduce these by caching uniform values in JS, and comparing the values to see if they have changed before calling any GL updates. This will need to be benchmarked however, as there is a trade-off between increased JS time to check uniform state vs. increased driver/GL time to update.

**Comment by dmvaldman** [comment]
![tumblr_m7u8lg9qsw1rwper3o2_500-2](https://cloud.githubusercontent.com/assets/796394/14548807/7c3ee7ea-0288-11e6-8b65-041937ad37a9.jpg)

**Comment by meetar** [comment]
:trophy:

**Comment by bcamper** [comment]
Turned out that caching the uniform values was actually *slower* (partially due to the complexity of needing to copy all array values) -- but, we were able to get big CPU savings with other changes in #298.

**Comment by dmvaldman** [comment]
![images](https://cloud.githubusercontent.com/assets/796394/14753894/2b8d9a2a-08a6-11e6-83eb-1f9f06e5fe0c.jpeg)

**Comment by dmvaldman** [comment]
(though technically, stars are much further away from the moon, so this adage really makes little sense. you'll more likely just burn up in the atmosphere)
