### ISSUE TITLE
CMake Error at external/alfons/deps/CMakeLists.txt:6 (add_subdirectory):

### ISSUE THREAD

**Issue by mgarcia01752** [tangrams/tangram#289]
I  have a RaspberryPI 3 and I followed the steps provided:

sudo apt-get update
sudo apt-get install cmake g++-4.7 libcurl4-openssl-dev
cd ~
git clone https://github.com/tangrams/tangram-es.git
cd tangram-es
git submodule init && git submodule update
make rpi
cd build/rpi/bin
./tangram

When I get to the "make rpi" I get the below error:

pi@raspberrypi:~/tangram-es $ make rpi
-- The C compiler identification is GNU 4.9.2
-- The CXX compiler identification is GNU 4.9.2
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Platform chosen : RASPBERRYPI
-- Including raspberrypi dependent cmake file : /home/pi/tangram-es/toolchains/raspberrypi.cmake
-- Performing Test FLAG_WEXTRA
-- Performing Test FLAG_WEXTRA - Success
-- Looking for GLM
-- GLM include /home/pi/tangram-es/core/include/glm
CMake Error at external/alfons/deps/CMakeLists.txt:6 (add_subdirectory):
  The source directory

    /home/pi/tangram-es/external/alfons/deps/harfbuzz-icu-freetype

  does not contain a CMakeLists.txt file.

-- harfbuzz
-- Configuring incomplete, errors occurred!
See also "/home/pi/tangram-es/build/rpi/CMakeFiles/CMakeOutput.log".
Makefile:256: recipe for target 'cmake-rpi' failed
make: *** [cmake-rpi] Error 1

I am using tangram for my Senior Capstone Project and would any help!!!!

Thank You!!!!

Maurice

**Comment by tallytalwar** [comment]
Hey Maurice

I guess this issue belongs here: https://github.com/tangrams/tangram-es

If you do a recursive init and update for submodule, it should fix your problem. Try the following, and then try to build again.
```
git submodule sync --recursive
git submodule update --init --recursive
```

Let us know if this resolves your problem.
Thanks

**Comment by tallytalwar** [comment]
This issue was moved to tangrams/tangram-es#671

**Comment by mgarcia01752** [comment]
That did it...Thank You!!!
