### ISSUE TITLE
Use GL element buffers 

### ISSUE THREAD

**Issue by bcamper** [tangrams/tangram#294]
Currently all of our geometry is rendered with vertex buffers. We can save memory and rendering time by using element arrays instead. An element array buffer references vertices from a vertex array buffer by index. As with the current setup, the vertex buffer will be bound to `ARRAY_BUFFER`, with an additional index buffer bound to `ELEMENT_ARRAY_BUFFER`. When using an element array, the `drawArrays` call is replaced by `drawElements`. [Element array example](https://developer.mozilla.org/en-US/docs/Web/API/WebGL_API/Tutorial/Creating_3D_objects_using_WebGL).

Components to be updated:
- **GL rendering interface**
  - The [`VBOMesh`](https://github.com/tangrams/tangram/blob/master/src/gl/vbo_mesh.js) class should be updated to optionally support drawing with element arrays (preserving existing behavior to render with just vertex buffers).
  - See the [corresponding class](https://github.com/tangrams/tangram-es/blob/master/core/src/gl/mesh.cpp) in Tangram ES, which follows the same pattern. 
  - Since element arrays are 16-bit ints (`Uint16Array`), each element array **can only address up to 65536 vertices at a time**. We do have draw calls in dense areas (e.g. NYC buildings at z14, etc.) that exceed this limit, so we must gracefully support any number of vertices per mesh.
    - This can be done while still keeping all vertices in a single vertex buffer and all indices in a single element buffer, but with multiple `drawElements` calls. Each call points to different starting offsets in the element and vertex buffers. Care must also be taken so that a single geometry doesn't cross a "boundary" multiple of 65536 vertices. The ES class and geometry build process implements this logic, so @blair1618 or another member of the ES team can provide assistance when we get to this point.
  - `VBOMesh` could also be updated to support additional draw modes beyond `TRIANGLES`, such as `TRIANGLE_STRIP`. This can be done after initial element array support is done (and the ability to use alternate draw modes is heavily dependent on the geometry building process).

- **Tile construction**
  - During tile construction, the vertex data used to create each `VBOMesh` is stored by the rendering style, in a per-tile object containing [`vertex_data` property](https://github.com/tangrams/tangram/blob/master/src/styles/style.js#L113-L117).
  - When all features in the tile are processed, that data is passed to the main thread where it is turned into a `VBOMesh`, which uploads it to GL; zero or more of these are passed per tile, [one for each rendering style](https://github.com/tangrams/tangram/blob/master/src/tile.js#L271-L287) used in the tile.
  - Currently, a single [`vertex_data`](https://github.com/tangrams/tangram/blob/master/src/tile.js#L281) property is passed for each style, containing the data for the vertex buffer. We can extend this with an optional `element_data` (or similarly named property) (and likely another property for buffer offsets for multiple draw calls, see above comments on 16-bit index limitations). 
  - Back on the main thread, these buffers are turned into `VBOMesh` objects [here](https://github.com/tangrams/tangram/blob/master/src/tile.js#L374) and [here](https://github.com/tangrams/tangram/blob/master/src/styles/style.js#L287-L289).
  - Note: any typed arrays (e.g. `vertex_data`) are automatically sent as transferable objects by the `WorkerBroker`, so data overhead should be minimized without any special logic for the new element buffer. 

- **Geometry builders**
  - Geometry builders turn abstract geometry features into GL-formatted buffers. Each builder needs to be updated to output element arrays (along with vertex arrays). These pieces can be done incrementally for each geometry type (while most or all of the changes in the above two sections are likely required).
  - [Points](https://github.com/tangrams/tangram/blob/master/src/builders/points.js) are the best first candidate given their simplicity, and the vertex order of each feature is always the same (e.g. see [ES implementation](https://github.com/tangrams/tangram-es/blob/master/core/src/util/builders.cpp#L445-L450)).
  - The [polyline builder](https://github.com/tangrams/tangram/blob/master/src/builders/polylines.js) is more complex but also lends itself well to elements, since its logic already stores and [references vertices by index](https://github.com/tangrams/tangram/blob/master/src/builders/polylines.js#L568) during the build process. A lot of vertex memory can hopefully be saved here too.
  - The [polygon builder](https://github.com/tangrams/tangram/blob/master/src/builders/polygons.js) has two components:
    - A wrapper over the [earcut](https://github.com/mapbox/earcut) tesselator, for flat 2d polygons. Earcut has a mode for outputting element arrays (in fact, newer versions of the library only support this mode). There is some extra overhead in converting the geometry data to different layouts to match earcut's own input/output formats, so we'll have to take care to benchmark here, and could consider changes elsewhere in our data pipeline too.
    - For extruded polygons (e.g. 3d buildings), the builder creates additional vertices/triangles for the building walls. This logic should be relatively straightforward to convert to an element indexed model.

**Comment by bcamper** [comment]
@blair1618 while there are several JS-specific references here, if you could give this a read to see if I misstated anything, I'd appreciate it.

**Comment by blair1618** [comment]
Looks good!

One thing you might look into: 

The limitations of unsigned 16-bit element indices has led to the introduction of OpenGL and WebGL extensions that allow using  unsigned 32-bit integers for element indices. 32-bit indices should be sufficient to index any mesh we would encounter in our current architecture with a single draw call. The [WebGL extension](https://developer.mozilla.org/en-US/docs/Web/API/OES_element_index_uint) has far more support than the corresponding extension for OpenGL ES 2 (which tangram-es does not use), with 98% coverage according to [webglstats.com](webglstats.com). 

This would simplify the implementation of your mesh types and reduce draw calls, but could be unsupported on a small number of browsers and would actually consume a bit more memory than 16-bit indices (the index buffers would be twice as large).

**Comment by dmvaldman** [comment]
Nice. [webglstats.com](webglstats.com) looks like a great resource too

**Comment by bcamper** [comment]
Yes webglstats is awesome!

Good point about the 32-bit element index extension. I've wanted to avoid reliance on any specific extensions so far (e.g. we support Vertex Object Arrays when the extension is available, but also fallback to normal behavior when they are not supported), but this might be the first case where it arguably could make sense. Should maybe dive into the stats a bit more too to see which devices don't support it (likely not a particularly important 2% but it would be good to know if it's a specific chipset/device or what).

**Comment by bcamper** [comment]
Closed via #313. Will ship as part of 0.8 release.

**Comment by bcamper** [comment]
Released in [v0.8.0](https://github.com/tangrams/tangram/releases/tag/v0.8.0)
