### ISSUE TITLE
add markers, circles

### ISSUE THREAD

**Issue by geraldstanje** [tangrams/tangram#297]
Hi,

is it possible show points (lat/long) in form of markers (google.maps.InfoWindow) or circles (google.maps.Circle) on the map? i would like to add them on the fly...

Thanks

**Comment by bcamper** [comment]
Hi - for most typical uses cases, the most straightforward way to do this is with [Leaflet's](http://leafletjs.com) own built-in marker capability -- you can put these over a base map rendered with Tangram.

It is also possible to render additional circles/markers/etc. with Tangram styles, if you have more advanced styling needs or want the rendering more closely integrated with the base map. The best way to do this would be to put the styling code in your Tangram scene file (usually using the [`points`](https://mapzen.com/documentation/tangram/Styles-Overview/#points) style), and the use the [`setDataSource()`](https://mapzen.com/documentation/tangram/Javascript-API/#setdatasourcename-source) method in your JS code to set the circle/marker geometry on the fly.

**Comment by geraldstanje** [comment]
@bcamper thanks for the info. is it also possible to plot a heatmap? what do you suggest to look at?

**Comment by dmvaldman** [comment]
@geraldstanje You may be interested in Leaflet's heatmap plugin: http://leaflet.github.io/Leaflet.heat/demo/

**Comment by geraldstanje** [comment]
@dmvaldman thanks for pointing to, does it use webgl? i have a dataset with 200k points which i add on the fly.
