### ISSUE TITLE
Data URI images don't load in Safari due to CORS error

### ISSUE THREAD

**Issue by bcamper** [tangrams/tangram#300]
Looks like the `Image`'s `crossOrigin` property may need to change based on the browser to allow data URI images to load properly. Chrome and FF load OK with `image.crossOrigin = 'anonymous'`, but Safari does not. Also need to check IE11/Edge.

**Comment by bcamper** [comment]
@dmvaldman this is the issue we saw yesterday with the uniform texture test not working in Safari.

**Comment by dmvaldman** [comment]
That's strange. I would have thought data URI's were created to avoid external file requests, making CORS a non-issue

**Comment by bcamper** [comment]
You would think so :)  Chrome also treats (or at least used to, not sure if
this is still the case) `file://` requests as from a "different" domain,
even when loaded from another `file://`.

**Comment by bcamper** [comment]
Resolved in https://github.com/tangrams/tangram/commit/a38cd69890574afc514e6978e7757f11721e4021, will be part of 0.8 release.

**Comment by bcamper** [comment]
Released in [v0.8.0](https://github.com/tangrams/tangram/releases/tag/v0.8.0)
