### ISSUE TITLE
Adding Motorway Icons

### ISSUE THREAD

**Issue by hasan9206** [tangrams/tangram#304]
I have been trying to use icons to label motorways and highways but I have not been able to do so, I have had no issues with using labels:
![screenshot from 2016-04-27 11 36 27](https://cloud.githubusercontent.com/assets/7081695/14843790/6ee1d8ee-0c6c-11e6-9a5d-a15265c11766.png)

But I want to have icons on the motorways and highways, like google maps:
![screenshot from 2016-04-27 11 36 43](https://cloud.githubusercontent.com/assets/7081695/14843888/20e708d4-0c6d-11e6-89a0-d2cf471b1455.png)

I have tried adding a icon like I would for POIs but that doesn't work, since motorways are a line class. I was wondering if there was a parameter I could use to get points on the lines like the `centroid: true` parameter for polygons. I don't really want to add points on roads for icons manually as that wont work for all zoom levels. I also will need to be able to add text in the icon to label each motorway correctly.

P.S: Do you guys have any tips on getting tangram to render faster?

**Comment by meetar** [comment]
Hi Muhammad!

We are currently working on a new unified points/labels style which will
allow you to place icons on roads – we hope to release it soon.

We're also continually making improvements to the rendering speed – but in
general the best way to speed up rendering is to draw fewer features. :)

Best,
Peter

**Comment by bcamper** [comment]
@hasan9206 nice progress! In addition, sometimes slower drawing can happen if features are unintentionally matching/drawing multiple times ("overdraw"). That may not be happening in your case, but we've seen issues with it. If you'd like, we're happy to take a look at your scene file, you could either post it here or send privately to brett@mapzen.com if you prefer.

**Comment by hasan9206** [comment]
Thanks for the quick reply @meetar & @bcamper , really appreciate it! I'm looking forward to the unified points/labels style, it will really help alot and make life alot easier. The hardest part right now seems to be handling the POIs Labels and icons ( difficulty compounded by the fact that I am labelling some of important features in two languages ).

@bcamper I think I am "overdrawing" some of the features and I know that I have alot of extra lines of code that I should be able to get rid of in my scene file but I haven't been able to get around it so far. I really appreciate your offer of taking a look at my scene file but I wouldn't want to take more of your time (my scene file is over 2350 lines long so far!).

On another note. I'm trying to make my railways look something like this:
![screenshot from 2016-04-28 10 27 07](https://cloud.githubusercontent.com/assets/7081695/14876230/2018806c-0d2c-11e6-8d15-723900655a3e.png)
I know that I'll have to make a custom shader to get the same look but I don't really know how to code webgl shaders, I'd really appreciate it if you could point me in the right direction.

**Comment by meetar** [comment]
Patterned lines are another thing which *just* became possible in Tangram – lines now have UV ranges which are scaled based on their length. We're taking advantage of this in our "bubble wrap" style, here: https://github.com/tangrams/bubble-wrap/blob/gh-pages/bubble-wrap.yaml#L438-L453

You can see an example of it on the stairways on Telegraph Hill in San Francisco, here: http://tangrams.github.io/bubble-wrap/#19/37.80240/-122.40575

If you'd like to learn more about building patterns in GLSL, we recommend checking out @patriciogonzalezvivo's excellent Book of Shaders, especially Chapter 9: http://patriciogonzalezvivo.com/2015/thebookofshaders/09/

**Comment by patriciogonzalezvivo** [comment]
Hello @hasan9206 here you can find some snippets to make line patterns https://github.com/tangrams/blocks/tree/gh-pages/patterns/lines

**Comment by hasan9206** [comment]
@patriciogonzalezvivo  & @meetar Thanks guys! Patterned lines were giving me some trouble but not anymore! Really appreciate the help!

**Comment by patriciogonzalezvivo** [comment]
Just FYI I update the location and add some documentation to the line patterns to here https://github.com/tangrams/blocks/tree/gh-pages/lines
