### ISSUE TITLE
Scroll zoom slower than image maps

### ISSUE THREAD

**Issue by amnesia7** [tangrams/tangram#305]
Is it me or does it require more scroll zooming with the tangram map to zoom in and out?

It seems to require more scrolling (I'm using touchpad scrolling to zoom) to zoom in. 

Is this because image version would just jump from full world zoom straight to local zoom level if zoomed quickly whereas tangram tries to zoom through the different zoom levels to get from full world down to local zoom level?

**Comment by meetar** [comment]
Hi @amnesia7, thanks for the feedback! You may be right – what platform and browser are you using?

**Comment by amnesia7** [comment]
@meetar that was with latest chrome on 64bit linux.

**Comment by meetar** [comment]
Hi again @amnesia7 – the "image maps" you mention may well only be displaying whole-numbered zoom levels, whereas we've implemented "fractional zoom". If you make your own Tangram map, you can adjust this behavior using Leaflet's many zoom-related options. Thanks for your feedback!
