### ISSUE TITLE
External MVT source 

### ISSUE THREAD

**Issue by sevamoo** [tangrams/tangram#308]
Hi
Thanks a lot for the amazing work you do!
May I ask if possible, some one give me or show me an example how to use a tiled data source from an external source?

**Comment by nvkelso** [comment]
Hi @sevamoo, Thanks! Can you provide more information about your use case, please? Are you asking how to use Mapzen vector tiles in something like Leaflet or how to add custom data to the tile response (when you build from our source)?

**Comment by sevamoo** [comment]
My main problem is that I want to color code buildings based on some external features. For example, imagine I have pre-computed the distances of each building from the nearest public transport station or an we have estimated sale prices of large number of houses. Here, by large I mean something more than 1 million buildings. 
Therefore, seemingly geojson loading on the client side doesn't work I guess.
My initial understanding was that I need to develop a new vector tile (original osm + estimated features) and serve it on an external server?! and use it as a data source in Tangram scene file. Considering m current skills this idea at the moment is a bit complicated for me and for that I was asking for a possible similar example.
Further, I thought there should be a way to join osm building data with some other pre-computed features through something like osm ID. This would be fantastic.
Thanks a lot for any feedback.
B
V

**Comment by bcamper** [comment]
Answered via email.

**Comment by psaidurga13** [comment]
We want to use our custom mvt map (which is not the world map) but some indoor map. Can we use this library to achieve it by giving our own custom tiles?

**Comment by nvkelso** [comment]
Yes, any MVT source can be used with Tangram.
