### ISSUE TITLE
Default source[scripts] to same path as .yaml file

### ISSUE THREAD

**Issue by batje** [tangrams/tangram#314]
I have some javascript functions that produce styling for scenes that I would like to maintain in a separate file. 

The most sensible place to store that .js file is in the same folder of wherever my scene.yaml file is. (On my localhost or github for example). But currently I can only provide the full path to the javascript file.

I read the source of the DataSource object but I don't see an easy way of accessing the full path of the current Scenes.yaml file from there.

Would you be able to implement this, or provide a pointer as to how to provide some code myself?

**Comment by bcamper** [comment]
Hi @batje - can you provide a bit more detail to help me understand what you are trying to do - are you trying to pull in additional JS functions via the [`scripts`](https://mapzen.com/documentation/tangram/sources/#scripts) data source parameter? Or add additional JS functions to the scope executed by a JS [`filter`](https://mapzen.com/documentation/tangram/filters/#javascript-filters) function?

What functionality is included in your separate JS file? Depending on the needs, it may also be possible to make it a separate YAML file that defines JS functions as [`global` properties](https://mapzen.com/documentation/tangram/global/), and then [`import`](https://github.com/tangrams/tangram-docs/blob/gh-pages/pages/import.md) that into your main scene YAML.

Any YAML/JS snippets could be helpful here. Thanks.

**Comment by batje** [comment]
Sorry for being too vague. Yes, am using the [scripts] attribute of the source parameter.

This is the line in the yaml https://github.com/FruitsofThought/TheOtherMaps/blob/master/src/scenes/startdate.yaml#L44
And this is the javascript
https://github.com/FruitsofThought/TheOtherMaps/blob/master/src/scenes/startdate.js

I am calling the same javascript to build a legend in my app. (And somehow I am forced to load the startdate.js file twice for that, but that is another question perhaps)

If the code on this line could check whether there is a / in the passed script s, and if not, add the path to the yaml file in front of the value in s, that would be great.

**Comment by bcamper** [comment]
Thanks, that helps -- I do think it would be consistent to make the `scripts` URLs for data sources relative to the scene YAML they are specified in. I will create an issue for this and it should be in the next release (should be available within a week or so). (If you're interested, this will involve expanding the `scripts` URLs [here](https://github.com/tangrams/tangram/blob/master/src/scene_loader.js#L68), as is done for the source's `url`).

**Comment by bcamper** [comment]
@batje this will be part of the next Tangram release, 0.8, which should be released within a couple days. See #315 for more info.

**Comment by bcamper** [comment]
Released in [v0.8.0](https://github.com/tangrams/tangram/releases/tag/v0.8.0)
