### ISSUE TITLE
Drawing different shaped roofs.

### ISSUE THREAD

**Issue by hasan9206** [tangrams/tangram#316]
I've been trying to add 3-D Buildings in Tangram and have had pretty good results. I am however stuck at trying to give different shapes to the roof of buildings.
What I want is to have a circular dome on the top of my buildings, something like [this in osmbuildings](http://osmbuildings.org/?lat=52.51936&lon=13.40101&zoom=18.6&rotation=0&tilt=30):
![screenshot from 2016-05-25 18 04 12](https://cloud.githubusercontent.com/assets/7081695/15541014/c88daa38-22a3-11e6-9af6-2d35ff77da07.png)
I tried adding concentric circles, and giving them varying heights and extruding them, but had no success ( I think tangram is not taking the height in points, its only taking them as whole numbers )

Is there a way to make different shaped roofs, like domes, pyramids etc?

**Comment by hjanetzek** [comment]
Sure, there is a way :) It's certainly a bit of work though. One needs to implement a style that handles OSM S3DB tags and generates meshes for roof geometries. To start I would suggest looking into ```polygonStyle.cpp``` and its PolygonStyleBuilder

**Comment by hjanetzek** [comment]
Oh, this is not about tangram-es. Then it's of course not polygonStyle.cpp to start with.. 

https://github.com/OSMBuildings/Triangulate seems to have the geometry builders for roof shapes. Maybe you can adapt them for use in Tangram.

**Comment by hasan9206** [comment]
@hjanetzek you scared me for a second there, felt like I was doing it all wrong, since I haven't seen any `cpp` files in Tangram. 
Thanks for the quick reply, really appreciate it. I'll look into it but I'm not really sure where to start and how to adapt it for use in Tangram.

**Comment by hasan9206** [comment]
@hjanetzek you scared me for a second there, felt like I was doing it all wrong, since I haven't seen any `cpp` files in Tangram. 
Thanks for the quick reply, really appreciate it. I'll look into it but I'm not really sure where to start and how to adapt it for use in Tangram.

**Comment by bcamper** [comment]
@hasan9206 what @hjanetzek means is that you could adapt the code from OSMBuildings to create similar mesh models for Tangram -- the comparable Tangram builder file for that is here: https://github.com/tangrams/tangram/blob/master/src/builders/polygons.js. As he says, it is not a trivial effort, but it is possible for Tangram to render any 3d polygons generated by that function, so in theory it would work. We'll consider this support for the future, though we have no immediate plans to support it.

**Comment by ENT8R** [comment]
> We'll consider this support for the future, though we have no immediate plans to support it.

Why don't you leave this ticket open so one can find it better? I think adding this feature would be a great addition to this awesome library! But as it seems there are still no plans to add this in the near future, right?
