### ISSUE TITLE
Draw polygons with extrude values in decimal points

### ISSUE THREAD

**Issue by FarazKhalidZaki** [tangrams/tangram#318]
I am trying to render a building containing multiple polygons with different extrude values (extrude values are in decimal points e.g. {24.1,24.2,...,26.1}). Tangram rounds off the decimal point values. Right image in the following figure is the building which i am trying to render, and left is what tangram draws.

![3d_building_tngrmc](https://cloud.githubusercontent.com/assets/19620016/15626223/cff33662-24d8-11e6-93ad-1f439213a425.png)

May be the problem is with the array type in which values of vertices are pushed.

vertex_data.addVertex(vertex_template);

"vertex_template" contains decimal point values, but after adding vertex to "vertex_data" probabily it is rounded off. Please help me how can I change it to draw decimal point extrude values.

**Comment by bcamper** [comment]
Hi @FarazKhalidZaki -- thanks, you are correct, good catch. The values are quantized into integers (for consumption by WebGL), which wasn't really intentional, but we hadn't noticed an issue with real world data yet.

We have a fix for this in a [branch](https://github.com/tangrams/tangram/compare/height-precision), which will be included in our upcoming 0.8 release, which should happen within the next week or so. I'll mark this issue as part of that release.

**Comment by bcamper** [comment]
cc @blair1618 for ES

**Comment by blair1618** [comment]
Tangram-es currently encodes height values with a precision that varies with the size of the current tile, so there won't be any noticeable quantization. This creates a separate issue that arises with very, very tall geometry at high zooms, but I'll save that for another issue :)

**Comment by bcamper** [comment]
Note this is resolved by https://github.com/tangrams/tangram/commit/9c6123a373c638a16e7fc87861d0e99619445448, will close this issue when 0.8 is released.

**Comment by FarazKhalidZaki** [comment]
thanks @bcamper. One more thing, it would be too good if tangram has some triangulation methods for complex roof shapes and extrude method take arguments for "roof shape" and "shape parameters" e.g. radius and height.

**Comment by bcamper** [comment]
Unfortunately we do not support automatic triangulation of complex roof shapes. We might consider this in the future because there is some OSM support for it, but it hasn't been a priority yet. See related issue #316 too.

**Comment by bcamper** [comment]
Released in [v0.8.0](https://github.com/tangrams/tangram/releases/tag/v0.8.0)
