### ISSUE TITLE
tile edges sometimes extend outside of geometry

### ISSUE THREAD

**Issue by meetar** [tangrams/tangram#323]
With `tile_edges: true`, seen in https://gist.githubusercontent.com/kevinkreiser/1b1fe407c93ed68344c22ac6ff66c6ab/raw/a16b4d949fdc6bec055eae6654e80abf7f177165/valhalla_transit_tiles.geojson

Example scene: 
https://api.github.com/gists/05fc9809ae7c58ca84c0da353dbffd9a

<img width="197" alt="screen shot 2016-06-03 at 5 22 10 pm" src="https://cloud.githubusercontent.com/assets/459970/15793125/e2ed8b2e-29af-11e6-91cb-41c0c83cff92.png">
<img width="197" alt="screen shot 2016-06-03 at 5 21 51 pm" src="https://cloud.githubusercontent.com/assets/459970/15793124/e0c6ea84-29af-11e6-995f-6ffefa9d392c.png">
<img width="197" alt="screen shot 2016-06-03 at 5 21 01 pm" src="https://cloud.githubusercontent.com/assets/459970/15793123/de7fa3c4-29af-11e6-8a6e-fae4994635e9.png">

**Comment by bcamper** [comment]
Should be fixed in https://github.com/tangrams/tangram/commit/9e04c3345205d1d0161e684f2366b0c7e0549f45

cc @dmvaldman

**Comment by dmvaldman** [comment]
Reopening because there may be another edge case to consider

**Comment by dmvaldman** [comment]
Fixed in https://github.com/tangrams/tangram/pull/324
