### ISSUE TITLE
RFC: Change default position to (0, 0) and default zoom to 0

### ISSUE THREAD

**Issue by blair1618** [tangrams/tangram#328]
Currently, if no `position` or `zoom` is set in the `camera` node of a scene file, the camera position defaults to `[-74.00976419448854, 40.70532700869127]`, the southern tip of Manhattan, and the zoom defaults to `15`. This is a useful map area for testing rendering features, but is probably not the map area that a brand new user would expect to see with a new scene file. 

I think a default map position of `[0, 0, 0]` would better reflect our aim to build a tool for international, open-ended use. For our own testing and demos, we can add the current default position in the scene file.

**Comment by nvkelso** [comment]
+1, though a zoom of 2 might be more useful?

**Comment by blair1618** [comment]
Good point, zoom 0 is probably not very useful. Zoom 2 looks good on my small display, but looks small again on a larger monitor. 

In tangram-es the zoom is effectively clamped to the lowest value that fits the entire world vertically, so zoom 0 doesn't put the whole world in a fraction of the window. I had forgotten that tangram-js (or maybe leaflet?) doesn't do this.

**Comment by meetar** [comment]
+1, and zoom 2 works for me –  edges of our data are visible on a larger monitor, but as an overview and starting place it's easily comprehensible.

**Comment by bcamper** [comment]
While the world does revolve around NYC, I endorse this change. (Leaflet does not do any view clamping by default and Tangram does not add any, though users may if they choose.)

**Comment by blair1618** [comment]
Yep, our demos will still take place in the world's capital city :)

It happens that tangram-es already defaults to [0, 0, 0] (with view clamping) and I just realized that this diverges from the default stated in the documentation.

**Comment by bcamper** [comment]
So default zoom 0 or zoom 2? Either works for me.

**Comment by bcamper** [comment]
Turns out there's no default location in Tangram JS, this must exist in ES only (or may have existed prior but no longer). The position is always explicitly set by Leaflet (and Leaflet won't render the map until provided with a position).

**Comment by bcamper** [comment]
But I guess we should open an issue for this in ES, @blair1618?

**Comment by blair1618** [comment]
If no position is provided in tangram-es, the view currently defaults to a longitude and latitude of 0 and a zoom of 0.

**Comment by bcamper** [comment]
Updated in docs: https://github.com/tangrams/tangram-docs/commit/919a3d34d4179c376ea7472c6113d22c4a2c7fa8

**Comment by blair1618** [comment]
To clarify: is it desirable that position have "no default" rather than [0, 0, 2]? I'm unsure what that would mean for something like an Android SDK.

**Comment by bcamper** [comment]
Hm, well in Leaflet's case it simply won't render without an explicit position. If we were to remove the Leaflet dependency we'd have to revisit.

For ES, maybe it does make sense to have a default then. (I found the Leaflet behavior confusing, it's sometimes tripped me up that the map wasn't rendering because it wasn't "ready" yet.)

**Comment by blair1618** [comment]
I see! I can understand the reasoning there, it's a more "agnostic" treatment of position. The trouble I imagine with that is exactly what you described, that users would not understand why their map won't show up (especially if this parameter is labeled "optional").
