### ISSUE TITLE
transform: capitalize makes non-first letters lowercase

### ISSUE THREAD

**Issue by meetar** [tangrams/tangram#330]
```yaml
  font:
     transform: capitalize
```

Our docs say that `capitalize` capitalizes the first letter of every word, aka "title case". But it's also dropping the case of all other letters, eg "macArthur" -> "Macarthur". Is this desired? If so, what's the argument for it?

**Comment by bcamper** [comment]
I guess I hadn't thought about it too closely -- but if we think the expectation is that other capitalization should be left alone (reasonable), then it's a bug, and we can easily fix.

**Comment by meetar** [comment]
I suppose one argument would be for cases where the source text is already all-caps, but title case is preferred:

`TITLE CASE -> Title Case`

Of course this wouldn't know anything about words which ought to be interCapped:

`MACARTHUR -> Macarthur`

…but absent that data I suppose forcing title case is the best we can do.

**Comment by bcamper** [comment]
CSS spec says:

"Puts the first typographic letter unit of each word in titlecase; other characters are unaffected."

https://drafts.csswg.org/css-text/#propdef-text-transform

Probably best to follow that for consistency / ease of explanation.

**Comment by bcamper** [comment]
Updated to match CSS behavior in https://github.com/tangrams/tangram/commit/039b6459583bea68d31a73fffce42a2ff9cc77c5

**Comment by meetar** [comment]
:+1:
