### ISSUE TITLE
mystery squares: missing hemispheres when drawing sparse external json

### ISSUE THREAD

**Issue by meetar** [tangrams/tangram#331]
In this test, I have 5 squares arranged in a quincunx, with the center over null island:

http://tangrams.github.io/tangram-frame/?url=https://rawgit.com/tangrams/differ-tests/gh-pages/unit-tests/polygons/squares.yaml&lib=0.8#14/0/0

If I hide any of the other squares, whether with a data filter:

http://tangrams.github.io/tangram-frame/?url=https://rawgit.com/tangrams/differ-tests/gh-pages/unit-tests/polygons/squares1.yaml&lib=0.8#14/0/0

or a `visible: false`:

http://tangrams.github.io/tangram-frame/?url=https://rawgit.com/tangrams/differ-tests/gh-pages/unit-tests/polygons/squares2.yaml&lib=0.8#14/0/0

the center square is still drawn, as expected.

BUT if I remove any of the other squares from the data source, the portion of the center square in that semihemisphere is not drawn:

http://tangrams.github.io/tangram-frame/?url=https://rawgit.com/tangrams/differ-tests/gh-pages/unit-tests/polygons/squares3.yaml&lib=0.8#14/0/0
http://tangrams.github.io/tangram-frame/?url=https://rawgit.com/tangrams/differ-tests/gh-pages/unit-tests/polygons/squares4.yaml&lib=0.8#14/0/0
http://tangrams.github.io/tangram-frame/?url=https://rawgit.com/tangrams/differ-tests/gh-pages/unit-tests/polygons/squares5.yaml&lib=0.8#14/0/0
http://tangrams.github.io/tangram-frame/?url=https://rawgit.com/tangrams/differ-tests/gh-pages/unit-tests/polygons/squares6.yaml&lib=0.8#14/0/0

This is seen with any combination of semihemispheres:

http://tangrams.github.io/tangram-frame/?url=https://rawgit.com/tangrams/differ-tests/gh-pages/unit-tests/polygons/squares7.yaml&lib=0.8#14/0/0
http://tangrams.github.io/tangram-frame/?url=https://rawgit.com/tangrams/differ-tests/gh-pages/unit-tests/polygons/squares8.yaml&lib=0.8#14/0/0

... which means if the center square is the only shape in the data source, it will not be drawn:

http://tangrams.github.io/tangram-frame/?url=https://rawgit.com/tangrams/differ-tests/gh-pages/unit-tests/polygons/squares9.yaml&lib=0.8#14/0/0

This behavior is seen with versions of the library back to least v0.4.

**Comment by nvkelso** [comment]
+1

**Comment by bcamper** [comment]
Maybe the winding orders aren't consistent?

**Comment by meetar** [comment]
According to my math they're consistent – they were all drawn the same way,
using the geojson.io editor.

**Comment by bcamper** [comment]
@meetar seems the URLs for scenes and/or resources are out of date now...

**Comment by bcamper** [comment]
This appears to be another corner case with geojson-vt returning invalid polygons -- in this case, a degenerate / zero-area triangle was being generated, our winding order detection code was skipping these rings already, but the rest of the data source was not. They should now be thrown out of the pipeline in https://github.com/tangrams/tangram/commit/3760d81dcc1e167dc602b4cbf572f17ce2c21463. 

But it may be worth verifying the fixes explicitly with this test data again.

**Comment by meetar** [comment]
For the record the links should work again now.

**Comment by bcamper** [comment]
Released in v0.8.1 and verified with updated links.
