### ISSUE TITLE
external json: shapes contained by other shapes aren't drawn

### ISSUE THREAD

**Issue by meetar** [tangrams/tangram#333]
http://tangrams.github.io/tangram-frame/?url=http://tangrams.github.io/differ-tests/unit-tests/polygons/boxtest.yaml&lib=0.8#15/0.0099/-0.0154

If the left edge of the smaller box is moved just inside the perimeter of the larger box, the smaller box isn't drawn:

http://tangrams.github.io/tangram-frame/?url=http://tangrams.github.io/differ-tests/unit-tests/polygons/boxtest2.yaml&lib=0.8#15/0.0099/-0.0154

**Comment by bcamper** [comment]
I see the inner box on the second link, not what you see?

<img width="595" alt="screen shot 2016-06-17 at 8 47 11 pm" src="https://cloud.githubusercontent.com/assets/16733/16168103/bfa3b594-34cc-11e6-99df-afcfea962b11.png">

**Comment by meetar** [comment]
Accidentally changed the source geometry since I made the test, I've re-added the geo as boxtest4.geojson and the test should work (improperly) again:

http://tangrams.github.io/tangram-frame/?url=http://tangrams.github.io/differ-tests/unit-tests/polygons/boxtest2.yaml&lib=0.8#15/0.0109/-0.0154

<img width="444" alt="screen shot 2016-06-20 at 10 58 09 am" src="https://cloud.githubusercontent.com/assets/459970/16198981/ea0d15d6-36d5-11e6-8b97-dbead1857997.png">

**Comment by bcamper** [comment]
This appears to be an issue with geoson-vt, possibly with values near zero. I'm not entirely sure why, but I'm able to get this to work by adding a small `buffer` value to geoson-vt config (e.g. `buffer: 0.001`). I'll probably do that for now (I don't believe it should affect other data sources).

**Comment by bcamper** [comment]
Fixed in https://github.com/tangrams/tangram/commit/f9c4d26e229be4dc37dcede1c03211064734d595
