### ISSUE TITLE
RFC: Articulated Labels

### ISSUE THREAD

**Issue by dmvaldman** [tangrams/tangram#336]
Currently our label placement algorithm tries to place straight labels on segment midpoints if they can fit. Often this is too restrictive, especially for curvy roads, because often there is no road segment where a label fits entirely. Two approaches are to:

#### Break labels on spaces

By splitting a label such as _"Washington Blvd"_ into two - _"Washington"_ and _"Blvd"_ - we can place the label on (internal) segment ends in addition to segment midpoints, where the label is split and follows the angles of the previous and next line segments. For labels that are three or more words, such as _"George Washington Blvd"_, we would still split them into a set of pairs ([_"George Washington"_, _"Blvd"_] and  [_"George"_, _"Washington Blvd"_]) and try to fit the possibilities in the set, taking the first that fits.

The GL geometry (for a split label) would consist of creating two quads offset from an anchor point. We could do this by generalizing the point builder to include an offset (to be applied before any rotation). We can also consider a polyline geometry which would generalize to the case of more than two quads (described below).

**Pros**:
- Simple
- Keeps typography integrity (kerning, ligatures, etc)
- Works for all languages (text shaping, etc)

**Cons**:
- Label placement is still geometry dependent. Can't place label anywhere along a curve, or space them out regularly, etc. 
- Doesn't generate as many new label placements as a "break on characters" approach.
- For curved lines made of several short segments, the label cannot "curve around" the line; it can only kink in one place.

#### Break labels on characters

By breaking labels on any character we can place labels arbitrarily. The placement function doesn't need to consider midpoints or ends of segments, but can simply place based on some arbitrary spacing.

The GL geometry for such a label would consist of several quads in a chain like a polyline (but with no joins or miter vectors. I think we would need to modify the line builder to work with this type).

**Pros**:
- Complete control over label placement, as we are not dependent on the underlying geometry.
- Can generate many more labels
- Can allow for realtime dynamic label placement on zoom (though this would require development work in other areas)

**Cons**:
- Can mangle the typography
- No clear way to extend to languages like Arabic that incorporate text-shaping

cc @bcamper @hjanetzek

**Comment by bcamper** [comment]
Can you explain more why we would only break labels into two components when breaking on spaces (e.g. one "kink")? I had been imagining both of these approaches as different implementations of the same abstract algorithm that, given a list of arbitrarily sized boxes (each of which could contain a whole word, a set of characters, or a single character in the most extreme case), finds the most desirable contiguous placement of those boxes along a given line geometry (ideally biasing towards the placement with the fewest kinks). 

Broadly speaking, it's not acceptable to lose support for text shaping, but we can consider a "progressive" approach where we have more flexibility with some strings (those with Latin characters) than with others (Arabic and other unicode ranges not safe to break mid-word). But even without text shaping, when working per-glyph it is considerably difficult to create an acceptable level of typography layout without having access to the per-glyph metrics (advance values per character, etc.). The Canvas text rendering system in the browser provides a huge advantage here (in exchange for some disadvantages for sure...). It's theoretically possible to extract these with JS libraries (for example [this](https://github.com/nodebox/opentype.js) or [this](https://github.com/bramstein/opentype)), but it's a large increase in complexity that I'd prefer to not take on at this time.

Overall I'd like to manage incremental complexity, and establish a roadmap for better labels that can be rolled out over the course of several steps (some steps might be bigger than others, but aiming to keep them as small as possible per PR). The way I think about this (to start) is:

- Generate collision boxes: A function that, given a string of text, returns a list of boxes to collide against. This would depend on the unicode ranges of the string as described above. In the case of text like Arabic, it would likely only be able to break on spaces; for simpler text, we could consider breaking on smaller sets of characters, such as groups of 3. But we'd start simple, and just break on spaces for the first version. The caller doesn't need to know/care how the string is split up, it just gets a set of boxes back.
- Layout collision boxes: A function that, given a line geometry and a set of boxes, finds an acceptable contiguous placement of the boxes along the line (biasing towards straighter placements).

There's a potential multi-pass element here, where we might not need to bother breaking a string down into smaller components if the entire thing fits along a straight line segment already, but this might require multiple calls to Canvas `measureText()` to generate multiple word/character combinations. That's one reason that I think a basic approach that always splits on spaces is a good first step to prove the concept, and then if the placement algorithm is generic enough, can be easily extended.

**Comment by dmvaldman** [comment]
This was discussed IRL further. For posterity, there is a problem incurred from generalizing from a label split at a single location (like a space) and a label split at serval places (per multiple spaces, per glyph, etc). 

The problem being that a single kink can lie on any line segment end, whereas it's very rare to fit a label to a line when it's broken up in more than one place (the length of each split label would need to match length of each line segment for all internal labels). If you don't care where the label is broken up (on any character, say) then you are "unhinged" from the underlying road geometry as you can place labels anywhere, so that's fine. But if you do care where the label is broken up (say on spaces only), then you have to settle for having only 1 kink.

There may be more complex ways around this, such as doing line simplification. Here we'd be fitting a label with multiple kinks to a line, but instead of using the given line geometry, we can simplify the geometry in order to place the label. For instance, if the road wiggles along an axis, we can just pretend it's straight if we are within some error tolerance.

There may be other approaches to consider. Currently I'll be implementing the single kink version, and we can consider other approaches from there.

**Comment by bcamper** [comment]
Closing in favor of #360 for discussion
