### ISSUE TITLE
RFC: setting explicit height values on features with min_height

### ISSUE THREAD

**Issue by meetar** [tangrams/tangram#337]
Currently, features with a `min_height` property have unexpected behavior when drawn with a polygons style with an explicit height value (such as `extrude: 10`), possibly because the extrusion is moving the top-most vertices while leaving the lower-most hanging out by themselves in space:

In the case below, all extruded buildings are set to `extrude: 10`, which is the height of the lowest buildings visible – any features with a `min_height` ignore the `extrude` setting and are apparently extruded to the `min_height`:

<img width="556" alt="screen shot 2016-06-20 at 5 28 39 pm" src="https://cloud.githubusercontent.com/assets/459970/16210929/97382cec-370c-11e6-8473-961477e16e72.png">

This could be improved in a few ways:

1) set `min_height` to `0` if the `extrude` value is lower than the `min_height`
2) treat `extrude` values as distance from the baseline, whether `min_height` or an implied `0`
3) if a feature has both `height` and `min_height`, save the difference between them, treat an explicit `extrude` value as the new height, and set `min_height` to be that value minus the old difference - then extrude from the new `min_height` to the new `extrude` value
4) ignore features with a `min_height` altogether when setting an explicit height

… and possibly others. Comments?

**Comment by blair1618** [comment]
This seems to be a point of divergence: tangram-es ignores the `min_height` property when `extrude` is set to a scalar. That is, `extrude: 10` is equivalent to `extrude: [0, 10]`.

**Comment by bcamper** [comment]
The ES behavior make sense to me. @blair1618 is this right:

- `extrude: true`: use feature `height` and `min_height` if available, otherwise both default to 0 (no extrusion - **note this is another divergence from JS, which has a default extrude value of 20, that needs to be addressed separately**)
- `extrude: 10`: `height` is set to 10, `min_height` is set to 0
- `extrude: [5, 10]`: `height is set to 10, `min_height` is set to 5

**Comment by blair1618** [comment]
Yes, exactly that.

**Comment by meetar** [comment]
:+1: works for me

**Comment by bcamper** [comment]
Resolved in https://github.com/tangrams/tangram/commit/43dcac737e71e1b637d783238681415a0356a4d9
