### ISSUE TITLE
Generate warning event when scene `import` fails to load

### ISSUE THREAD

**Issue by bcamper** [tangrams/tangram#340]
Any `import`'ed scenes that can't load should generate a warning event (for example that Play can subscribe to for user feedback). See:

https://github.com/tangrams/tangram-play/issues/391

**Comment by bcamper** [comment]
First step is to continue loading the rest of hte scene and log an error to console: https://github.com/tangrams/tangram/commit/167da246f4974c6f3b89c820a3045b6e6389b8a4

Still need to look at triggering an external event.

**Comment by louh** [comment]
We're currently subscribing to `error` and `warning` events from Tangram, but it seems there are warnings (and also errors?) that are logged to console but not emitted through the same event handlers. Is there any reason why it shouldn't?

**Comment by bcamper** [comment]
These are two different systems at the moment (logging and external event emitting). It would make sense to unify them, but it's a larger project. In the meantime, we should document warnings/errors emitted by Tangram and wire them up appropriately in Play.

**Comment by bcamper** [comment]
@louh I have an initial version of this working in https://github.com/tangrams/tangram/compare/scene-load-error-event, but would like to talk with you and think on the current + future API a bit more.

**Comment by bcamper** [comment]
Merged the `scene-load-error-event` branch, it's a good start. We may need to expand the info returned to deal with multiple levels of scene imports, but deferring that until more work is done with [scene bundles](https://github.com/tangrams/tangram/issues/253).

**Comment by bcamper** [comment]
@louh this event is included in the v0.8.2 release, we can refine with more info as we try it out (and start experimenting with bundles / nested tabs).
