### ISSUE TITLE
Error: Unimplemented type: 3,4,7..

### ISSUE THREAD

**Issue by shahzadbacha** [tangrams/tangram#342]
I am serving[ mapnik vector tiles](https://github.com/mapbox/mapnik-vector-tile) (.mvt) using [TileStache](https://github.com/TileStache/TileStache) from postgresql database which works perfectly. 

![tilestache](https://cloud.githubusercontent.com/assets/16791779/16330289/9e2b27e6-3a01-11e6-95a5-b714eae0a7b7.PNG)

But when i try to render these mvt tiles using Tangram, it throws the error 'Error: Unimplemented type : 3,4,7'

![tangram](https://cloud.githubusercontent.com/assets/16791779/16330298/ab1aa0da-3a01-11e6-9bdf-384c37ede025.PNG)

I have tried to render both compressed and uncompressed mvt tiles but still got blank screen.
Any ideas on, why is this happening and how can i resolve this?

OS: Windows 7
Browser: Google Chrome V 51.0

**Comment by ligai322** [comment]
Your  mvt data is error  ,  you can use [vector-tile-js ](https://github.com/mapbox/vector-tile-js) to parse your mvt file, If still have this error ,the data has some problem.
maybe is your file encoding problem, because mvt must ascii format

**Comment by shahzadbacha** [comment]
I don't know if that's the case. This is how my mvt file looks like 
```
 894d 5654 0000 0055 789c 6360 6060 6260
 6088 6564 0692 8c40 ccca 0006 1ff9 b9e3
 1d81 b4be 4191 9f23 127f fde4 1230 7fa3
 230f 563e ba7a 185f b05a 292f 3137 55c9
 4a41 293f 3935 314f a996 1eb6 8a20 6c0d
 48cc ce2c 2e01 590c 00ef 4c2e fb
```

**Comment by bcamper** [comment]
Hi @shahzadbacha, I believe @ligai322 is correct, this is likely an issue with your data, because those errors indicate unexpected protocol buffer binary data. We are using the official MVT JS library, [vector-tile-js](https://github.com/mapbox/vector-tile-js), to decode these, and it is generating these errors (but they come from even deeper, from the underlying protocol buffer decoder).

@rmarianski I can't recall now, do you have a command-line tool that can be used to verify MVT tiles?

**Comment by rmarianski** [comment]
Yup, but it's really just an example delegating to the official vector-tile js library. It assumes a particular layer name, but can probably be adapted easily enough.

https://github.com/mapzen/mvt-encoding-test

**Comment by shahzadbacha** [comment]
You people are right. I tested my mvt tiles with the link @rmarianski provided and i got the same error ('unimplemented type: +type) which means the tiles have encoding issue.
Thanks for the help!

**Comment by bcamper** [comment]
Thanks, good luck with your tiles and hope to see them on Tangram soon :)
