### ISSUE TITLE
Undesirable query parameter when loading raster tiles

### ISSUE THREAD

**Issue by mmmatthew** [tangrams/tangram#343]
A timestamp is added as a query parameter to the url of raster tiles. For most tile sources, this doesn't seem to be an issue, but for mapbox tiles, it is problematic: the timestamp is not recognized as a valid query parameter and an error is raised.
![image](https://cloud.githubusercontent.com/assets/10126798/16346648/b60aab92-3a48-11e6-94d8-11527f67a775.png)

**Comment by meetar** [comment]
Thanks very much, we'll take a look! There may be a better way to implement 'cachebuster' parameters in these cases.

**Comment by bcamper** [comment]
Thanks @mmmatthew, agreed these are undesirable, that code is verrry old. They will be removed in the next patch release of Tangram, v0.8.2 :) I will keep this ticket updated when that happens.

**Comment by bcamper** [comment]
@mmmatthew this is now fixed in the [v0.8.2](https://github.com/tangrams/tangram/releases/tag/v0.8.2) release of Tangram. It is available at any of these endpoints:

https://mapzen.com/tangram/tangram.min.js
https://mapzen.com/tangram/0.8/tangram.min.js
https://mapzen.com/tangram/0.8.2/tangram.min.js

**Comment by mmmatthew** [comment]
Great, thanks!

On Fri, Jul 8, 2016, 17:20 Brett Camper <notifications@github.com> wrote:

> @mmmatthew <https://github.com/mmmatthew> this is now fixed in the v0.8.2
> <https://github.com/tangrams/tangram/releases/tag/v0.8.2> release of
> Tangram. It is available at any of these endpoints:
>
> https://mapzen.com/tangram/tangram.min.js
> https://mapzen.com/tangram/0.8/tangram.min.js
> https://mapzen.com/tangram/0.8.2/tangram.min.js
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/tangrams/tangram/issues/343#issuecomment-231388279>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AJqFzhmteMAr3Zo5M962EYBdOuLAR1jwks5qTmqogaJpZM4I-ALj>
> .
>
-- 


Matthew
