### ISSUE TITLE
Mapnik Vector Tiles vs Mapbox Vector Tiles

### ISSUE THREAD

**Issue by hasan9206** [tangrams/tangram#345]
Hi! I am trying to improve the performance of my maps. I am using TileStache to serve Vector Tiles in GeoJSON, and I want to shift to MVT (I've tested it a bit and there is a significant reduction in size of the tiles when they are in MVT).

TileStache uses [Mapnik Vector Tiles](http://tilestache.org/doc/TileStache.Goodies.VecTiles.mvt.html) while Tangram says it uses [Mapbox Vector Tiles](https://mapzen.com/documentation/tangram/sources/#type). Is there a difference between the two? Can I use Mapnik Vector Tiles in Tangram?

**Comment by nvkelso** [comment]
As long as the output format is GeoJSON, TopoJSON, or MVT it “should” work.
The Mapbox Vector Tiles (MVT) format is a protocol buffer encoded
representation of the data, but there are several major alternatives for
what actually shows up in the tiles (from Mapbox, Mapzen, Esri, and others).

**Comment by bcamper** [comment]
"Mapnik Vector Tiles" was simply an earlier name for "Mapbox Vector Tiles". They have updated the spec to change the name, but the format and data structure is otherwise the same.
