### ISSUE TITLE
properties filter cannot be used

### ISSUE THREAD

**Issue by ligai322** [tangrams/tangram#348]
I  used the [filters-demo](https://github.com/tangrams/filters-demo)  and upgraded tangram to  0.8. 
But the filter can not work, has some issues.
![1](https://cloud.githubusercontent.com/assets/3262486/16477792/7d68c50c-3ec7-11e6-9479-63b318026097.jpg)

**Comment by judequinn** [comment]
We managed to solve this by adding 'properties' item to whiteList array in tangram.js file itself, but it's obviously hacky and unintended.

**Comment by bcamper** [comment]
Hi @ligai322 and @judequinn -- apologies, the layer-level `properties` were actually deprecated in Tangram 0.7, and this demo needs to be updated (cc @meetar).

This behavior has been replaced with `global` properties, which can accomplish the same thing (and more) in a slightly different syntax: https://mapzen.com/documentation/tangram/global/#global

Feel free to reach out with questions on the differences.
