### ISSUE TITLE
Support multiple map instances on one page

### ISSUE THREAD

**Issue by bcamper** [tangrams/tangram#350]
We currently have several places where global state prevents us from displaying multiple maps on the same page. This can be circumvented with iframes, but that's not an ideal solution. The ES team is also working on a similar refactor to support multiple maps instances. Here's a running list of known things that would need to be addressed to enable this on the JS side:
- [x] `RenderState` (manages GL state) is a singleton, should be instantiated per GL context (e.g. per scene).
- [x] `VertexArrayObject` (manages VAO extension & bindings) is a singleton, should be instantiated per GL context (e.g. per scene).
- [ ] Some internal event targets (e.g. from `Texture` to a scene instance) are singletons. Event system may need to be refactored for better cross-object coordination.
- [ ] `ShaderProgram` maintains global `#defines` and shader blocks that are scene specific, should be instantiated per scene.
- [ ] `Texture` manages global set of textures, should be instantiated per scene (maybe a `TextureManager` per scene).
- [ ] `Style` main/worker thread communication makes some related assumptions about textures being global.
- [x] `StyleManager` maintains a global set of styles, should be instantiated per scene.
- [x] `TileManager` is a singleton, should be instantiated per scene.
- [x] `TilePyramid` is a singleton, should be instantiated per scene.
- [ ] `CanvasText` manages custom font loading globally, should be managed per scene.

**Comment by bcamper** [comment]
Knocked off a couple of the easy ones:
- `TileManager` instances: https://github.com/tangrams/tangram/commit/165b2539a80cda2a576dceb38b172e176e8834a7, https://github.com/tangrams/tangram/commit/b4a4354e2fd3812e03410d4b7991165dbdce0952
- `TilePyramid` instances: https://github.com/tangrams/tangram/commit/9846c14be50c372593cfb54793ccd54c36b42e2c

**Comment by bcamper** [comment]
- Manage `VertexArrayObject` extensions per GL context: https://github.com/tangrams/tangram/commit/5fc0869eceb2aa752fe7f87d37868260bd88a9f5

**Comment by bcamper** [comment]
- Manage `RenderState` entries per GL context: https://github.com/tangrams/tangram/commit/8b4d2858d39824188cf145bda9ae26976c660997

**Comment by bcamper** [comment]
- Separate `StyleManager` per scene: https://github.com/tangrams/tangram/commit/c80c0e6297691f36e3acaaa997f91dd3a85225f1
- Increment `generation` across all scene instances: https://github.com/tangrams/tangram/commit/9c8056554cefff80a2dad9d2321a90e5c9116192

**Comment by hwhelchel** [comment]
How can you use `iframe`s to get multiple maps on one page?

**Comment by meetar** [comment]
@hwhelchel The general idea is to make a web page for each map, and then use each page as the "src" of an iframe.

We've been using a custom map-displaying page called [tangram-frame](https://github.com/tangrams/tangram-frame) to do this in our blog posts – it accepts a number of URL parameters including a Tangram scene file, and does all the HTML setup to display it, like so:

http://tangrams.github.io/tangram-frame/?url=https://raw.githubusercontent.com/tangrams/tangram-sandbox/gh-pages/styles/blueprint.yaml#15/40.7053/-74.0097

In the above case, the "blueprint" style is passed as the "url" parameter to tangram-frame. We use URLs like that as the "src" of iframes to load multiple maps on one page, such as in these posts:

https://mapzen.com/blog/escape-from-mercator/
https://mapzen.com/blog/mapping-mountains/

If you view the source of those posts, you'll see they also have additional code to selectively load and unload iframes, to prevent all the maps from drawing at once and consuming resources unnecessarily. That may not be needed if you're only displaying a few simple maps at once, though.

**Comment by hwhelchel** [comment]
Thanks for the explanation. I was able to get iframes "working" 😜 last night on desktop. 
I was trying to load 8 maps at a time on the page. This was crashing hard on mobile so I tried 4 which still crashed the site on mobile. I switched to static maps this morning for now. Will be curious to see when you all have multiple maps ready to try it again. iframes are resource intensive as you said so it could just be that I was loading too many at once.

For posterity's sake, if you set the `src` of the iframe programmatically in JS it prevents the iframe from blocking `onload` from firing for the main page which helped a little when loading multiple maps.

**Comment by hwhelchel** [comment]
@meetar is there a mapzen / tangram static map api?

**Comment by meetar** [comment]
@hwhelchel Not at this time!

**Comment by bcamper** [comment]
@hwhelchel We do not have a static map service at this time, but it's on our roadmap to offer in the future.

I agree that static maps are a better approach for many maps on a single page. Once this issue is resolved and released, it will be possible to load multiple maps with a single Tangram instance. This will significant reduce the resource overhead compared to iframes. However my gut instinct it that after more than ~4 maps, static may be the best way to go. We'll be able to offer better guidance once we have something working though!

**Comment by hwhelchel** [comment]
Ok cool thanks again!

On Tuesday, July 12, 2016, Brett Camper <notifications@github.com> wrote:

> @hwhelchel <https://github.com/hwhelchel> We do not have a static map
> service at this time, but it's on our roadmap to offer in the future.
>
> I agree that static maps are a better approach for many maps on a single
> page. Once this issue is resolved and released, it will be possible to load
> multiple maps with a single Tangram instance. This will significant reduce
> the resource overhead compared to iframes. However my gut instinct it that
> after more than ~4 maps, static may be the best way to go. We'll be able to
> offer better guidance once we have something working though!
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/tangrams/tangram/issues/350#issuecomment-232082522>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AEkgNwT44pqt4CC-fXXKnlIJSYk2uyKwks5qU7EtgaJpZM4JHZ9p>
> .
>


-- 
Harry

**Comment by mattrei** [comment]
Hi guys,

I want to use multiple Tangram maps on my page, however *not simultaneously*. How should we handle this use case?
Tangram does not provide a public API for deleting a Tangram instance, once it was created. Or is it a simple a remove of the Leaflet DOM node?

However it should be still  possible to make use of the Leaflet Layer and just remove the Tangram instance from the Leaflet layer, nor?

Thx & best,
Matthias

**Comment by skorasaurus** [comment]
@mattrei see https://github.com/mapzen/mapzen.js/issues/318

**Comment by bcamper** [comment]
@mattrei Yes, simply removing the Leaflet layer (e.g. `layer.remove()`) will cause all the Tangram resources to be deallocated. It should work as long as you avoid having more than one map loaded at a time, and some users have done this with Leaflet layer controls. Of course, we would like to just solve the underlying issue :)  Let us know if you have further issues with this.

(Also worth looking at related discussions that @skorasaurus pointed out if you are interested in more cases.)

**Comment by dmvaldman** [comment]
Is this in our documentation somewhere @meetar?

**Comment by meetar** [comment]
I don't think so but it can easily be added.

**Comment by meetar** [comment]
Note about `layer.remove()` added to docs with https://github.com/tangrams/tangram-docs/commit/f6fcf6e809778808842e78bccb4b04ec23854f40.
