### ISSUE TITLE
Debug flag to visualize label collision boxes

### ISSUE THREAD

**Issue by bcamper** [tangrams/tangram#353]
@dmvaldman created some debugging rendering of label collision boxes by simply drawing the boxes in the underlying texture, with Canvas.

It would be generally useful to expose this option behind a debug flag. We currently have a `debug` property on the `Scene`, which can be used to configure a few different debug flags: https://github.com/tangrams/tangram/blob/master/src/scene.js#L1127.

However, this may not be the best approach to extend, given that the scene object won't always be available in other modules like `CanvasText`. Perhaps we should consider moving these to a global level, e.g. `Tangram.debug`, or something similar (note we'd probably still have to "sync" debug settings to worker threads)?

**Comment by dmvaldman** [comment]
Should we add this as an option on the scene file? Something like:

```
{
    ...
    text:
        bounding_box: true,
        color: 'red',
        width: 1px
}
```

Or would you rather it be a debug setting?

**Comment by bcamper** [comment]
The pattern we usually follow is to implement these types of things with a way to turn them on/off at run-time. We could consider some type of `debug` flag that could be turned on in the scene file for authoring purpose, but even then I think letting people style their debug lines is going a bit far :)

Let's just make it configurable via `Tangram` (or another JS object) for now.

**Comment by dmvaldman** [comment]
Initial implementation here: https://github.com/tangrams/tangram/compare/label-boxes

I created a new file called `debug_settings.js` in `utils`. Maybe we could move other such settings there? It would also be nice to have a function you can run on the command line to rebuild the scene after patching something in the `debug_settings`

**Comment by bcamper** [comment]
Makes sense - added a few comments on the commit.

What do you think of migrating this [scene debug param](https://github.com/tangrams/tangram/blob/master/src/scene.js#L1134-L1136) (for profiling) there too?

**Comment by dmvaldman** [comment]
Sure, do you have a more descriptive name for `geometry_build`? Or maybe a one-liner that I can add as a comment above each debug flag?

**Comment by bcamper** [comment]
Yeah we can rename it, the idea of nesting them under different groups (`profile.geometry_build`) might have been overkill :)  It could be something like `profile_geometry_build_time`? It's that flag we use to time how long it takes for tile geometry to build, if you have other suggestions. I just added a new debug flag in a branch we can move to this pattern too once it's merged.

**Comment by dmvaldman** [comment]
Closing to move the discussion to the PR https://github.com/tangrams/tangram/pull/371
