### ISSUE TITLE
Add parameter to prevent excessively tall text labels

### ISSUE THREAD

**Issue by bcamper** [tangrams/tangram#357]
We should consider adding a `max_lines` parameter for text wrapping, to prevent labels that are comically tall:

![screen_shot_2016-07-13_at_12 53 52_pm](https://cloud.githubusercontent.com/assets/16733/16855827/271cc332-49e5-11e6-98d0-4b7daddcd7c2.png)

**Comment by bcamper** [comment]
@nvkelso what do you think?

**Comment by nvkelso** [comment]
_hahahaha_

Would it be better to add a `max_char` count instead that would apply generally to avoid super long text?

**Comment by dmvaldman** [comment]
Seems google maps does a maximum number of characters and then adds an ellipsis (on the next complete word)

<img width="282" alt="screen shot 2016-07-15 at 11 14 38 am" src="https://cloud.githubusercontent.com/assets/796394/16879176/6dc6995a-4a7d-11e6-9512-53975dec780d.png">

**Comment by nvkelso** [comment]
Leveling up for power punctuation! I kinda like it.

**Comment by bcamper** [comment]
@dmvaldman would you want to give this a try with the ellipsis method? I think the place to add this logic would be [`parseTextSource()`](https://github.com/tangrams/tangram/blob/master/src/styles/text/text_labels.js#L67).

**Comment by dmvaldman** [comment]
How would we like to expose this as a scene file parameter?

**Comment by bcamper** [comment]
`max_lines`? Since we allow the user to control the length of a line with `text_wrap`, that gives a lot of flexibility. And we can try the ellipsis on the final line?

@nvkelso?

**Comment by dmvaldman** [comment]
Note a max character count is not exactly precise as you would likely want to complete the word that overflows the character count. Additionally, you'd like to continue the entire line that overflows (with the addition of an ellipsis to it)

**Comment by bcamper** [comment]
Yep I believe we already do that - the line needs to be *whole words* and those words *together* can't exceed the `max_chars` value.

**Comment by dmvaldman** [comment]
Consider the following label text: "this label is a very very very very very very long label". 

Say it's displayed like

```
this is a very very very
              very...
```

It's preferable to complete the last line, since the thing you want to constrain is vertical space, not horizontal space (within the wrapping value). So you want

```
this is a very very very
 very very very very...
```

Which is clearly, much more informative.

So I vote for using a `max_line` value as @bcamper suggested as opposed to a `max_char` value.

**Comment by bcamper** [comment]
Makes sense but how does that interact with [`text_wrap`](https://mapzen.com/documentation/tangram/draw/#text_wrap) parameter which can be used to set the max number of characters per line? (A factor which comes into play more often than a max number of vertical lines.)

**Comment by dmvaldman** [comment]
I'm opting for both `text_wrap` to specify the maximum width, and `max_lines` to specify the maximum height (dependent on the font's `line_height` implicitly)
