### ISSUE TITLE
Support TMS tiles

### ISSUE THREAD

**Issue by Tristramg** [tangrams/tangram#359]
Currently tangram seems to only support XYZ tiles when defined in a scene file.

On leaflet, a simple `tms: true` must be defined when adding a `L.tileLayer`

**Comment by bcamper** [comment]
@Tristramg - do you have a TMS endpoint we can test this against? I don't have any readily available :)

**Comment by bcamper** [comment]
WIP in https://github.com/tangrams/tangram/compare/source-tms

**Comment by bcamper** [comment]
@Tristramg ping again to see if you have a test endpoint we could use - thanks!

**Comment by Tristramg** [comment]
Wow! thanks a lot :) Sorry for my silence, I had nearly no connectivity during my holidays.

Actually, I had this problem with hand made tiles with gdal2tiles, but `http://demo.opengeo.org/geoserver/gwc/service/tms/    1.0.0/ne:ne@EPSG:900913@png/{z}/{x}/{y}.png` seems to be on the right format.

**Comment by bcamper** [comment]
@Tristramg thanks! Success:

Here's a minimal scene file for rendering your tiles (note the `tms: true`):

https://gist.github.com/anonymous/e091ff4b9fc06beb89ca08330ba3e6f5

And here's an example live link, pointing to a dev build of this branch:

http://tangrams.github.io/tangram-frame/?url=https://gist.githubusercontent.com/anonymous/e091ff4b9fc06beb89ca08330ba3e6f5/raw/0ed6756e25e52935a690724f7e8f633e05fe00b1/scene.yaml&lib=https://precog.mapzen.com/tangrams/tangram/source-tms/dist/tangram.min.js#6/40.681/-72.532

This functionality will be added in the Tangram v0.10 release, which should be within the next week or two.

**Comment by Tristramg** [comment]
Faboulous! :+1:

**Comment by bcamper** [comment]
Support for this released in [v0.10.0](https://github.com/tangrams/tangram/releases/tag/v0.10.0)!
