### ISSUE TITLE
Unable to load scene.yaml while running webpack-dev-server

### ISSUE THREAD

**Issue by MRokas** [tangrams/tangram#361]
**TO REPRODUCE THE ISSUE, FOLLOW THESE STEPS:**

_index.html_ includes 
`<script src="app/tangram.js"></script>
<script src="app/app.js"></script>`

Inside _app.js_ I've 
`const Layer = Tangram.leafletLayer({
    scene: 'app/scene.yaml',
    attribution: '<a href="https://mapzen.com/tangram" target="_blank">Tangram</a> | &copy; OSM contributors | <a href="https://mapzen.com/" target="_blank">Mapzen</a>'
});`

I can access _scene.yaml_ by _localhost:8080/webpack-dev-server/app/scene.yaml_

**RESULT:**

> Tangram v0.8.2 [error]: Scene.load() failed to load app/scene.yaml: Can't load worker because couldn't find base URL that library was loaded from Error: Can't load worker because couldn't find base URL that library was loaded from
Stack trace:
[223]</Z</<.value@http://localhost:8080/app/tangram.js:9:22086
[223]</Z</<.value@http://localhost:8080/app/tangram.js:9:23009
[223]</Z</<.value/this.initializing<@http://localhost:8080/app/tangram.js:9:19406
promise callback*[223]</Z</<.value@http://localhost:8080/app/tangram.js:9:19363
i/t</<.onAdd@http://localhost:8080/app/tangram.js:8:15876
o.Layer<._layerAdd@http://localhost:8080/app/leaflet.js:6:3060
o.Map<.whenReady@http://localhost:8080/app/leaflet.js:6:584
.addLayer@http://localhost:8080/app/leaflet.js:6:3393
o.Layer<.addTo@http://localhost:8080/app/leaflet.js:6:2443
@http://localhost:8080/app/app.js:1:465
t@http://localhost:8080/app/app.js:1:102
@http://localhost:8080/app/app.js:1:194
@http://localhost:8080/app/app.js:1:2

**EXPECTED RESULT:**

_scene.yaml_ should be loaded :/

**ENVIRONMENT:**
Windows 7 32-bit, Firefox 49.0a2

**OTHER:**

Inside Network tab in DevTools, I can see scene.yaml among loaded files. It loads correct file too.

**Comment by meetar** [comment]
Hi @MRokas – The web workers expect that the Tangram .js file be named one of `tangram.debug.js` or `tangram.min.js` – could you try renaming the .js file to one of those filenames?

**Comment by MRokas** [comment]
Yes, that fixes the problem. Thanks!

**Comment by meetar** [comment]
Glad to hear!
