### ISSUE TITLE
filter for scalerank:0 fails in 0.8

### ISSUE THREAD

**Issue by meetar** [tangrams/tangram#362]
`filter: {scalerank: 0}`

returns no matches in 0.8, but does < 0.8.

Differ test: http://tangrams.github.io/differ/?1=https%3A//raw.githubusercontent.com/tangrams/differ-tests/gh-pages/unit-tests/filters/scalerank-0.yaml&2=&lib1=0.7&lib2=0.8&go

Scene file: https://raw.githubusercontent.com/tangrams/differ-tests/gh-pages/unit-tests/filters/scalerank-0.yaml

**Comment by nvkelso** [comment]
I believe these are to deal with bad region boundary data in Hungary in all house styles?

**Comment by meetar** [comment]
@nvkelso Interesting, what you mean by "these"?

**Comment by meetar** [comment]
Interesting, I'm seeing quite a few all over the world in the explorer:

<img width="1890" alt="screen shot 2016-07-20 at 4 38 31 pm" src="https://cloud.githubusercontent.com/assets/459970/17002284/995871aa-4e98-11e6-8f55-4217a5162393.png">

Image source: http://tangrams.github.io/explorer/#2.9/33.3293/-10.5780/scalerank/0

… Is this old data?

**Comment by nvkelso** [comment]
Those country labels are valid scale rank 0 data.

**Comment by meetar** [comment]
Aaaaand I just realized the explorer is using v0.8, so the original title of this issue is incorrect – I'll re-investigate and try to narrow it down.

**Comment by meetar** [comment]
Okay, I figured out why it was working in the explorer but not in a regular scene file. Here's a new test:

https://mapzen.com/tangram/play/?scene=https%3A%2F%2Fgist.githubusercontent.com%2Fanonymous%2F923e51866e4d3fc4768aea3e7e29d9aa%2Fraw%2F5e0d03e5b7768a4c4022c1e8cf9adae5c3f3d560%2Fscene.yaml#2/3.2/49.7

If you uncomment out line 18:

`filter: { scalerank: 0 }`

and comment out the filter below it:

```filter: |
                function() { return String(feature['scalerank']).indexOf('0') > -1; }```

the points will disappear. The explorer was casting both the filter key and value to strings and looking for a match that way. So now I'm wondering whether the plain filter parser is interpreting the 0 as falsey.

**Comment by bcamper** [comment]
Fixed in https://github.com/tangrams/tangram/commit/101d4aa64d86eaca2f386b720158e27a876dcc05

**Comment by meetar** [comment]
Confirmed!

<img src='https://cloud.githubusercontent.com/assets/459970/17531421/cc61d6fc-5e49-11e6-91ef-093eaed48a58.jpg' width=250>
