### ISSUE TITLE
'vanishing_point' displacement is half the expected value

### ISSUE THREAD

**Issue by blair1618** [tangrams/tangram#372]
For bug reports, please use this template:

**TO REPRODUCE THE ISSUE, FOLLOW THESE STEPS:**

- Open Tangram Play and load the 'default' sample scene.
- In the editor, change `cameras.perspective.vanishing_point` to `[600, 0]`

**RESULT:**

The vanishing point of 3d geometry in the scene is 300 logical pixels to the right of the center of the map view.

**EXPECTED RESULT:**

The vanishing point should be __600__ logical pixels to the right of the center of the map view, according to my reading of the documentation: https://mapzen.com/documentation/tangram/cameras/#vanishing_point

**ENVIRONMENT:**

Firefox 47 on Mac OS 10.11.6

**OTHER:**

![screen shot 2016-08-01 at 1 50 03 pm](https://cloud.githubusercontent.com/assets/3371850/17303994/51e38f8c-57f1-11e6-98c0-09d67169f913.png)

**Comment by bcamper** [comment]
Resolved by https://github.com/tangrams/tangram/commit/b094ccbb3b042cfb8c4719d1240abccb88c3fc81
