### ISSUE TITLE
Change generated polygon centroids `label_placement` to match vector tiles 1.0

### ISSUE THREAD

**Issue by bcamper** [tangrams/tangram#377]
When we release Mapzen vector tiles 1.0, we should change our synthesized polygon centroid features (enabled with `generate_label_centroids` on GeoJSON/TopoJSON sources) to match the new terminology:

Instead of `label_placement = yes`, it is now `label_placement = true`.

**Comment by nvkelso** [comment]
👍

**Comment by dmvaldman** [comment]
I can change this. Should we accept both `true` and `"yes"` for backwards compatibility with a depreciation warning thrown when `"yes"` is used? Or just peel the bandaid off all at once?

**Comment by bcamper** [comment]
Hmm, accepting both for backwards compatibility would be nice, but it would require special handling since this feature works by just generating new feature properties that are then filtered (with the `filter`) like any other... so it would need special-case code :/

We can probably get away with deprecating since this feature is not in heavy use yet.

**Comment by nvkelso** [comment]
+ @burritojustice

**Comment by burritojustice** [comment]
fine to rip off the bandaid, just a couple of instances (that I know) of that are easily changed.
