### ISSUE TITLE
Support filtering based on pixel area

### ISSUE THREAD

**Issue by bcamper** [tangrams/tangram#380]
As suggested in #320, we can considerably simplify styling of polygons by supporting filtering by pixel area (for the given styling zoom). Pixel area would be adjusted for device pixel ratio to maintain device-independent styling. 

The simplest approach would be to support a new unit type like `px` or `px2` (`px` already means linear pixels in some other contexts) to the current `{min, max}` filter syntax.

**Comment by nvkelso** [comment]
+1 for px2

**Comment by meetar** [comment]
+2!

**Comment by bcamper** [comment]
WIP in https://github.com/tangrams/tangram/compare/area-filter

**Comment by bcamper** [comment]
Released in [v0.10.0](https://github.com/tangrams/tangram/releases/tag/v0.10.0)!
