### ISSUE TITLE
Unable to render pbf tiles hosted at mapbox

### ISSUE THREAD

**Issue by 20sandeepsingh** [tangrams/tangram#382]
Somehow tangram is not able to render MapBox hosted pbf tiles. I have changed the tile source in style.yaml as follows
sources:
      osm:
              type: MVT
              url: https://b.tiles.mapbox.com/v4/mapbox.mapbox-terrain-v2,mapbox.mapbox-streets-v7/{z}/{x}/{y}.vector.pbf?access_token=mapbox-access-token

I am able to see the received pbf response, but UI remains blank, completely blank and no errors or warnings are generated. None of the tiles are displayed.

**Comment by meetar** [comment]
In your url, you must replace the string `mapbox-access-token` with a mapbox access token. Learn how to create a token here: https://www.mapbox.com/help/create-api-access-token/

**Comment by 20sandeepsingh** [comment]
I had obviously replaced that string with actual mapbox access token. I am able to see the received pbf response, but tiles does not show up.

**Comment by hjanetzek** [comment]
@meetar is the layer schema similar enough that mapbox tile features are matched by our styles?

**Comment by meetar** [comment]
Yes, Tangram should be able to render their tiles – here's an example showing their 'water' layer: https://mapzen.com/tangram/play/?scene=https%3A%2F%2Fapi.github.com%2Fgists%2F0185bca697d3344208a87327ac63bb23#15.6548/40.7071/-74.0141

If no layers are displayed, it's possible that an incorrect layer name was specified. @20sandeepsingh, would you be able to share your yaml with us, or at least the `layers` block?

**Comment by 20sandeepsingh** [comment]
I am using cinnabar-style.yaml referenced in one of your examples. I had just changed the tile source and it stopped working.

**Comment by meetar** [comment]
Yes, that style is dependent on layer names present in the mapzen tile source – the mapbox tile source has a different tile set with different layer names. You may be able to fork the Cinnabar style to a version which uses the mapbox tiles, but you probably won't be able to replicate the style exactly.

For more information about the relationship between layers and styles in Tangram, check out the [Filters Overview](https://mapzen.com/documentation/tangram/Filters-Overview/) in our documentation.

**Comment by 20sandeepsingh** [comment]
can you help me in fetching the version of cinnabar style which uses mapbox tiles, i tried searching but couldn't find it anywhere.

**Comment by meetar** [comment]
The cinnabar style was designed for mapzen vector tiles, and there is no other version at this time.

**Comment by 20sandeepsingh** [comment]
Thanks for the information. I have also set up the mapzen vector tile
service and its working file. Can you help me with pre-caching the topojson
tiles. I want to generate topojson tiles on the disk and serve them using
NGINX.

**Comment by meetar** [comment]
Your issue at https://github.com/tilezen/vector-datasource/issues/968 is the right place for those questions. Good luck!
