### ISSUE TITLE
Missing "build-bundle" dependency

### ISSUE THREAD

**Issue by IvanSanchez** [tangrams/tangram#384]
Trying to run the `master` branch with `npm run-script build` fails with the following error message:

`npm ERR! Error: ENOENT: no such file or directory, open '/home/ivan/devel/tangram/node_modules/build-bundle/package.json'`

This can be worked around with `npm install --save-dev build-bundle`. Will try to make a pull req to amend `package.json`.

**Comment by dmvaldman** [comment]
Hmm... Do you mind providing more of the log information from the error? I don't believe any package we use requires `build-bundle`, "build-bundle" is just the name of one of our npm scripts (as in `npm run-script build-bundle`) that the build script calls.

**Comment by meetar** [comment]
Hmm, yes, fwiw I'm unable to replicate this – though I am seeing a different npm problem, which I've just filed separately: https://github.com/tangrams/tangram/issues/386

**Comment by dmvaldman** [comment]
Since #386 has been patched, can you confirm @IvanSanchez that things are working for you with a clean install and build? Let us know if you are still having installation issues. Thanks.

**Comment by bcamper** [comment]
Closing as I believe the related issues are resolved elsewhere - `build-bundle` is an npm script, not a package.
