### ISSUE TITLE
Problem with lodash dependency

### ISSUE THREAD

**Issue by meetar** [tangrams/tangram#386]
Starting from a clean clone:
- `npm install`
- `npm run build`

**RESULT:**

> Error: Cannot find module 'lodash/lang/isFunction'
    at Function.Module._resolveFilename (module.js:327:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:355:17)
    at require (internal/module.js:13:17)
    at Object.<anonymous> (/Users/peter/work/tangram/node_modules/babel-core/lib/api/node.js:21:29)
    at Module._compile (module.js:399:26)
    at Object.Module._extensions..js (module.js:406:10)
    at Module.load (module.js:345:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:355:17)
    at require (internal/module.js:13:17)

*However* – if I run `npm install` a second time, the build is successful.

**Comment by dmvaldman** [comment]
Yeah confirmed. So far in my searching for the cause all I've found is that we're not alone, and everyone's recommendation is to install twice, or remove `node_modules` and install again. I find this very disturbing. Will look more into it.

**Comment by meetar** [comment]
Yeah, removing node_modules just sets me back to square one… can we add `npm install` as a postinstall script in the package.json? :P

**Comment by dmvaldman** [comment]
This seems to be related to the culprit: https://github.com/webpack/webpack/issues/2044

**Comment by meetar** [comment]
If the babel-core files are using the old unflattened lodash paths, does that mean we should be using a newer version of Babel?

**Comment by bcamper** [comment]
We should upgrade Babel anyway, but it's actually a fairly complex upgrade.
I had a `babel6` branch mostly working a few months ago but didn't finish
the job.

On Wed, Aug 17, 2016 at 12:57 PM, Peter Richardson <notifications@github.com

**Comment by meetar** [comment]
Works for me – built successfuly on the first try.

**Comment by dmvaldman** [comment]
Great! There was a conflict resulting from babel requiring an incompatible version of `lodash`. I'm still not exactly sure why the conflict wasn't naturally avoided by the magic of npm dependency resolution. But it turns out the `babel` package wasn't needed to begin with, so we could just delete it.
