### ISSUE TITLE
Errors in polygon rendering when using vector tiles

### ISSUE THREAD

**Issue by shilad** [tangrams/tangram#388]
I have a series of topojson multipolygons whose lines I'd like render using vector tiles. I'm seeing weird rendering problems, and I've distilled the issue to a (relatively) simple test case. 

First, I believe the polygons are valid, because they open fine in various viewers and shapely also says they are valid.

When tangram renders them as a single topojson file (e.g. ` url: http://shilad.com/foo.topojson`), the results look fine: 
<img width="245" alt="screen shot 2016-08-20 at 4 00 45 pm" src="https://cloud.githubusercontent.com/assets/329888/17833854/4eae6db6-66ef-11e6-9366-0bcd4bc96309.png">

However, when I tell tangram that this is actually a vectored datasource (e.g. url: `http://shilad.com/foo.topojson?{x}{y}{z}`), lots of strange things happen: 
<img width="264" alt="screen shot 2016-08-20 at 4 00 31 pm" src="https://cloud.githubusercontent.com/assets/329888/17833855/4eae9b4c-66ef-11e6-9bfa-d0cdd8303d5c.png">

This happens to me on Mac under Chrome, Firefox, Safari.

I've posted code at http://shilad.com/tangram.html and : http://shilad.com/tangram_bug.html for the working and broken versions.

Thanks for the awesome library! I am excited to get past this so I can unleash it!

On an unrelated note: Do you have any kind of IRC, forum, etc?

**Comment by meetar** [comment]
Hi @shilad! Thanks for the excellent bug report, we'll take a look! And in the meantime, yes, we have a chat room at https://gitter.im/tangrams/tangram-chat

**Comment by bcamper** [comment]
Hi @shilad -- thanks for your report. Can you clarify if you want to serve your data from a single TopoJSON file, or if you are actually creating your own vector tiles server-side, such as with the tools in Mapzen's https://github.com/tilezen?

I ask because it seems that both of your examples are referencing the same `foo.topojson` file. If this is an *un-tiled* file, then the correct way to load it into Tangram is as your first example (http://shilad.com/tangram.html). Your second example (http://shilad.com/tangram_bug.html) appears to simply add tile x/y/z coordinates to the URL, but it looks like it's loading the same underlying data file. This will just duplicate that data many many times (once per tile on screen!), which will just cause things to run very slowly :) 

So if I understand correctly, you are already doing the right thing in your initial example, and the latter is only applicable if you want to invest additional time in creating your own vector tiles on your own server (if so, we can direct you to more info on that).

**Comment by shilad** [comment]
Hi @bcamper I am creating clipped tiles using a custom server. I distilled the bug I was observing to this issue to try to understand what was happening. 

So to be clear: This bug appears in my server-clipped tiles, but this example suggests it isn't related to my server or clipping.

Thanks for your help!

**Comment by bcamper** [comment]
OK thanks - can you post an example that uses your server-clipped tiles (or am I incorrect in my reading, and the link above already does that)?

**Comment by shilad** [comment]
Sure! I've updated the bug to use my topojson tiles now:
http://shilad.com/tangram_bug.html It's only available at zoom level 1, but
I presume that's fine.

Thanks for your help!

**Comment by meetar** [comment]
Investigating a bit more, it looks as though your tiles are clipped in an unusual way – there's a lot of overlap between them, and they don't appear to be clipped at the map tile boundaries. Here are the four tiles which make up the image at zoom 1, in an "exploded" view:

<img width="967" alt="tiles" src="https://cloud.githubusercontent.com/assets/459970/17872348/a411b4bc-688d-11e6-8c64-f3f244a430aa.png">

And here I've colored each of them to show how they overlap to make the final image:

<img width="673" alt="tiles-merged" src="https://cloud.githubusercontent.com/assets/459970/17872363/ba6a72b2-688d-11e6-8b27-59c784c09807.png">

So there's certainly some unusual tiling happening here – I'd recommend you check your clipping settings, try to clip the tiles such that they fit within tile boundaries and don't overlap, then try again!

**Comment by shilad** [comment]
Good catch! I was using a buffer on a box, and it was producing the rounded tiles you saw. I've fixed it to square off the edges properly (image below). 

Unfortunately, even with the square tiles I'm still seeing the same behavior. Any other ideas?

<img width="825" alt="screen shot 2016-08-22 at 5 30 31 pm" src="https://cloud.githubusercontent.com/assets/329888/17874000/747ec220-688e-11e6-8d43-0c9e53a91544.png">

**Comment by shilad** [comment]
Update: I think this is due to a bug related to projection. My data is for a made up flat world, so I was using CRS.Simple (see http://leafletjs.com/examples/crs-simple/crs-simple.html). I switched to Web Mercator on both the tile server and leaflet, and all seems fine! I'm happy now, but I thought I should keep this open in case this suggests some related bug.

**Comment by bcamper** [comment]
Ah, good to hear! For Tangram tiles, they are expected to be served in latitude/longitude for GeoJSON/TopoJSON (the MVT format specifies its own coordinate space), but you could transform other data into that space (perhaps that's what you've done). And for the final display to match up properly with Leaflet, yes, it will need to be set to Web Mercator (the default). We can look at clarifying this in docs too. Closing for now, please re-open or file a new issue if needed. Thanks!

**Comment by meetar** [comment]
Ah ha! It looked like it was otherwise projected correctly so I didn't consider that possibility – looks like an interesting project, send us a link to the finished map if you can!
