### ISSUE TITLE
Remove `move_into_tile` parameter

### ISSUE THREAD

**Issue by bcamper** [tangrams/tangram#402]
While testing #360 we found some illogical behavior in how the `move_into_tile` parameter (which is JS-only and thus should be discouraged anyway) is applied. Proposed changes are:

- Remove the `move_into_tile` parameter from the scene file and internally.
- The "move into tile" behavior...
  - Should **always** apply for **line labels** (e.g. just keep the code path for if this value is `true`). The label is being moved *along* the line, but is still *on* the line, so moving it is OK.
  - Should **never** apply for **point labels** (e.g. just keep the code path for if this value is `false`). The label shouldn't be moved because it will no longer be labelling the correct position in space.
    - A possible caveat here would be supporting labels for points where some position tolerance is acceptable, e.g. a polygon centroid, where you might rather have a slightly off-center label than no label at all. However, it may not be worth the additional complexity for this case.

**Comment by bcamper** [comment]
cc @dmvaldman

**Comment by dmvaldman** [comment]
Will work on this once the articulated labels branch is merged. Consider this issue extortion.

**Comment by bcamper** [comment]
See revised logic in #437
