### ISSUE TITLE
Will leaflet plugin  support  L.CRS.EPSG4326?

### ISSUE THREAD

**Issue by Mofangbao** [tangrams/tangram#405]
When initiate the map using L.CRS.EPSG4326,map was still rendered using mecator,will this plugin plan to support other projecion?

thanks!

**Comment by meetar** [comment]
For now, we require that the default Leaflet CRS.EPSG3857 be used. Additionally, EPSG4326 isn't a projection – it's just a coordinate system for defining how to interpret the input data, and does not require any particular output projection.

At this time the only way to reproject data in Tangram is to do it in a vertex shader: https://mapzen.com/blog/escape-from-mercator/

**Comment by bcamper** [comment]
@Mofangbao we are interested in adding non-Mercator projection support to Tangram, but it's a complex addition and is not on our near-term roadmap... eventually though :)
