### ISSUE TITLE
map freezes briefly on touchpad dragend 

### ISSUE THREAD

**Issue by meetar** [tangrams/tangram#406]
**TO REPRODUCE THE ISSUE, FOLLOW THESE STEPS:**

- load any Tangram map
- drag the map with the touchpad and release while dragging

**RESULT:**

The map will freeze immediately at the `dragend` event for about a half-second, then unfreeze and continue any drag-inertia animation.

**EXPECTED RESULT:**

No freeze.

**ENVIRONMENT:**

Seen in Chrome, FF, and Safari on Mac OS. Not seen when using a regular mouse.

**Comment by dmvaldman** [comment]
I've noticed this as well. It may have something to do with the opacity of loading async labels, as I notice the animation of opacity also freezes.

**Comment by meetar** [comment]
Seems to be coming from Leaflet – probably OS-related, maybe unfixable, but re-filed this issue there just in case: https://github.com/Leaflet/Leaflet/issues/4889
