### ISSUE TITLE
is it possible to "select" building on click?!

### ISSUE THREAD

**Issue by plandem** [tangrams/tangram#410]
e.g.:
https://cesiumjs.org/NewYork/index.html

is it possible?
1) change color of building on hover
2) change color of specific building
3) handle click on building?

I tried to look through documentation and demos - could not see any cases for that :(

**Comment by bcamper** [comment]
Hi @plandem, sorry for the delay. Here's an example that uses a combination of the [`interactive`](https://mapzen.com/documentation/tangram/draw/#interactive) property, along with [hover and click events](https://mapzen.com/documentation/tangram/Javascript-API/#hover-and-click) that use run-time manipulation of the [scene `config`](https://mapzen.com/documentation/tangram/Javascript-API/#config) to change a [`filter`](https://mapzen.com/documentation/tangram/layers/#filter) that highlights a single feature at a time.

1. Open this example scene:
http://tangrams.github.io/tangram-frame/?url=https://gist.githubusercontent.com/anonymous/b70f56111b13b5a44d35427e6056e70c/raw/02f68a429c53691d71a475548028800e5034bf3f/scene.yaml&lib=0.10#18.1076/40.76387/-73.97771

2. Open the browser console, and run the following JS snippet:
NOTE: the `layer` variable here is the Leaflet layer created by Tangram (`Tangram.leafletLayer()`), and the `scene` variable is the Tangram scene, also available as `layer.scene`.
```
layer.setSelectionEvents({
  click: function(selection){
    if (selection.feature) {
      scene.config.layers.buildings.selected.filter.id = selection.feature.properties.id;
      scene.rebuild();
    }
  },
  hover: function(selection){
    if (selection.feature) {
      scene.config.layers.buildings.hover.filter.id = selection.feature.properties.id;
      scene.rebuild();
    }
  }
});
```

The relevant selection and hover filters in the scene file are highlighted here:
https://mapzen.com/tangram/play/?scene=https%3A%2F%2Fgist.githubusercontent.com%2Fanonymous%2Fb70f56111b13b5a44d35427e6056e70c%2Fraw%2F02f68a429c53691d71a475548028800e5034bf3f%2Fscene.yaml&lines=69-79#17.5122/40.74955/-73.98244

Please let us know if you have further questions. Thanks!

**Comment by bcamper** [comment]
I should add that most architectural decisions in Tangram were made with a basemap in mind, so while this does work, it's not optimized -- it's doing way more work than it "should" have to just to change a single feature color. So... it works pretty well for *click* events, and is less performance (though seems comparable to Cesium) for *hover* events :)  In the future we may provide more direct support for this functionality, which could be more optimized.

**Comment by am2222** [comment]
@bcamper  Hi, Why selection.feature is always undifined? even when I click on tangram drawn layer?

**Comment by bcamper** [comment]
@am2222 did you set the `interactive` property on the features you would like to be selectable?

https://mapzen.com/documentation/tangram/draw/#interactive

Only those will register.

**Comment by am2222** [comment]
@bcamper  Hi, Wow it was exactly my problem.thanks
