### ISSUE TITLE
Add line offset option (for transit)

### ISSUE THREAD

**Issue by nvkelso** [tangrams/tangram#414]
We have transit data from both OpenStreetMap and Transit.land that knows about topology (that multiple transit lines run along a common linestring geometry). We currently show a transit overlay option on the Bubble Wrap house style, but that suffers from lack of line offsetting – there is no BART rainbow in the SF Bay Area, which is sad. 

Using that topology (which needs to be added to Mapzen's vector tiles),  it would be nice to add Tangram support for offsetting the lines.

There might be several toggles for this depending on number of lines (max of say 5 or 8) and some knowledge of transit system (if too many lines, then stop offsetting by line and instead offset by system) and transit mode. 

See also:
- Conveyal's [transitive.js](https://github.com/conveyal/transitive.js/) Leaflet project does line offsets (more as diagrams).
- [Leaflet.PolylineOffset](https://github.com/bbecquet/Leaflet.PolylineOffset)

**Comment by nvkelso** [comment]
Tilezen work in: https://github.com/tilezen/vector-datasource/issues/1058

**Comment by bcamper** [comment]
Released in [v0.14.0](https://github.com/tangrams/tangram/releases/tag/v0.14.0).
