### ISSUE TITLE
Tangram will render labels, but no line, polygon in some tiles, in some pans

### ISSUE THREAD

**Issue by nvkelso** [tangrams/tangram#415]
**TO REPRODUCE THE ISSUE, FOLLOW THESE STEPS:**

From support channel, a user reported that Refill around [zoom 15 in Bogata Columbia](https://tangrams.github.io/refill-style/#15/4.6678/-74.0386) doesn't always draw the fills and strokes (but always draws the labels). Weirdly, if you pan the map around, that same tile WILL draw all content sometimes.

- Load up: https://tangrams.github.io/refill-style/#15/4.6658/-74.0390
- Notice a big chunk of the map is empty except for labels
- Pan the map around
- Watch that empty area fill in, and remove itself (see GIF)

![tangram_roads_render_bug_bogota](https://cloud.githubusercontent.com/assets/853051/18693615/f5b1e702-7f57-11e6-876f-1a4d5a39fdcc.gif)

Example tile:
[15958.txt](https://github.com/tangrams/tangram/files/483871/15958.txt)

That same tile loads fine in QGIS:

<img width="737" alt="screen shot 2016-09-20 at 17 25 04" src="https://cloud.githubusercontent.com/assets/853051/18693614/f597b3e6-7f57-11e6-970e-4083e0a03274.png">

**RESULT:**

Most layers don't draw (except labels). 

**EXPECTED RESULT:**

Always all the stuff, all the time.

**ENVIRONMENT:**

Repor'd on Mac OS Safari and Chrome. Not sure user's original system config.

**Comment by nvkelso** [comment]
I can reproduce it on all house styles except the forthcoming [Tron](https://tangrams.github.io/tron/#15/4.6678/-74.0386).

**Comment by bcamper** [comment]
This appears to be a data error upstream in OSM:

- If you disable `buildings` layer, everything draws.
- If you set building color to red, you get:

![screen shot 2016-09-21 at 9 52 20 am](https://cloud.githubusercontent.com/assets/16733/18713723/57c6ed78-7fe1-11e6-97f8-b7ff5696d499.png)

- Looking up the OSM id: https://www.openstreetmap.org/way/439899732#map=14/42.1030/-77.9867
- And changeset: https://www.openstreetmap.org/changeset/41823638

"Revert changeset that put large building over most of South America. Also lots of duplicates in Africa"

-_-

**Comment by nvkelso** [comment]
Super weird! Thanks for the sleuthing.

**Comment by nvkelso** [comment]
(And to clarify, it's probably a building in a neighbouring tile projecting into the current view – when the neighboring tile is removed from current view, it no longer projects into the visible tile. Because buildings aren't clipped to tile boundaries in Mapzen vector tiles, they are buffered out.)
