### ISSUE TITLE
generating label centroid prevents a WOF polygon from being drawn

### ISSUE THREAD

**Issue by burritojustice** [tangrams/tangram#416]
**TO REPRODUCE THE ISSUE, FOLLOW THESE STEPS:**

- reference a WOF polygon (non-tiled geojson) as a source
- generate label centroid
- draw polygon and display a name (filtering for `label_placement=true`)

https://mapzen.com/tangram/play/?scene=https%3A%2F%2Fmapzen-uploads.s3.amazonaws.com%2Fplay%2F262792e74b86d8cb772a3f0fd83c4328%2Feast-africa%2Fscene.yaml#5.5839/-0.880/37.147

https://dev.mapzen.com/tangram/view/?scene=https://mapzen-uploads.s3.amazonaws.com/play/262792e74b86d8cb772a3f0fd83c4328/east-africa/scene.yaml#5/-0.857/37.178

**RESULT:**

- if the `generate_label_centroids: true`,  the polygon does draw at all (even if not filtering for `label_placement: true`)
- if `generate_label_centroids: true` is left out, the polygon and tiled labels draw

**EXPECTED RESULT:**

polygon and a single label should appear as it does with other non-tiled geojson sources

https://dev.mapzen.com/tangram/view/?scene=https://mapzen-uploads.s3.amazonaws.com/play/262792e74b86d8cb772a3f0fd83c4328/tanzania/scene.yaml#6/-6.806/39.232

**ENVIRONMENT:**

Tangram 0.9 and 0.10

**OTHER:**

Any additional notes, comments, tips, tricks, gifs, suggestions, poetry, recipes, jokes

**Comment by bcamper** [comment]
Fixed in https://github.com/tangrams/tangram/commit/41d16cc9d745ccfce174423f1b212316979323e9, will be in v0.10.3.

**Comment by bcamper** [comment]
Released in [v0.10.3](https://github.com/tangrams/tangram/releases/tag/v0.10.3).

**Comment by burritojustice** [comment]
thanks!
