### ISSUE TITLE
Upgrade to Leaflet 1.0.1

### ISSUE THREAD

**Issue by hallahan** [tangrams/tangram#420]
Leaflet 1.0 is finally out. Not a beta. Not a release candidate.

http://leafletjs.com/2016/09/27/leaflet-1.0-final.html

It might be good to update src, examples, and docs to this release.

That is if the roadmap is to continue building on top of Leaflet...

**Comment by bcamper** [comment]
Thanks for the reminder - done in https://github.com/tangrams/tangram/commit/6c53693a8c0af153ed7fe58ae1338b34fd1a513e
