### ISSUE TITLE
Support caching of already downloaded tiles

### ISSUE THREAD

**Issue by batje** [tangrams/tangram#422]
I noticed that all tiles are re-downloaded every time, for example when zooming out and back in again.
This could be prevented by supporting caching the tiles. 
Might add some more speed to the maps. Not sure on what level that would need to be implemented.

**Comment by meetar** [comment]
Hi @batje! There are two layers of caching in use by Tangram – the first is the browser cache, where any downloaded tiles should be cached and managed by the browser itself; the second is Tangram's internal JS object cache, which stores built tiles. The rules for that cache are here:

https://github.com/tangrams/tangram/blob/master/src/view.js#L263-L280

Currently, we discard tiles which are > 2 tiles outside of the current view (a value set with `border_tiles`), and > 1 zoom level away from the current zoom level (set with `preserve_tiles_within_zoom`). Those values could be modified, but the current combination is a level that we find works pretty well with the environments we're working in for the moment.

Feel free to experiment with these values and functions in a local build :)
