### ISSUE TITLE
Modify wheel zoom steps

### ISSUE THREAD

**Issue by carlospg79** [tangrams/tangram#423]
Hi, it's possible to change the behaviour of the wheel zoom? 

it seems very slow, and the wheelpxperzoom and wheelDebounceTime options doesn't do anything.
the wheel zoom on google maps or mapbox it's more fast, and seems more appropiate.

I tried to change that also directly on mapzen.debug.js of the main sample, but with no luck.

Thanks

**Comment by pnorman** [comment]
This matches my experience, and has given some people a negative impression of tangram with live demos.

**Comment by bcamper** [comment]
Thanks for the feedback - there does appear to be an undesirable
interaction between Tangram and Leaflet scroll wheel handling. It's changed
a bit through the various 1.0 pre-releases, but now that 1.0 is official we
can revisit and hopefully have an update soon.

**Comment by meetar** [comment]
Hi @carlospg79, can you tell us the versions of Tangram and Leaflet that you're seeing this behavior in, as well as your OS and browser versions? That will help us track down your specific issue. Thanks!

**Comment by pnorman** [comment]
I get it with Windows 8.1 Chrome 53.0.2785.143 (Official Build) m (64-bit) on https://mapzen.com/tangram/play. A single zoom wheel click moves the zoom from 12.0000 to 12.0120

**Comment by carlospg79** [comment]
I use ubuntu 16.04 with own tangram-play installation. 
The same behavior occurs with any demo (at localhost or mapzen.com), or even a clone of main tangram branch.
The web browser is Chromium.

_Chromium	52.0.2743.116 (Build para desarrolladores) Built on Ubuntu , running on Ubuntu 16.04 (64 bits)_



it solves a bit if i unlock the wheel mouse because moves freely and faster.

At work i use chrome with windows 8.1 and repeats the same behaviour.

**Comment by bcamper** [comment]
We believe this should be addressed in the newly released [v0.10.5](https://github.com/tangrams/tangram/releases/tag/v0.10.5) (CDN expiration may take another 15 mins for mapzen.com/tangram/0.10 paths to reflect this).

Please note (as mentioned in the release notes) that Tangram makes a couple modifications to default Leaflet scrollwheel behavior to try to get better synchronization with its own render loop. The new version *should* work for you, but you can always disable it with the `modifyScrollWheel` option:

```
var layer = Tangram.leafletLayer({
  scene: ...,
  modifyScrollWheel: false
});
```

Please give it a try and let us know if you continue to experience problems!

**Comment by bcamper** [comment]
Documented in https://github.com/tangrams/tangram-docs/commit/bb2f070131e45fd39783b3d268314e3e36969c1c

**Comment by carlospg79** [comment]
Thanks, i tried with online tangram/play and now works perfectly.
