### ISSUE TITLE
Using http://mapkeyicons.com/ for point style

### ISSUE THREAD

**Issue by am2222** [tangrams/tangram#430]
Hi,
Is it poeeible to use icons from http://mapkeyicons.com/ as style for points in ymal files for javascript api??

**Comment by bcamper** [comment]
Hi @am2222 -- the easiest way to do that would be to use the PNG or SVG versions of the icons. However, if you are using more than a couple, you would want to put them all into one spritesheet, and create a Tangram sprite definition that tells the renderer where each individual icon is in the larger image, details here: https://mapzen.com/documentation/tangram/textures/#sprites

It may be possible to use the font version, though I have not tried this.

**Comment by am2222** [comment]
@bcamper  thanks. I tried with font version and it did not work..I used unicode value of icon as text and also defined font in ymal file but it simple showed only unicode value

**Comment by bcamper** [comment]
Ah, we use Canvas text rendering, and it may have some issues with these kinds of custom fonts -- I'm not sure, it's just not something we've focused on supporting! I recommend using the image versions, ideally combined into a single spritesheet (e.g. as is common for CSS sprites).

**Comment by am2222** [comment]
@bcamper  thanks very much.But I thing it would be good if you add support of those kind of fonts.It is very handy feature.Anyway,thanks very much for your help
