### ISSUE TITLE
Italic text not accounted for in collision box

### ISSUE THREAD

**Issue by bcamper** [tangrams/tangram#431]
It looks like the slant from italic text is not accounted for in the collision box:

![screen shot 2016-10-19 at 10 15 26 am](https://cloud.githubusercontent.com/assets/16733/19522393/0be0af9c-95e5-11e6-89a8-b9248e196e62.png)

**Comment by bcamper** [comment]
@dmvaldman FYI I usually close these when they are released to production, so we can do a final verification - I believe this fix is merged to master but not released until 0.11

**Comment by dmvaldman** [comment]
Ah sorry. I thought the protocol was close on merge.

**Comment by bcamper** [comment]
Part of the thinking there was to only notify external people that their issue is closed when it's released and they can actually get the benefit :)

**Comment by bcamper** [comment]
Released in 0.11.0
