### ISSUE TITLE
need some tutorials about styles and shaders

### ISSUE THREAD

**Issue by am2222** [tangrams/tangram#432]
Hi,
I can easily extrude building walls using tangram. But it does not seem as a 3d, in fact it does not effect from lights and for example a cube has the same color in all sides. In real 3d it seems that each side of a cube should get a little shadow and etc, even edges should have some diffrences with each sides surface,
any way I figure out that I must use shaders to achieve what I need,isn't it?If so can some one give me some hints about doing it?for example this is what I need
http://uploads.im/6EiOd.png
and this is what I get (this is only a test)
http://uploads.im/cRTsv.png

do you suggest me to use shaders?or styles..or even it is not possible to achieve sth similar that?

**Comment by dmvaldman** [comment]
Perhaps @patriciogonzalezvivo would be best to answer. On first glance it seems that things are in 3D with shading, but the effect would be greater if you exaggerate the perspective of the scene, or change the vanishing point of the camera.

In the scene file try changing the camera's perspective `type` property to `isometric`, or increase the distance to the `vanishing_point` property.

**Comment by patriciogonzalezvivo** [comment]
Hi @am2222!

Seams that the extrusion and the shading are working properly BUT there is some weird geometry problem inside the "rooms" for example in this room call "woman wc" there is a gigantic white cube being extrude together with the walls. The final effect is a Z-fighting kind of problem.

<img width="326" alt="crtsv" src="https://cloud.githubusercontent.com/assets/346914/19565957/af8d76bc-96b6-11e6-92c9-bde168e131c8.png">

Also as @dmvaldman point out... you can change the camera to `isometric` to mimic the reference image you have

**Comment by am2222** [comment]
@patriciogonzalezvivo  thanks for your help.In fact this levels must be zero in height but when I set is zero is shows nothing,for this reason I gave the room floors 0.01 height. 

Another my problem is about shadings ..I have no idea why I have such bright scence, I added these lines into material of walls

`                material:
                    emission: 0
                    ambient: [ 0.1745f, 0.01175f, 0.01175f, 0.55f ]
                    diffuse: [ 0.61424f, 0.04136f, 0.04136f, 0.55f ]
                    specular: [ 0.727811f, 0.626959f, 0.626959f, 0.55f ]
                    shininess: 76.8f`

it looks better but I have no idea how can I have more 3d like shapes with shadows and things like that. even I dont know if shaders will help me in this case or material is enough

**Comment by am2222** [comment]
@dmvaldman  thanks for your comment. Can you give me an idea how to set vanishing point?

**Comment by patriciogonzalezvivo** [comment]
@am2222 there is a bunch of things that seems to be mixed... are you using tangramJS? 
do you have this data online so I can take a look? also can you pass the .yaml file you are using? It will be easier if I take a look to them

**Comment by am2222** [comment]
@patriciogonzalezvivo thanks.Yes it is tangramJs ,In fact it is on localhost.this is my json file
`{"water": {"type": "FeatureCollection", "features": []}, 

"buildings": {"type": "FeatureCollection", "features": [
{ "type": "Feature", "properties": { "sort_key": null, "height": 1.000000, "min_zoom": null, "id": null, "name": null, "label_plac": null, "type": "wall", "level": 1, "building": 1, "color": "#A2BBA0" }, "geometry": { "type": "Polygon", "coordinates": [ [ [ 51.359232385442766, 32.617977291268652 ], [ 51.359235255077849, 32.618025930862167 ], [ 51.359238615002326, 32.618131991997821 ], [ 51.359363436918031, 32.618112841870271 ], [ 51.359355808591644, 32.618042312296581 ], [ 51.359356385402712, 32.618039543603437 ], [ 51.359352059319676, 32.617993687123302 ], [ 51.3593499251187, 32.61796194809417 ], [ 51.359344589616292, 32.617962625847177 ], [ 51.359344676137951, 32.617962798890495 ], [ 51.359349665553715, 32.61796222207942 ], [ 51.359350069321465, 32.617965697366124 ], [ 51.359345714397882, 32.617966101133874 ], [ 51.359345498093731, 32.617963952512639 ], [ 51.359345209688193, 32.617963995773465 ], [ 51.359345512514004, 32.617966389539411 ], [ 51.359349939538973, 32.617965971351381 ], [ 51.359358141071162, 32.618074083771418 ], [ 51.359358115835924, 32.61807438299212 ], [ 51.359358115835924, 32.6180766902364 ], [ 51.359360563677654, 32.61811180721535 ], [ 51.359360769166848, 32.618111587306174 ], [ 51.359280592428028, 32.618123181208695 ], [ 51.359278425781383, 32.618123689523394 ], [ 51.35927834286484, 32.618123411933126 ], [ 51.359260890724876, 32.618126573578735 ], [ 51.35926075012717, 32.618126411350673 ], [ 51.35926075012717, 32.618126295988461 ], [ 51.359259564059414, 32.618126515897629 ], [ 51.35924200376737, 32.618128776276066 ], [ 51.35924217681071, 32.618128891638293 ], [ 51.359241106105202, 32.618112499388644 ], [ 51.359241048424096, 32.618111518809826 ], [ 51.359241023188552, 32.618111414262835 ], [ 51.359240734783022, 32.618107607309781 ], [ 51.359240561739696, 32.618106396006532 ], [ 51.35924050405859, 32.618106569049857 ], [ 51.359239869566416, 32.618095032828442 ], [ 51.359235601164492, 32.618028353468667 ], [ 51.359232385442766, 32.617977291268652 ] ] ] } },
{ "type": "Feature", "properties": { "sort_key": null, "height": 1.000000, "min_zoom": null, "id": null, "name": null, "label_plac": null, "type": "wall", "level": 1, "building": 1, "color": "#A2BBA0" }, "geometry": { "type": "Polygon", "coordinates": [ [ [ 51.35927834286484, 32.618123411933126 ], [ 51.359280592428028, 32.618123181208695 ], [ 51.359275657088254, 32.618086427528297 ], [ 51.359276035620567, 32.618086322981277 ], [ 51.359274305187355, 32.618086438343489 ], [ 51.359276695348179, 32.618108577073379 ], [ 51.359276727793826, 32.618108760931911 ], [ 51.35927834286484, 32.618123411933126 ] ] ] } },
{ "type": "Feature", "properties": { "sort_key": null, "height": 1.000000, "min_zoom": null, "id": null, "name": null, "label_plac": null, "type": "wall", "level": 1, "building": 1, "color": "#A2BBA0" }, "geometry": { "type": "Polygon", "coordinates": [ [ [ 51.359358000473712, 32.618076805598619 ], [ 51.359357910346731, 32.618076621740123 ], [ 51.359358115835924, 32.61807438299212 ], [ 51.359298935020064, 32.618080497189467 ], [ 51.359299050382283, 32.618083381244823 ], [ 51.359358000473712, 32.618076805598619 ] ] ] } },
{ "type": "Feature", "properties": { "sort_key": null, "height": 1.000000, "min_zoom": null, "id": null, "name": null, "label_plac": null, "type": "wall", "level": 1, "building": 1, "color": "#A2BBA0" }, "geometry": { "type": "Polygon", "coordinates": [ [ [ 51.359300204004427, 32.618064231117266 ], [ 51.35929907561767, 32.618047204375593 ], [ 51.359299281106715, 32.618047272871792 ], [ 51.359355487740245, 32.618042359162608 ], [ 51.359355808591644, 32.618042312296581 ], [ 51.359355372378026, 32.618040167280554 ], [ 51.359356385402712, 32.618039543603437 ], [ 51.359296281689147, 32.618045542438573 ], [ 51.359297345184459, 32.618064393345456 ], [ 51.359297435311284, 32.618064346479478 ], [ 51.359300204004427, 32.618064231117266 ] ] ] } },
{ "type": "Feature", "properties": { "sort_key": null, "height": 1.000000, "min_zoom": null, "id": null, "name": null, "label_plac": null, "type": "wall", "level": 1, "building": 1, "color": "#A2BBA0" }, "geometry": { "type": "Polygon", "coordinates": [ [ [ 51.359235601164492, 32.618028353468667 ], [ 51.359277131561583, 32.618026392311023 ], [ 51.359277131561583, 32.618023738980099 ], [ 51.359235255077849, 32.618025930862167 ], [ 51.359235601164492, 32.618028353468667 ] ] ] } },
{ "type": "Feature", "properties": { "sort_key": null, "height": 1.000000, "min_zoom": null, "id": null, "name": null, "label_plac": null, "type": "wall", "level": 1, "building": 1, "color": "#A2BBA0" }, "geometry": { "type": "Polygon", "coordinates": [ [ [ 51.359253078539936, 32.617977074964465 ], [ 51.359320911521856, 32.617968768885049 ], [ 51.359320219348575, 32.617966230916338 ], [ 51.359252847815512, 32.617974075546897 ], [ 51.359253078539936, 32.617977074964465 ] ] ] } },
{ "type": "Feature", "properties": { "sort_key": null, "height": 1.000000, "min_zoom": null, "id": null, "name": null, "label_plac": null, "type": "wall", "level": 1, "building": 1, "color": "#A2BBA0" }, "geometry": { "type": "Polygon", "coordinates": [ [ [ 51.359352059319676, 32.617993687123302 ], [ 51.35935159787082, 32.617989534083598 ], [ 51.359292301692747, 32.617995302194302 ], [ 51.359292301692747, 32.617998763060726 ], [ 51.359352059319676, 32.617993687123302 ] ] ] } },
{ "type": "Feature", "properties": { "sort_key": null, "height": 0.900000, "min_zoom": null, "id": null, "name": "woman wc", "label_plac": null, "type": "bathroom", "level": 1, "building": 1, "color": "#EADF85NULL" }, "geometry": { "type": "Polygon", "coordinates": [ [ [ 51.359241023188552, 32.618111414262835 ], [ 51.359241106105202, 32.618112499388644 ], [ 51.359241048424096, 32.618111518809826 ], [ 51.35924200376737, 32.618128776276066 ], [ 51.35924200376737, 32.618128776276066 ], [ 51.359259506378308, 32.61812634285431 ], [ 51.35926075012717, 32.618126295988461 ], [ 51.35925933333499, 32.618110192144371 ], [ 51.359259423461708, 32.618110145278479 ], [ 51.359258179712853, 32.61811036518769 ], [ 51.359252411602156, 32.618110711274333 ], [ 51.359241023188552, 32.618111414262835 ] ] ] } },
{ "type": "Feature", "properties": { "sort_key": null, "height": 0.900000, "min_zoom": null, "id": null, "name": "men wc", "label_plac": null, "type": "bathroom", "level": 1, "building": 1, "color": "#EADF85" }, "geometry": { "type": "Polygon", "coordinates": [ [ [ 51.35926075012717, 32.618126411350673 ], [ 51.359277099115921, 32.618123458798962 ], [ 51.359278400545932, 32.618123411933105 ], [ 51.359276727793826, 32.618108760931911 ], [ 51.359262448114762, 32.618110653593227 ], [ 51.35925933333499, 32.618110192144371 ], [ 51.359259423461708, 32.618110145278479 ], [ 51.35926075012717, 32.618126411350673 ] ] ] } },
{ "type": "Feature", "properties": { "sort_key": null, "height": 1.000000, "min_zoom": null, "id": null, "name": null, "label_plac": null, "type": "wall", "level": 1, "building": 1, "color": "#A2BBA0" }, "geometry": { "type": "Polygon", "coordinates": [ [ [ 51.359256678023812, 32.618104259247488 ], [ 51.359257914274046, 32.618104123259961 ], [ 51.359256712449678, 32.618092956308587 ], [ 51.359255558827542, 32.618093013989693 ], [ 51.359256678023812, 32.618104259247488 ] ] ] } },
{ "type": "Feature", "properties": { "sort_key": null, "height": 0.900000, "min_zoom": null, "id": null, "name": null, "label_plac": null, "type": "elevator", "level": 1, "building": 1, "color": "#FFA370" }, "geometry": { "type": "Polygon", "coordinates": [ [ [ 51.359240561739696, 32.618106396006532 ], [ 51.359256586272267, 32.618105844430929 ], [ 51.359255501146428, 32.618093071670799 ], [ 51.359239869566416, 32.618095032828442 ], [ 51.359240561739696, 32.618106396006532 ] ] ] } },
{ "type": "Feature", "properties": { "sort_key": null, "height": 1.000000, "min_zoom": null, "id": null, "name": null, "label_plac": null, "type": "wall", "level": 1, "building": 1, "color": "#A2BBA0" }, "geometry": { "type": "Polygon", "coordinates": [ [ [ 51.359257914274046, 32.618104123259961 ], [ 51.359256678023812, 32.618104259247488 ], [ 51.359256770130784, 32.618105184703282 ], [ 51.35924050405859, 32.618106569049857 ], [ 51.359240734783022, 32.618107607309781 ], [ 51.359256586272267, 32.618105844430929 ], [ 51.359258093191187, 32.618105707438289 ], [ 51.359258096796253, 32.618105819195463 ], [ 51.359257914274046, 32.618104123259961 ] ] ] } },
{ "type": "Feature", "properties": { "sort_key": null, "height": 0.200000, "min_zoom": null, "id": null, "name": null, "label_plac": null, "type": "stairs", "level": 1, "building": 1, "color": "#64BBB4" }, "geometry": { "type": "Polygon", "coordinates": [ [ [ 51.359245316825998, 32.618078352173335 ], [ 51.359255353338604, 32.618077083188979 ], [ 51.359251661747763, 32.618030476854578 ], [ 51.359242548132862, 32.618031284390078 ], [ 51.359245316825998, 32.618078352173335 ] ] ] } },
{ "type": "Feature", "properties": { "sort_key": null, "height": 0.500000, "min_zoom": null, "id": null, "name": null, "label_plac": null, "type": "water", "level": 1, "building": 1, "color": "#1a910d" }, "geometry": { "type": "Polygon", "coordinates": [ [ [ 51.359247393345846, 32.618008327309518 ], [ 51.359275772450459, 32.618005904703026 ], [ 51.359273349843967, 32.617987677473238 ], [ 51.359245547550422, 32.617991830512935 ], [ 51.359245547550422, 32.617991830512935 ], [ 51.359247393345846, 32.618008327309518 ] ] ] } },
{ "type": "Feature", "properties": { "sort_key": null, "height": 0.200000, "min_zoom": null, "id": null, "name": "پلاک يک", "label_plac": null, "type": "room", "level": 1, "building": 1, "color": "#65B8B3" }, "geometry": { "type": "Polygon", "coordinates": [ [ [ 51.359298383444383, 32.618080544055395 ], [ 51.359358141071162, 32.618074083771418 ], [ 51.359355487740245, 32.618042359162608 ], [ 51.35929907561767, 32.618047204375593 ], [ 51.359300806050875, 32.618064047258812 ], [ 51.359297345184459, 32.618064393345456 ], [ 51.359298383444383, 32.618080544055395 ] ] ] } },
{ "type": "Feature", "properties": { "sort_key": null, "height": 0.500000, "min_zoom": null, "id": null, "name": null, "label_plac": null, "type": "unit", "level": 1, "building": 1, "color": "#64BBB4" }, "geometry": { "type": "Polygon", "coordinates": [ [ [ 51.359293999680254, 32.618113883735198 ], [ 51.359347873834125, 32.618105000844729 ], [ 51.359347412385276, 32.618099694182888 ], [ 51.359293538231398, 32.618108000262289 ], [ 51.359293999680254, 32.618113883735198 ] ] ] } },
{ "type": "Feature", "properties": { "sort_key": null, "height": 0.200000, "min_zoom": null, "id": null, "name": "پلاک دو", "label_plac": null, "type": "room", "level": 1, "building": 1, "color": "#65B8B3" }, "geometry": { "type": "Polygon", "coordinates": [ [ [ 51.359280733025663, 32.61812288198788 ], [ 51.359360563677654, 32.61811180721535 ], [ 51.359357910346731, 32.618076621740123 ], [ 51.359275657088254, 32.618086427528297 ], [ 51.359280733025663, 32.61812288198788 ] ] ] } },
{ "type": "Feature", "properties": { "sort_key": null, "height": 0.200000, "min_zoom": null, "id": null, "name": "پلاک سه", "label_plac": null, "type": "room", "level": 1, "building": 1, "color": "#65B8B3" }, "geometry": { "type": "Polygon", "coordinates": [ [ [ 51.359296422286739, 32.61804489713132 ], [ 51.359296306924534, 32.618045358580176 ], [ 51.359355372378026, 32.618040167280554 ], [ 51.359352257598253, 32.617993907032798 ], [ 51.35929215388483, 32.617999444419056 ], [ 51.359296422286739, 32.61804489713132 ] ] ] } },
{ "type": "Feature", "properties": { "sort_key": null, "height": 1.000000, "min_zoom": null, "id": null, "name": null, "label_plac": null, "type": "wall", "level": 1, "building": 1, "color": "#B3BB71" }, "geometry": { "type": "Polygon", "coordinates": [ [ [ 51.359241048424096, 32.618111518809826 ], [ 51.359241106105202, 32.618112499388644 ], [ 51.359252584645482, 32.618111749534258 ], [ 51.359252411602156, 32.618110711274333 ], [ 51.359241048424096, 32.618111518809826 ] ] ] } },
{ "type": "Feature", "properties": { "sort_key": null, "height": 1.000000, "min_zoom": null, "id": null, "name": null, "label_plac": null, "type": "wall", "level": 1, "building": 1, "color": "#B3BB71" }, "geometry": { "type": "Polygon", "coordinates": [ [ [ 51.359259506378308, 32.61812634285431 ], [ 51.359259564059414, 32.618126515897629 ], [ 51.359260890724876, 32.618126573578735 ], [ 51.35925933333499, 32.618110192144371 ], [ 51.359258179712853, 32.61811036518769 ], [ 51.359259506378308, 32.61812634285431 ] ] ] } },
{ "type": "Feature", "properties": { "sort_key": null, "height": 1.000000, "min_zoom": null, "id": null, "name": null, "label_plac": null, "type": "wall", "level": 1, "building": 1, "color": "#B3BB71" }, "geometry": { "type": "Polygon", "coordinates": [ [ [ 51.359277099115921, 32.618123458798962 ], [ 51.359278425781383, 32.618123689523394 ], [ 51.359276695348179, 32.618108577073379 ], [ 51.359262217390338, 32.618109211565553 ], [ 51.359262448114762, 32.618110653593227 ], [ 51.35927571476936, 32.618110249825477 ], [ 51.359277099115921, 32.618123458798962 ] ] ] } },
{ "type": "Feature", "properties": { "sort_key": null, "height": 0.01, "min_zoom": null, "id": null, "name": null, "label_plac": null, "type": "building_outline", "level": 1, "building": 1, "color": "#F6FFD7" }, "geometry": { "type": "Polygon", "coordinates": [ [ [ 51.35923706842771, 32.618134245165955 ], [ 51.359364889760663, 32.618113941416318 ], [ 51.35934995035398, 32.617961720975124 ], [ 51.359231357998127, 32.617977756322844 ], [ 51.359231357998127, 32.617977756322844 ], [ 51.35923706842771, 32.618134245165955 ] ] ] } }
]},
		"landuse_labels": {"type": "FeatureCollection", "features": []}, 
		"places": {"type": "FeatureCollection", "features": []},
		"transit": {"type": "FeatureCollection", "features": []},
		"pois": {"type": "FeatureCollection", "features": []}, 
		"boundaries": {"type": "FeatureCollection", "features": []}, 
		"roads": {"type": "FeatureCollection", "features": []}
		,"points": {"type": "FeatureCollection", "features": [{"geometry":{"type":"Point","coordinates":[51.35929875869,32.61801730129]},"type":"Feature","properties":{"kind":"station","name":"Franklin Avenue","subway_routes":["A","C"],"kind_tile_rank":2,"min_zoom":10.000000,"is_subway":true,"id":3564375804}}]}
		
		
		
		}`

and this is my ymal file

`import:
    - styles/water.yaml

cameras:
    perspective:
        type: perspective
        focal_length: 5       
        vanishing_point: [100, 100] 
        active: false

    isometric:
        type: isometric
        axis: [-1, 1]
        active: true

    flat:
        type: flat
        active: false

lights:
    light1:
        type: directional
        direction: [0, 1, -.5]
        diffuse: .3
        ambient: 1
fonts:
    Mapkeyicon:
        url: http://127.0.0.1:8000/tn/MapkeyIcons/MapkeyIcons.woff
sources:
   
textures:
    icons:
        url: images/pois.png
        filtering: mipmap
        sprites:
            # define sprites: [x origin, y origin, width, height]
            plane: [0, 0, 32, 32]
            tree: [0, 185, 32, 32]
            sunburst: [0, 629, 32, 32]
            restaurant: [0, 777, 32, 32]
            cafe: [0, 814, 32, 32]
            museum: [0, 518, 32, 32]
            bar: [0, 887, 32, 32]
            train: [0, 74, 32, 32]
            bus: [0, 148, 32, 32]
            hospital: [0, 444, 32, 32]
            parking: [0, 1073, 32, 32]
            info: [0, 1110, 32, 32]
            hotel: [0, 259, 32, 32]
            bookstore: [0, 333, 32, 32]
            shield: [0, 1142, 32, 32]   
            
            
styles:
    icons:
        base: points
        texture: icons
layers:

    _buildingLayer:
        data:
            source: dynamic_data
            layer: buildings 
        filter:
          #  not: { type: building_outline }

        draw:
            _countryStyle: # We're giving this draw group a name '_countryStyle'
                style: polygons
                color: function () { return feature.color; } 
                order: 0 
                extrude: function () { return feature.height>=0 || $zoom >= 16; }
                material:
                    emission: 0
                    ambient: [ 0.1745f, 0.01175f, 0.01175f, 0.55f ]
                    diffuse: [ 0.61424f, 0.04136f, 0.04136f, 0.55f ]
                    specular: [ 0.727811f, 0.626959f, 0.626959f, 0.55f ]
                    shininess: 76.8f
            _bordersStyle: # A new style name for our borders
                style: lines
                color: white
                width: 0.02m # REQUIRED
                order: 1 #
    _water:
        data:
            source: dynamic_data
            layer: buildings 
        filter: { type: water }

        draw:
            style: water              
    _textLayer: # A new layer name. We'll use this layer to style country labels
        data:
            source: dynamic_data
            layer: buildings
        draw:
            _labelStyle:
                style: text # The style has to be 'text' in order to render a label
                text_source: name # ~~~ TODO ~~~ Uncomment each 'text_source' one at a time to experiment with different labels
                # text_source: capital
                # text_source: continentName
                font:
                    family: Mapkeyicon # Family can be any typeface available to the operating system. Meaning, you can import font families in your CSS and Tangram will be able to use them.
                    size: 16px
                    fill: palegreen # The label color can be set with a 'fill' parameter. Change the color!
                    stroke: # You can set a stroke (outline) color and width for the font
                        color: black
                        width: 1px
    _pointlayer:
        data:
            source: dynamic_data
            layer: points
        parks:
            draw:
                icons: 
                    order: 491
                    sprite: tree
                    priority: 1
                    size: 16px
                    text:
                        text_source: name
                        font:
                            family: Lucida Grande
                            size: 10pt
                            style: italic
                            fill: darkgreen
                            stroke: { color: white, width: 3 }  `

It seems that I should work with materials,right?

**Comment by patriciogonzalezvivo** [comment]
can you drop the files instead of copy pasting the content... I'm losing a lot of the precious indentation : )

**Comment by am2222** [comment]
@patriciogonzalezvivo  thanks.I have packed files and uploaded. My json file overlaps in some futures, I have created it for test only

**Comment by meetar** [comment]
Hi @am2222, we have lots of information about styles and shaders in our documentation: https://mapzen.com/documentation/tangram/

3D extruded objects are rendered with the Phong-Blinn shading model, and should show light and shade if the data is structured correctly. You shouldn't need to adjust your materials to simply adjust brightness – try adjusting your layer's `color` attribute first, and perhaps remove your `lights` to use the default directional light – that way you should be able to tell whether your geometry is extruding as expected. More information on our lighting model can be found here: https://mapzen.com/documentation/tangram/Lights-Overview/

And information about adjusting the vanishing point of a perspective camera or the `axis` of an isometric camera can be found on our documentation's Cameras Overview: https://mapzen.com/documentation/tangram/Cameras-Overview/

Unfortunately the scene in the .rar you included seems to be incomplete, so I'll close this for now – feel free to open another issue later, or find us in our gitter chat rom at gitter.im/tangrams/tangram-chat. We'll be adding more tutorials soon, thanks for your interest!
