### ISSUE TITLE
Map drawn in another tab is invisible until navigation

### ISSUE THREAD

**Issue by meetar** [tangrams/tangram#444]
**TO REPRODUCE THE ISSUE, FOLLOW THESE STEPS:**

- Open this link in a new tab (on Chrome on a mac, command-click it):

http://tangrams.github.io/tangram-frame/?url=https://raw.githubusercontent.com/tangrams/bubble-wrap/gh-pages/bubble-wrap.yaml&lib=0.10#10/40.7145/-74.0073

- Wait long enough for the tab to load and finish drawing the map
- Switch to that tab

**RESULT:**

The map is empty, though the UI is visible. Any mouse input causes the map to draw immediately.

**EXPECTED RESULT:**

The map will be visible as soon as you switch to the tab.

**ENVIRONMENT:**

Chrome/Mac OS

**NOTES:**

FF/Mac and Safari/Mac do not exhibit this behavior.

**Comment by bcamper** [comment]
Should be resolved by https://github.com/tangrams/tangram/commit/a797d034ce8212e2e62f077d306df655139b7852 and https://github.com/tangrams/tangram/commit/c08e1916a51d1b977514c2126b72d0d62202da57

**Comment by bcamper** [comment]
Released in v0.11.1.
