### ISSUE TITLE
The Chinese label shows very vague. 

### ISSUE THREAD

**Issue by ligai322** [tangrams/tangram#453]
**EXPECTED RESULT:**

The text displayed in the green box is clear. 
But the text displayed in the red box is vague.
The two types of text displayed on the same layer, using the same style.
![image](https://cloud.githubusercontent.com/assets/3262486/20469570/dad098a2-afdb-11e6-9329-62cdd5e97525.png)

**ENVIRONMENT:**
OS : window 8.1
browser version : firefox 49.0.2   or google chrome 53.0.2785.116 m

**OTHER:**
 [this demo](http://tangrams.github.io/bubble-wrap/#4.375/40.463/78.215) has the same problem. 
![image](https://cloud.githubusercontent.com/assets/3262486/20469702/dd63fb4e-afdc-11e6-93da-f4cd1a1b0f60.png)

**Comment by nvkelso** [comment]
Can you clarify if the text content is incorrect (something upstream in OpenStreetMap), or Tangram renderingor basemap style related?

Looking at the different colored boxes it's not obvious to me.

**Comment by ligai322** [comment]
@nvkelso    [this demo](https://mapzen.com/tangram/play/?scene=https%3A%2F%2Fapi.github.com%2Fgists%2F2b273a3ca5531c706c6cf69cb09a007d#10.2917/30.2751/114.7863)
like this 
![image](https://cloud.githubusercontent.com/assets/3262486/20472882/ddde7a3e-aff7-11e6-8cac-738b7b9100e0.png)

**Comment by ligai322** [comment]
There is another problem. When the label with stroke, The effect of the display is shadow, not what I want halo. so how do I need to achieve halo effect
![image](https://cloud.githubusercontent.com/assets/3262486/20473148/9c6d2dd2-aff9-11e6-972d-7dedf9b510e6.png)

**Comment by nvkelso** [comment]
I still don’t know what to debug, can you help me?

> The text displayed in the green box is clear.
> But the text displayed in the red box is vague.

What is “clear” and “vague”? Is it the text content or how it is rendered?

**Comment by meetar** [comment]
@nvkelso Some but not all of the labels are blurry – in this image, for
instance:

https://cloud.githubusercontent.com/assets/3262486/20469702/dd63fb4e-afdc-11e6-93da-f4cd1a1b0f60.png

The top boxed label is blurry, the bottom one is not.

This looks like something to do with texture definitions, @bcamper will
have more definite ideas.

**Comment by bcamper** [comment]
I think this may be an issue generally with rendering complex scripts with Canvas at small font sizes. We can do some tests to see if adjusting texture coordinates could possibly help (or maybe rendering at higher resolution and downsampling, though that could actually make things blurrier), or if this is an issue with the underlying text render engine.

**Comment by dmvaldman** [comment]
This could also be due to aliasing. We may be placing the label at a fractional pixel, or sampling at the texture at a fractional pixel.

**Comment by bcamper** [comment]
Yeah, I suspect the former more likely than the latter (texture UVs *should* be calculated on pixel boundaries), but either is possible.

**Comment by pnorman** [comment]
I was observing this with Thai in http://tangrams.github.io/bubble-wrap/#10.06944/14.8128/106.8603


![image](https://cloud.githubusercontent.com/assets/1190866/20508583/708d93e6-b017-11e6-94d7-584977a93352.png)
Scaled 8x
![image](https://cloud.githubusercontent.com/assets/1190866/20508617/a2649d1a-b017-11e6-8446-6a390511334b.png)

![image](https://cloud.githubusercontent.com/assets/1190866/20508624/b69f9794-b017-11e6-8e1d-4a5cc7b479c9.png)
Scaled 8x
![image](https://cloud.githubusercontent.com/assets/1190866/20508650/c8df17fe-b017-11e6-92a4-cfa6f88d3b13.png)

This looks exactly like aliasing by not being aligned with pixel boundaries.

**Comment by bcamper** [comment]
Good news: I got this to go away with some simple grid-snapping in the vertex shader: https://github.com/tangrams/tangram/compare/snap-to-pixel

Bad news: it introduces a kind of shimmer/wobble when panning (particularly noticeable as pan inertia comes to a stop, didn't bother me when actively panning or zooming). 

I'll post some pics tomorrow. There may be a way to simplify or eliminate the shimmer. But it may be a better trade-off anyway for increased legibility.

**Comment by bcamper** [comment]
Here's a comparison of snapped vs. un-snapped. You can see the text getting clearer with snapping. Now working on how to eliminate the jitter caused when the map is actively moving. I believe that both the `snap-to-pixel` branch *and* the changes in #454 may be needed to fully solve this issue.

![snap-to-pixel](https://cloud.githubusercontent.com/assets/16733/20545159/9ec52a84-b0db-11e6-958a-bcf3763c470f.gif)

**Comment by pnorman** [comment]
> eliminate the jitter caused when the map is actively moving

What do you mean by jitter?

**Comment by bcamper** [comment]
@pnorman when the map is moving slowly, for instance at the end of the panning inertia curve, the sprite may be snapping to slightly different pixels from frame to frame, causing a noticeable wobble/jitter effect (hard to explain without seeing in action). But looking at Google Maps, it appears they do a sort of "fade to snap" action at the end of panning; it's very subtle but works well to hide the issue, we're working on something similar with promising results so far.

**Comment by pnorman** [comment]
> @pnorman when the map is moving slowly, for instance at the end of the panning inertia curve, the sprite may be snapping to slightly different pixels from frame to frame, causing a noticeable wobble/jitter effect (hard to explain without seeing in action).

Some of this is inherent with the conversion of a continuous quantity (desired position) to a discrete quantity (pixels). Is it jittering between two positions, or just unsmooth motion?

> But looking at Google Maps, it appears they do a sort of "fade to snap" action at the end of panning; it's very subtle but works well to hide the issue, we're working on something similar with promising results so far.

This is what I had independently thought of, but looks like you're ahead of me.

**Comment by bcamper** [comment]
This has been released in v0.11.1, and should be much better now!

**Comment by bcamper** [comment]
Further improvements in #467.
