### ISSUE TITLE
tangram makes multiple API requests for same non-tiled data, geojson draws & disappears on 429s

### ISSUE THREAD

**Issue by burritojustice** [tangrams/tangram#462]
**TO REPRODUCE THE ISSUE, FOLLOW THESE STEPS:**

- List the steps you used
- To produce the result here
- Don't leave any out

In Tangram, make a call to the isochrone API.

Add a second layer with a different data source to our scene file (the first layer being the isochrone layer).

https://bl.ocks.org/rfriberg/38694be3e8ffb30ac6ac8302960c7ebd

**RESULT:**

Tangram displays the GeoJSON from the isochrone API as expected. 

When the second layer is present, the isochrone service is called two to four times, often resulting in 429s. The isochrones are drawn, but in Chrome they often quickly disappear after a 429 is received

**EXPECTED RESULT:**

Draw and keep on screen the GeoJSON from the API request, even if the additional requests result in 429s with no data returned.

**ENVIRONMENT:**

List the OS and browser version combinations which exhibit the behavior here.

Mac OS X 10.11.5, Chrome 54.0.2840.98. Safari seems more forgiving and doesn't remove the isochrone as often.

**OTHER:**

Any additional notes, comments, tips, tricks, gifs, suggestions, poetry, recipes, jokes

There are no cache headers on the isochrone API response.

https://www.goodeggs.com/sfbay/seasonal-recipes/content/V1DBGygAAKNHw3Hy/chickpea--ricotta-shakshuka

**Comment by bcamper** [comment]
Requesting the non-tiled data source multiple times is resolved here (will be in v0.11.1): 7a4c47921c419f9ee7dc8b16c0b21b84dcc99341

The 429 is a separate issue. It's an HTTP error, so I would expect the data source to be cleared in that case -- the old data is no longer available. I don't know exactly why each browser may handle it a bit differently.

**Comment by bcamper** [comment]
Two requests is expected - one per worker. Four should not happen - can you provide more info/examples on how to see that?

**Comment by burritojustice** [comment]
thanks! we were seeing up to four in the example listed above (though no longer, now that it is running 0.11.1)
