### ISSUE TITLE
Filters with arrays do not accept keys with a colon

### ISSUE THREAD

**Issue by batje** [tangrams/tangram#466]
**TO REPRODUCE THE ISSUE, FOLLOW THESE STEPS:**
I created a gist to show the issue with several (non-working) examples commented out and a working example of the desired result using a workaround here:

**RESULT:**

Describe the result here.

**EXPECTED RESULT:**

Describe what you expected to see here.

**ENVIRONMENT:**

List the OS and browser version combinations which exhibit the behavior. The idea is to filter out boundaries with key name, name:left and name:right and certain value. You should be able to use and array, eg [key:value, key2:value] for that or the any: keyword.
Both do not work for the 'name:' based keys, but do work if you use keys that do not contain a colon.

https://mapzen.com/tangram/play/?scene=https%3A%2F%2Fapi.github.com%2Fgists%2F6993db04475690c1658504c24d07475b#10.5000/52.6425/4.8133

**OTHER:**

The Beemster from the example is one of the oldest polders in The Netherlands. (though that does not rhyme, so it is not poetry.).

**Comment by bcamper** [comment]
Interesting! Thank you for the detailed examples, we'll take a look.

**Comment by nvkelso** [comment]
Good bug!

To work around this, you could filter using a JS function (e.g.: `filter:
function() { … }` ).

**Comment by bcamper** [comment]
Fixed in 818e08c1039480cb9d79e5b94dbfa44585fa6c1a, for pending v0.11.3 release.

**Comment by bcamper** [comment]
Released in v0.11.3, thanks again!
