### ISSUE TITLE
buffer doesn't work for text symbolizer

### ISSUE THREAD

**Issue by sensescape** [tangrams/tangram#468]
We're redoing label hierarchy for places, but running into zoom levels where labels are too dense like here in Paris, would like to use buffer, but only available for point symbolizer right now. Would like to use for text as well. 

http://localhost:8007/#11/48.8489/2.3315

<img width="1524" alt="screen shot 2016-12-12 at 11 36 51 am" src="https://cloud.githubusercontent.com/assets/466585/21113693/6d8b140e-c05f-11e6-8752-33eaa0eac592.png">

**Comment by bcamper** [comment]
OK, so `buffer` *should* work for `text`, so it's a bug we should fix if not.

For clarity though, we would also like to migrate these labels to all use `points`, with a variant where the sprite/size is null, and just the text portion is rendered. Is that correct?

**Comment by sensescape** [comment]
yes that's correct. I'll try buffer with text again, but it wasn't working, only for points.

**Comment by bcamper** [comment]
Oh yeah I just wanted to confirm that it *should* work, I trust you that it doesn't :)  May just be a bug. I'll investigate.

**Comment by sensescape** [comment]
Well, now text buffer works!?

**Comment by sensescape** [comment]
![tangram-11-48 85139-2 35863-2073](https://cloud.githubusercontent.com/assets/466585/21120864/50145f24-c07e-11e6-90db-72135a8752fd.png)

**Comment by bcamper** [comment]
I did a series of tests and I believe this does work as desired. If you have problems again, feel free to reopen or open a new issue).
