### ISSUE TITLE
WebGL: Invalid Operation errors on second map 

### ISSUE THREAD

**Issue by rgillan** [tangrams/tangram#470]
Hi,
Sorry we've been a few dot releases behind in our testing and just catching up.  In our application we have two maps, one on a dashboard page (occupying only part of the window) that's created on startup.  There's a second, full window map that's created when the user selects that tab.  We create it on tab selection so Leaflet correctly obtains the window dimensions and builds the map properly.  This has been working fine up to and including 0.11.0.

We tried installing 0.11.4 today and it has some problems (and turns out all the way back to 0.11.1).  When we try and substantiate the second map now we get a flood of WebGL INVALID_OPERATION errors mainly complaining about 'the object does not belong to this context'.  Do you have any idea how we can create the second map now as we really want to keep Tangram updated.

Thanks

**Comment by bcamper** [comment]
Ah, thanks. It's likely a result of optimizations to reuse GL shader and program objects. These are bound to specific canvas contexts. I thought these were being reset, but this may be a case where not. 

To clarify, Tangram (unfortunately) currently doesn't properly support displaying multiple maps at the same time on the same page. It is however valid to switch between maps on the same page (remove/replace one with another). Is that what you are doing here?

**Comment by rgillan** [comment]
Brett,

Our app has a number of tabs with hidden content as a single page application.  The first tab is a dashboard, which has the initial map created at startup.  When the user clicks on the map tab, the dashboard div is hidden and the map div is shown.  This is where the second map is created in the dom.  The two can never be shown at the same time but both end up existing in the dom.  Hope that helps and thanks for being so responsive as always.

Cheers
Rob

**Comment by bcamper** [comment]
Hey @rgillan, could you give this build a try and let me know if it resolves the issue?

https://precog.mapzen.com/tangrams/tangram/context-id/dist/tangram.debug.js

**Comment by rgillan** [comment]
Brett,
Fantastic, solved the problem.
Cheers
Rob

**Comment by bcamper** [comment]
Great, will include it in the next release (in the next day or two).

**Comment by bcamper** [comment]
Fix in https://github.com/tangrams/tangram/commit/00d0f15c34ecd16b0a7b06450dcfa6115c5859ab

**Comment by bcamper** [comment]
Fix was released in v0.11.5.
