### ISSUE TITLE
Consider not snapping non-sprite and/or small points to pixel grid

### ISSUE THREAD

**Issue by bcamper** [tangrams/tangram#481]
When looking at the test data from #478, I noticed some unusual visual behavior when rendering dense point data (in that case output by Tippencanoe), especially when the dots have a relatively small radius.

When new tile data loads or stops panning, the dots appear to crawl or "bleed" a bit. Upon further investigation, this looks like the result of the pixel snapping behavior we apply to improve the legibility of sprites and text labels. If the points are as small as `1px`, they can actually disappear and reappear depending on if they are too small to see when un-snapped to the pixel grid.

This behavior is currently blanket-applied to all `points`-based styles. We should consider not applying it in some cases, potentially:

- Non-sprite points (they aren't sampling from a texture so aligning with the pixel grid isn't necessarily relevant)
- Points with a small size (snapping to pixel grid may be more distracting than helpful)

**Comment by meetar** [comment]
+1

**Comment by nvkelso** [comment]
Also text smaller than a certain size, 11 or 10pt?

**Comment by meetar** [comment]
While it's true that the smaller the text, the more any snapping will cause it to crawl, prooprtionally, I think it would be even more important to snap small text than large text, as it's sampling from a texture (as in the exceptions noted above) – and the smaller the text, the more any grid mismatch will blur the rendered text, proportionally.

**Comment by nvkelso** [comment]
Another use case:

Road shield sprites and their text attachments aren't consistently snapped.

**Comment by bcamper** [comment]
Shields + text correlation is a separate issue, need to think on it more but not explicitly related to the issue described here.

I agree with @meetar, based on the most recent posted results on #475, I believe the differences cited there are 80% a styling issue, 20% a rendering issue (at least vis a vis Tangram vs. Mapnik results). While I certainly agree that text (small fonts and angled) can be improved, I don't think it's through not snapping them to the grid.

**Comment by bcamper** [comment]
Included in commit https://github.com/tangrams/tangram/commit/1f2552d787879a91ffde11639aa93261ff5315d0 in PR #508

**Comment by bcamper** [comment]
Released in [v0.12.0](https://github.com/tangrams/tangram/releases/tag/v0.12.0)
