### ISSUE TITLE
Drawing branched roads with varying draw orders

### ISSUE THREAD

**Issue by hasan9206** [tangrams/tangram#483]
I've had a lot of success getting Tangram to display my vector maps for a while now, really appreciate all the work you guys have done, loving all the updates as well, keep it up guys!

Recently I've looked into improving the roads display, and I realized that my roads were displayed such that I was not able to differentiate which roads passed above or below another (flyovers, underpasses etc): 
![screenshot from 2017-01-18 11-33-53](https://cloud.githubusercontent.com/assets/7081695/22053867/0a7ba0a8-dd75-11e6-9076-f7b38482d558.png)

I then changed the draw order for the flyovers and underpasses using an attribute that I made and was able to get it fixed:
![screenshot from 2017-01-18 11-34-07](https://cloud.githubusercontent.com/assets/7081695/22053906/376663a0-dd75-11e6-92ff-c8d1eab9d9d2.png)

This however resulted in another issue, when the roads branch (The Blue circle in the south-east corner) the outlines of the roads make the roads appear separate instead of branched. 

I want to start drawing the ramp of the flyover from the edge of the highway (or blend the outlines) so that I can get a proper branching effect and not cause any ambiguity, something like google maps:
![screenshot from 2017-01-18 11-34-30](https://cloud.githubusercontent.com/assets/7081695/22054093/e24bf92e-dd75-11e6-800f-66b633bfa7b4.png)

**Comment by bcamper** [comment]
Hi @hasan9206 -- I think what you want to do is to set a different `order` value for your road `outline`. We do this in several cases in Mapzen's own styles, where we want to group outlines from several different road classes together to create a continuous outline as you suggested. For example:

https://github.com/tangrams/bubble-wrap/blob/gh-pages/bubble-wrap.yaml#L1685-L1693

Feel free to re-open if this does not resolve your problem.

**Comment by hasan9206** [comment]
Thanks for the quick reply, really appreciate it! I tried grouping together the outlines but I wasn't able to quite figure out how to get it exactly as I want it. Grouping together the outlines results in the merging of the flyover outlines as well:
![screenshot from 2017-01-20 10-28-35](https://cloud.githubusercontent.com/assets/7081695/22137259/c3542afa-defb-11e6-88e0-fb0725a605cc.png)

**Comment by nvkelso** [comment]
Update link:
https://github.com/tangrams/bubble-wrap/blob/gh-pages/bubble-wrap-style.yaml#L1685-L1693

**Comment by bcamper** [comment]
I think you may need to only apply the outline grouping to the road segments that are links/ramps (or another combination of outline orders based on how your features are organized).

**Comment by hasan9206** [comment]
I looked into the source code of the bubble-wrap style a bit more and was able to fix my draw orders and outlines, (I will need to update my road data to be able to get the correct draw orders and outlines). I know what I need to do now, Thanks!
![screenshot from 2017-01-24 12-37-53](https://cloud.githubusercontent.com/assets/7081695/22242844/af67fc1c-e246-11e6-904c-3d0752576dc2.png)

**Comment by nvkelso** [comment]
Looking good!
