### ISSUE TITLE
"Uncaught TypeError: Cannot read property 'hasPendingRequests' of null" error in scene.js (0.11.7)

### ISSUE THREAD

**Issue by thisisaaronland** [tangrams/tangram#485]
![Uploading Screen Shot 2017-01-19 at 08.17.47.png…]()

**TO REPRODUCE THE ISSUE, FOLLOW THESE STEPS:**

https://whosonfirst.mapzen.com/iamhere/ with tangram.js 0.11.7 – currently the site is pegged at 0.11.6 but you can run a local copy here: https://github.com/whosonfirst/whosonfirst-www-iamhere

**RESULT:**

Tiles load but then `scene.js` emits a "TypeError: Cannot read property 'hasPendingRequests' of null"" at line 427 and prevents all subsequent JS from being invoked

**EXPECTED RESULT:**

For the map not to prevent the rest of the JS from working :-)

**ENVIRONMENT:**

OS X 10.11.6 in FF 50.1.0, Safari 10.0.2 and Chrome 55.0.2883.95

**Comment by bcamper** [comment]
@thisisaaronland can you try this build to see if it resolves your issue?

https://precog.mapzen.com/tangrams/tangram/selection-null/dist/tangram.debug.js

**Comment by thisisaaronland** [comment]
Can has map again, yes!

**Comment by bcamper** [comment]
Resolved by 2a6019b23ad0b76690578b4d24605be47e211b12, queued for release.

**Comment by thisisaaronland** [comment]
so 0.11.8 or a different version ?

**Comment by bcamper** [comment]
It's not released yet, just noting the fix. I'll update and close the
ticket when it's included in a release.

**Comment by bcamper** [comment]
Will be either 0.11.8 or 0.12.0

**Comment by pnorman** [comment]
The screenshot in this issue isn't displaying for me.

**Comment by bcamper** [comment]
This is released in v0.11.8 now.
