### ISSUE TITLE
SVG Display issue on IOS

### ISSUE THREAD

**Issue by johnclittle** [tangrams/tangram#486]
**TO REPRODUCE THE ISSUE, FOLLOW THESE STEPS:**

I am serving SVG files from a node server. We are linking these svg files in the scene file by creating textures then applying the texture to a style and then applying the style to a layer. Example below:

"textures": {
"f3f58b56-e562-46c4-96d1-bda0531a20f5": {
"url": "http://localhost:3000/markers/8dd593/circle-11.svg",
"filtering": "linear"
}, ...

"styles": {
"f3f58b56-e562-46c4-96d1-bda0531a20f5": {
"base": "points",
"texture": "f3f58b56-e562-46c4-96d1-bda0531a20f5"
},...

"layers": {
"f3f58b56-e562-46c4-96d1-bda0531a20f5": {
"data": {
"source": "location_source",
"layer": "locations"
},
"visible": true,
"draw": {
"points": {
"style": "f3f58b56-e562-46c4-96d1-bda0531a20f5",
"interactive": true,
"collide": false
}
}
},...

The svg file accessed at the url is as follows:

`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 15 15" height="15" width="15"><title>circle-11.svg</title><rect fill="none" x="0" y="0" width="15" height="15"></rect><path fill="#000" transform="translate(2 2)" d="M10,5.5C10,7.9853,7.9853,10,5.5,10S1,7.9853,1,5.5S3.0147,1,5.5,1S10,3.0147,10,5.5z"></path></svg>`

We are using the svg icon set available here. https://www.mapbox.com/maki-icons/

**RESULT:**

The svg shows as expected as the map point symbol within our tangram map on the latest Chrome web browser (Version 55.0.2883.95 (64-bit)) on desktop devices. Unfortunately, when accessing the map on an IOS device iPhone or IPad using IOS safari (latest) the point style only shows as a black square. 

**EXPECTED RESULT:**

Since the point symbol is being properly rendered on the desktop map we believe that our configuration is correct. We would expect that the display on IOS Safari would be the same.

**ENVIRONMENT:**

We are using tangram js v0.11.7.

**OTHER:**

I wanted to say that this is a great library and we really appreciate your making it available to the community. 

If there is any guidance you can provide to help us understand how to resolve this issue or if there are any thoughts about how tangram is consuming the. svg and displaying it that would allow us to continue our research on a solution it would be greatly appreciated.

**Comment by bcamper** [comment]
Hi, thanks for the details. Tangram simply treats SVGs as any other image file, which is to say the URL is set on an internal Image object/element, which is then fed to WebGL as a texture. So the responsibility for any SVG parsing is the browser's. That said, I've occasionally seen oddities in this image -> texture loading process across browsers.

I made a quick test that *does* appear to work for me both on desktop Chrome and iOS mobile  Safari. Can you give it a try and let me know if it works for you too (you should see red star icons):
http://bit.ly/2jSPBp5

This may help to narrow whether it is an environment or resource-related issue.

**Comment by johnclittle** [comment]
Thank you for the example. It is producing the desired result and we can see the svg symbol on IOS. This helps us understand that it is most likely an issue within our environment.

**Comment by johnclittle** [comment]
The issue is in the SVG. The fill property on "none" reverts the svg to black which is its [initial value](https://www.w3.org/TR/SVG/painting.html#FillProperty).

`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 15 15" height="15" width="15"><title>circle-11.svg</title><rect fill="none" x="0" y="0" width="15" height="15"></rect><path fill="#000" transform="translate(2 2)" d="M10,5.5C10,7.9853,7.9853,10,5.5,10S1,7.9853,1,5.5S3.0147,1,5.5,1S10,3.0147,10,5.5z"></path></svg>`

When the fill property is set to transparent it works as expected. 

`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 15 15" height="15" width="15"><title>circle-11.svg</title><rect fill="transparent" x="0" y="0" width="15" height="15"></rect><path fill="#000" transform="translate(2 2)" d="M10,5.5C10,7.9853,7.9853,10,5.5,10S1,7.9853,1,5.5S3.0147,1,5.5,1S10,3.0147,10,5.5z"></path></svg>`

Curious as the the svg fill property of "none" is per the [specifications](https://www.w3.org/TR/SVG/painting.html#SpecifyingPaint)  and when using the same svg outside of the map it renders correctly on the IOS devices (below). 

```
<span class="map-marker" data-marker-name="circle-11">
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 15 15" height="15" width="15"><title>circle-11.svg</title><rect fill="none" x="0" y="0" width="15" height="15"></rect><path fill="#000" transform="translate(2 2)" d="M10,5.5C10,7.9853,7.9853,10,5.5,10S1,7.9853,1,5.5S3.0147,1,5.5,1S10,3.0147,10,5.5z"></path></svg>
</span>
```

**Comment by bcamper** [comment]
Interesting, although I haven't yet been able to reproduce this issue in Tangram. Here's an example I made using the original SVG (with `fill="none"`) you provided above. It's working for me on both desktop and iOS. Can you give it a try?

https://mapzen.com/tangram/view/?scene=https%3A%2F%2Fmapzen.com%2Fapi%2Fscenes%2F4%2F140%2Fresources%2Fscene.yaml#12.9175/40.6750/-73.9953

Side note, the SVG here is actually inlined in the Tangram scene file using a data URL:

`texture: data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 15 15" height="15" width="15"><title>circle-11.svg</title><rect fill="none" x="0" y="0" width="15" height="15"></rect><path fill="#000" transform="translate(2 2)" d="M10,5.5C10,7.9853,7.9853,10,5.5,10S1,7.9853,1,5.5S3.0147,1,5.5,1S10,3.0147,10,5.5z"></path></svg>`

If you're curious, [the whole scene is here](https://mapzen.com/tangram/play/?scene=https%3A%2F%2Fmapzen.com%2Fapi%2Fscenes%2F4%2F140%2Fresources%2Fscene.yaml&lines=5#12.9175/40.6750/-73.9953).

**Comment by johnclittle** [comment]
I like this approach and did not realize it is available. I will test it out and let you know what we find.

**Comment by bcamper** [comment]
Yeah it's not obvious at first, but as long as it's a valid URL that an `<img>` tag will render, it should work :)

**Comment by johnclittle** [comment]
All is good with this approach. Thanks for the assistance!

**Comment by bcamper** [comment]
Great! Still not clear what caused your original issue, let us know if it happens again.
