### ISSUE TITLE
incorrect point widths

### ISSUE THREAD

**Issue by meetar** [tangrams/tangram#492]
**TO REPRODUCE THE ISSUE, FOLLOW THESE STEPS:**

Make a point of `size: 100px` :

https://mapzen.com/tangram/play/?scene=https%3A%2F%2Fmapzen.com%2Fapi%2Fscenes%2F5%2F187%2Fresources%2Fscene.yaml#1.2/33.5/-135.9

**RESULT:**

Resulting points are about 176 pixels wide on a retina screen.

Seen on Mac FF/Safari/Chrome.

**Comment by bcamper** [comment]
Oh haven't looked yet but this may be an issue with running out of precision in the vertex attribute packing for the width.

**Comment by hanbyul-here** [comment]
I found this incorrect point width problem while building [this] (https://hanbyul-here.github.io/seoul-metro-turnstile-data/map/#lat=37.5601&lng=126.9794&z=14) the point on the map should match to the legend's circle radius (They are using same function to get its size), but it is not matching. 

Also, (this can be documentation issue) the size for the point means radius or diameter ?

**Comment by bcamper** [comment]
Fixed by #472

**Comment by bcamper** [comment]
Released in [v0.12.0](https://github.com/tangrams/tangram/releases/tag/v0.12.0)
