### ISSUE TITLE
Cannot display points - could use help diagnoising

### ISSUE THREAD

**Issue by jerryhall** [tangrams/tangram#493]
I'm using this basic scene to display points of businesses in the LA area. I created a snippet of the geojson file and put the scene in Tangram Play here: https://mapzen.com/tangram/view/?scene=https://mapzen.com/api/scenes/28758/190/resources/blank.yaml#10.1208/34.0139/-118.1524

But, the fact that I can't get the points to display in Play leads me to believe it's the GeoJson formatting. The error messages seem to refer to null values and over time the number will increase significantly to thousands (I have about 23k records for one county). Here's a screen of the errors I'm seeing: https://drive.google.com/file/d/0B-sBXvhIZi_gbS1lU1EwVHJhcms/view?usp=sharing 

I believe once I get this diagnosed it wont be a problem getting into my map but, here's my code nonetheless that might help identify where I'm going wrong. One question is I haven't been able to determine which scripts I should be using between Tangram, Leaflet and Mapzen - one thought that they might be out of order (which I've played with). 

I commented out a filter in the Play which effectively parses out records where the 'class' col includes different strings. My goal was to put selectors in a filter selection feature on the map itself. If that is the correct way to reference a filter that would be great to know. 

If I could get help with this I'd love to document what I'm doing since I believe others could use. 

Thanks!

Here's the html for the map:

  <!DOCTYPE html>
  <html lang="en">
    <head>
      <title>Alcohol Outlet Map</title>
      <meta charset="utf-8">

      <link rel="stylesheet" href="https://unpkg.com/leaflet@1.0.3/dist/leaflet.css" />
      <link rel="stylesheet" href="https://mapzen.com/js/mapzen.css">

      <script src="https://mapzen.com/js/mapzen.js"></script>

      <script src="https://mapzen.com/tangram/tangram.min.js"></script>
      <script src="https://mapzen.com/tangram/tangram.debug.js"></script>

    <style>
        #map {
          height: 100%;
          width: 100%;
          position: absolute;
        }
      html,body{margin: 0; padding: 0}
    </style>
    </head>
    <body>
      <div id="map"></div>
      <script>

      var map = L.Mapzen.map('map', {
        center: [34.089, -118.297],
        zoom: 10,
        debug: true,
        scene: '/maps/scenes/ca_la_scene.yaml',
        apiKey: 'mapzen-yj3B7sr'
        // apiKey: 'mapzen-yj3B7sr'

            // minZoom: 4,
            // maxZoom: 20,
            // latLongBounds: [[ 34.13408,-118.27820],[33.679053,-118.243207]],
            // scene: L.Mapzen.BasemapStyles.Zinc
            // debugTangram: true
      });
      var layer = Tangram.leafletLayer({
        attribution: '<a href="https://mapzen.com/tangram" target="_blank">Tangram.</a> | &copy; OSM contributors | <a href="https://mapzen.com/" target="_blank">Mapzen</a>'
      })
        layer.addTo(map);
        //add search box top right
      // var geocoder = L.Mapzen.geocoder('mapzen-yj3B7sr');
      //   geocoder.setPosition('topright');
      //   geocoder.addTo(map);

      </script>
    </body>
  </html>

**Comment by nvkelso** [comment]
I’m getting a cross origin request error:

```
Mixed Content: The page at '
https://mapzen.com/tangram/play/?scene=https://mapzen.com/api/scenes/28758/190/resources/blank.yaml#10.1208/34.0153/-118.1529'
was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint '
http://poursafe.net/data/geojson/ca_la_lic_test.geojson'. This request has
been blocked; the content must be served over HTTPS.
```

Can you enable CORS on that file?

**Comment by meetar** [comment]
Hi @jerryhall – we recently released an update to the library to address what I believe may be the same issue, reported here: https://github.com/tangrams/tangram/issues/485

Although I see one other problem with your code right away: you should only include one or the other of "tangram.debug.js" or "tangram.min.js" – so only one of those `<script>` tags is needed.

And when using one of those links, you should be using the latest release by default, so the fix that went in yesterday should apply to your case non – are you still seeing this error as of today?

**Comment by bcamper** [comment]
More generally, while you will need [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS) enabled, the URL itself is `http` -- is it possible for you to serve it under `https`? Both SSL and CORS headers will be necessary for loading any external data source from a mapzen.com-hosted page.

**Comment by meetar** [comment]
…I'm currently unable to load the link http://poursafe.net/data/geojson/ca_la_lic_test.geojson at all – the page times out, saying "This site can't be reached – poursafe.net took too long to respond."

**Comment by meetar** [comment]
@jerryhall Regarding the filtering – you were very close! I've made a sample scene here showing setting up multiple filters on a single data source:

https://mapzen.com/tangram/play/?scene=https%3A%2F%2Fmapzen.com%2Fapi%2Fscenes%2F5%2F192%2Fresources%2Fblank.yaml#10.1208/34.0137/-118.1542

**Comment by jerryhall** [comment]
Hey guys, I have the site locked down because AWS shut me down due to an attack I experienced. 

It appears I am still getting the same error. Here's everything in the secure site: 

I moved everything to a secure site at https://poursafe.com/test/ca_la_map.html
The data is here:   https://poursafe.com/test/ca_la_lic_test.geojson
The scene: https://poursafe.com/test/scene.yaml
The updated Play is here: https://mapzen.com/tangram/view/?scene=https://mapzen.com/api/scenes/28758/193/resources/blank.yaml#10.1208/33.9751/-118.1619

**Comment by jerryhall** [comment]
Meetar, I'm stoked to see the points on the map. I've got a few days of stubborn invested in that. Now I'm trying to figure out what you did. Was it just the scene styling that was the issue?

**Comment by meetar** [comment]
@jerryhall I think in your case if your data was good, what you had might actually have worked. What I'm doing in that example is slightly different because of the way our datasource is organized – our datasource includes multiple GeoJSON FeatureCollections which we treat as "layers". In your case I think you should continue to use standard layer filtering: https://mapzen.com/documentation/tangram/Filters-Overview/#layer-filters

Whereas I'm using the "layer name shortcut":
https://mapzen.com/documentation/tangram/Filters-Overview/#layer-name-shortcut

…in this case, the practical difference is a single level of indentation. If you only have a single FeatureCollection then you shouldn't need to specify a layer, and should be able to make separate filters as you were doing.

However I think the larger issue here is that your GeoJSON doesn't seem to be valid. The GeoJSON spec requires that all features have a top-level "geometry" object. Yours have one of these, but it's not top-level – it's inside a top-level "properties" object. I discovered this by running it through a "linter" like this one: https://jsonformatter.curiousconcept.com/ which just checks that the format is valid.

This showed that it was valid JSON, and also showed the structure of the data, but then I ran it through another one specifically for GeoJSON: http://geojsonlint.com/ … and it said the features were missing "geometry" objects. 

You can read a bit more about how the GeoJSON format expects FeatureCollections to be laid out here: http://www.macwright.org/2015/03/23/geojson-second-bite.html#featurecollection

How is your GeoJSON being generated?

**Comment by jerryhall** [comment]
I see what you're saying about the geom. I had thought it had to be in the properties eg Type, Properties (including all the cols selected including the geom) and not the correct way of having a separate level for Type, Properties, Geometry. That had been confusing. I tried to mimic a sample I found on the trees demo: 

{"type":"FeatureCollection","features":[{"type":"Feature","properties":{"qSpecies":"Ficus microcarpa nitida 'Green Gem' :: Indian Laurel Fig Tree 'Green Gem'"},"geometry":{"type":"Point","coordinates":[-122.4493156724,37.7908147066947]}}

and I ended up with this:

{"type":"FeatureCollection","features":[ {"type":"Feature","properties":{"status":"ACTIVE","county":"LOS ANGELES","license":"571511",**"dupe":"    ","geometry":{**"type":"Point","coordinates":[-118.3093618,34.18166664]},"prem_city":"BURBANK","master":"Y","prem_zip":"91502-1207","prem_st_1":"142 N SAN FERNANDO BLVD","type":"41","id":108763,"lic_app":"LIC"}}

You can see where after dupe there is "    ","geometry 
When it should be "},"geometry
and so on... So, I think that's it and I'll get that done.

I will have questions on the layers because I do have several area layers (city, council district, zips etc), the data you see here (licenses) and then I'm adding crime. My ultimate goal is to give users the ability to select a main geographic layer eg. zip code, then get counts of all the licenses and crime in that one district. So, I'll pay more attention to the layering and indentations in the scene.yaml file.

Thanks again!

**Comment by jerryhall** [comment]
Ok I was able to fix the geoJSON creation where Geometry, Type and Properties are all on the same level. The problem is I'm getting a lot of empty properties data, even though the geom shows, when I know for certain every record has a 'license' for instance. Does Tangram require a NOT NULL value for all Properties? One of the cols looks like it has four spaces in every record if it's null. That might be another item tripping things up but, that's a wild shot in the dark. 

I'm getting a battery of tile errors now that look like this: 
log @ log.js:37 Tangram v0.11.8 [error]: Error building tile license/12/701/1636/12: TypeError: Cannot read property 'type' of null
    at convertFeature (https://mapzen.com/tangram/tangram.debug.js:4893:20)
    at convert (https://mapzen.com/tangram/tangram.debug.js:4879:13)
    at new GeoJSONVT (https://mapzen.com/tangram/tangram.debug.js:5034:20)
    at geojsonvt (https://mapzen.com/tangram/tangram.debug.js:5023:12)
    at https://mapzen.com/tangram/tangram.debug.js:33595:83

buildTileError @ tile_manager.js:309
(anonymous) @ worker_broker.js:220
WorkerBrokerMainThreadHandler @ worker_broker.js:206

The query I'm using to build the GeoJson file is: 

      SELECT row_to_json(fc)
      FROM (
       SELECT 'FeatureCollection' AS type, array_to_json(array_agg(f)) AS features
       FROM (
         SELECT
           'Feature' AS type,
           ST_AsGeoJSON(t.geom,4)::json AS geometry,
           row_to_json((SELECT p FROM (
             SELECT
             t.id,
             t.type,
             t.license,
             t.lic_app,
             t.status,
             t.dupe,
             t.master,
             t.dba,
             t.prem_st_1,
             t.prem_city,
             t.prem_st,
             t.prem_zip,
             t.county,
             t.census_2010,
             t.abc_main_id,
             t.class,
             t.abc_rpt_date
             WHERE county = 'LOS ANGELES'
             ) AS p)) AS properties
         FROM poursafe.ca_licenses AS t
         ORDER BY 1
         LIMIT 100
       ) AS f
      ) AS fc;

I haven't been able to get ogr2ogr working but, that seems like an ideal solution and another animal. 

Thanks for any insight you can give. I really appreciate it.

**Comment by bcamper** [comment]
Can you try running your output through http://geojsonlint.com? The error
suggests another issue with the GeoJSON structure (which is well specified
at http://geojson.org but can be finicky).

**Comment by jerryhall** [comment]
Hey bcamper - I finally got it right insofar as the GeoJson file creation, first time I've launched it with no errors other than a deprecation warning. I'm still working on getting the points to appear. They light right up just fine in the GeoJsonLint.com so it must be how I'm calling the data and filter. The anticipation! :)

**Comment by jerryhall** [comment]
Thanks for the help everyone. Got my first map up with test data. Will post how I did this either on GitHub or my blog. If anyone needs similar help hit me up. Thanks!
