### ISSUE TITLE
blob data source load error with geojson

### ISSUE THREAD

**Issue by aimaps** [tangrams/tangram#494]
We are using tangram to render information about roadcare and roadcontrol. It is live data, so every three minutes we get geoJson from API and set it with setDataSource method. After some time (hour or so) of running app, the geojson blob starts to be unreachable and we got this error in console: 

`Failed to load resource: the server responded with a status of 404 (Not Found)
tangram.min.js:17 Tangram v0.11.8 [warn]: data source load error(s) for source 'roadCare', URL 'blob:http://roadcontrol.ai-maps.com/92201b49-2dc1-448b-8923-fbeef19d6b0c': Error: Request error with a status of Not Found
    at XMLHttpRequest.l.onload (https://mapzen.com/tangram/0.11.6/tangram.min.js:18:3148)`

To simulate the error to show sooner, I have made a simple leaflet map with one tangram layer and geojson markers from local file which change their position every two seconds. Here the error shows within ten minutes.

http://tangram.ai-maps.com/

It happend in all browsers.

Thanks very much.

**Comment by bcamper** [comment]
Thanks for the report. I have a theory that there is some kind of blob URL
resource exhaustion here and that calling `revokeObjectURL` once the data
is loaded may fix the issue. We'll take a look and get back to you.

**Comment by bcamper** [comment]
Hi - could you try running your test against this build to see if the issue is resolved?

https://precog.mapzen.com/tangrams/tangram/revoke-blob-sources/dist/tangram.min.js

Thanks!

**Comment by aimaps** [comment]
i've added your build to http://tangram.ai-maps.com/ but now there is another error from the start. `Could not create data source: Network data source must provide a `url` property Object {type: "GeoJSON", url: null}`

**Comment by bcamper** [comment]
Whoops, looks like I was relying on an order of operations that is not always valid. I've tried another approach, which is in an updated file at the same location as above -- could you please give that a try and see if it's any better?

**Comment by aimaps** [comment]
okay so, now we have got this blob error only once at start of the app and then it doesnt appear again. The app was running for an hour without data dissapearing. But if I zoom after some time of app running , tiles dissapear for a second with these errors for every tile on viewport:

`Tangram v0.11.8 [error]: Error building tile markers/16/64712/40229/16: [240]</<.addFeature@https://precog.mapzen.com/tangrams/tangram/revoke-blob-sources/dist/tangram.min.js:15:1159
[251]</k</<.value@https://precog.mapzen.com/tangrams/tangram/revoke-blob-sources/dist/tangram.min.js:17:12593
[229]</<.buildTile/</<@https://precog.mapzen.com/tangrams/tangram/revoke-blob-sources/dist/tangram.min.js:13:9557
[73]</R/</s@https://precog.mapzen.com/tangrams/tangram/revoke-blob-sources/dist/tangram.min.js:2:20703
[73]</R/<@https://precog.mapzen.com/tangrams/tangram/revoke-blob-sources/dist/tangram.min.js:2:20825
[45]</t.exports/l@https://precog.mapzen.com/tangrams/tangram/revoke-blob-sources/dist/tangram.min.js:2:11219`

With next setDataSource, there is no error and we get data back to map.

**Comment by bcamper** [comment]
Thanks - just to confirm, are you testing on http://tangram.ai-maps.com/? Because I am not seeing any errors (on start-up or after zooming, but I may not be waiting long enough for the latter). Which could just be due to different clients, just want to make sure I'm testing the same code as you. The error you're seeing on startup is the same as the one posted in the initial issue comment?

**Comment by bcamper** [comment]
Also, could you set the build to ('debug' instead of 'min'):

https://precog.mapzen.com/tangrams/tangram/revoke-blob-sources/dist/tangram.debug.js

This will allow me to set breakpoints for testing - should have asked for that the first time :)

**Comment by aimaps** [comment]
hi, i think the last time I tryed it could been some kind of cache because now there is no error like you said. I will keep monitoring it on different browsers whole day and let you know if some error pops up.

**Comment by aimaps** [comment]
after 2 hours running and then random zoom and pan on map throws again this error:

`Tangram v0.11.8 [error]: tile load error for markers/15/32367/20111/15: TypeError: Cannot read property 'push' of undefined
    at Object.addFeature (https://precog.mapzen.com/tangrams/tangram/revoke-blob-sources/dist/tangram.debug.js:35643:30)
    at Function.buildGeometry (https://precog.mapzen.com/tangrams/tangram/revoke-blob-sources/dist/tangram.debug.js:40094:35)
    at https://precog.mapzen.com/tangrams/tangram/revoke-blob-sources/dist/tangram.debug.js:32602:40`

**Comment by bcamper** [comment]
Thanks - I'm now seeing the initial error you reported yesterday, but intermittently. I think it has something to do with a race condition between your initial `setDataSource()` call and the ones you have running on the timer. But it's a good test case :)

I have also seen the zoom in/out error, so if you could leave this page up for awhile, we'll keep investigating.

**Comment by bcamper** [comment]
Behavior has been improved for most use cases. If issue persists, please re-open.
