### ISSUE TITLE
Not able to load >20k points but, can load <5k 

### ISSUE THREAD

**Issue by jerryhall** [tangrams/tangram#496]
This may be related to https://github.com/tangrams/tangram/issues/494 but, if not here's what's happening. 

I can load about 5k geojson rows which I determined after attempting my full file of ~23k and then ~10k with no luck.  Here's my scene in Play https://mapzen.com/tangram/view/?scene=https://mapzen.com/api/scenes/28758/216/resources/9845C.yaml#14.2875/37.7569/-122.4377

 I have multiple datasets up in there and commented the bigger ones out. The error message I'm getting is below. Another oddity is that I'm seeing over 14mb data loading when in fact the file is only 9.5k in size. I tried this in Chrome and FF with similar results. 

Tangram v0.11.8 [warn]: data source load error(s) for source 'licenses', URL 'https://poursafe.com/_data/_geojson/ca_la_current.geojson': SyntaxError: Unexpected token I in JSON at position 7970241
    at JSON.parse (<anonymous>)
    at GeoJSONSource.parseSourceData (https://mapzen.com/tangram/tangram.debug.js:33680:40)
    at https://mapzen.com/tangram/tangram.debug.js:33375:28

A question here too  - is there a way to load the absolute minimum eg. the business id#, class and lon/lat first so the points appear quickly, then load the fuller set in the background while the user is looking around? It would be ideal to load the whole dataset once but, if I can knock that initial size down all the better eh? I'm creating this mini file and will have up to test as well. If I was able to load in the background, how would I call that in the scene (assuming I'm not loading it in the scene but, background-loading it as an HTML function.

Thanks!

**Comment by jerryhall** [comment]
Apologies for this one. Turns out the state data source was using quotes in various fields to describe international addresses.  I didn't understand the "Unexpected token I in JSON at position 7970241".

**Comment by meetar** [comment]
No worries! Those parser errors aren't always the most obvious :)

Regarding your question about datasources – if I understand your question correctly, we don't have a way to selectively download a subset of a single JSON datasource. However, if you split your file in two, a smaller, "primary" data file could hypothetically be used to draw the initial map, and the "extra" data could be loaded asynchronously, and then summoned into something like a popup during browsing with Tangram's "[feature selection](https://mapzen.com/documentation/tangram/Javascript-API/#getfeatureatpixel)" capability.

Alternately, if you wanted features in the second datasource to be drawn but didn't want to wait for both datasources to load before drawing the map, you could always wait for the initial map to draw by subscribing to Tangram's [load event](https://mapzen.com/documentation/tangram/Javascript-API/#load) and then add a datasource via the [setDataSource()](https://mapzen.com/documentation/tangram/Javascript-API/#setdatasource_string_-name-_object_-config) function in our API.

Let me know if you have any more questions!
