### ISSUE TITLE
Unable to parse polygon on multiple maps

### ISSUE THREAD

**Issue by jerryhall** [tangrams/tangram#497]
After a couple days trying, and believe me I hate asking to not wear out my welcome but, I'm unable to get a GeoJSON file of neighborhoods to load. I've tried two other GeoJSON files with the same results. 

I tried cloning a couple examples and have tried 101 variations of style configurations to no avail. I would really love to help tell this story of how to do this but, am incredibly stumped.

Map 1 is at https://poursafe.com/maps/ux_map.html - clone of ux_layers demo
Map 2 is at https://poursafe.com/maps/ca_la_map.html - using tangramLayers 
Map 3 is at  https://poursafe.com/maps/map_3.html - w/o tangramLayers  

My scene is at the bottom of this page. 

This round of geoJSON is here: https://poursafe.com/_data/_geojson/_areas/ca_la_la_areas_neighborhoods-v5.geojson 

I have several other polygon layers to add (eg census tracts, zips, council districts) so the user can select one area-layer and any of the license layers shown in the selectors for the first two maps. On top of that and my biggest reason to move over to Tangram is I'm adding crime which is about 250k rows for each year for the city of LA alone. The 3D visualizations will be very useful to show area and crime in context to other data..

A second question is, is there any way for me to select which layers should display on the ux_layers map #1? I see that my scene layers are automatically adding but, I'd like to parse out many of the layers. And if so, is there a way for me to edit the labels? 

Finally, I don't want to bog down GitHub Issues to get this kind of help because this is likely my problems, not any bugs so I held off as long as possible. 

Thanks for any guidance.
---------------------------------

import:
    #- https://mapzen.com/carto/cinnabar-style/cinnabar-style.yaml
    - https://mapzen.com/carto/refill-style/4/refill-style.yaml
    # - https://tangrams.github.io/blocks/filter/grid.yaml
    # - https://tangrams.github.io/blocks/lines/dash.yaml
    # - https://tangrams.github.io/blocks/points/cross.yaml
    # - https://tangrams.github.io/blocks/polygons/dots.yaml

sources:
    mapzen:
        type: TopoJSON
        url: https://tile.mapzen.com/mapzen/vector/v1/all/{z}/{x}/{y}.topojson

    _licenses:
        type: GeoJSON
        #url: https://poursafe.com/_data/_geojson/ca_la_current.geojson
        url: https://poursafe.com/_data/_geojson/ca_la_map_mini.geojson
        #url: https://poursafe.com/_data/_geojson/ca_la_current_test.geojson

    _neighborhoods:
        type: GeoJSON
        url: https://poursafe.com/_data/_geojson/_areas/ca_la_la_areas_neighborhoods-v5.geojson

layers:
    _licenses_layer:
        data: { source: _licenses }
        _onsale_c:
            filter:
                class: onsale_c
            draw:
                points:
                    # order: global.sdk_order_over_everything_but_text_0
                    color: green
                    size: 10px
        _onsale:
            filter:
                class: onsale
            draw:
                points:
                    # order: global.sdk_order_over_everything_but_text_3
                    color: green
                    size: 10px
        _offsale_c:
            filter:
                class: offsale_c
            draw:
                points:
                    # order: global.sdk_order_over_everything_but_text_1
                    color: red
                    size: 10px
        _offsale:
            filter:
                class: offsale
            draw:
                points:
                    # order: global.sdk_order_over_everything_but_text_4
                    color: red
                    size: 10px
        _nonretail_c:
            filter:
                class: nonretail_c
            draw:
                points:
                    # order: global.sdk_order_over_everything_but_text_2
                    color: yellow
                    size: 10px
        _nonretail:
            filter:
                class: nonretail
            draw:
                points:
                    # order: global.sdk_order_over_everything_but_text_5
                    color: yellow
                    size: 10px

    # LA City Neighborhoods & Communities
    _neighborhoods:
        data: { source: _neighborhoods }
        draw:
            polygons:
                color: '#BCE3B4'
                order: global.sdk_order_under_everything_0

            lines:
                width: [[8, 0.5px], [18, 5px]]
                color: '#518946'
                order: global.sdk_order_under_everything_1

**Comment by ruatara** [comment]
That url is not valid JSON, it ends mid-geometry. 
    Tangram v0.11.8 [warn]: data source load error(s) for source '_neighborhoods', URL 'https://poursafe.com/_data/_geojson/_areas/ca_la_la_areas_neighborhoods-v5.geojson': SyntaxError: Unexpected end of JSON input

**Comment by jerryhall** [comment]
ruatara, thanks... that never helps. I updated the json. Thanks!

**Comment by bcamper** [comment]
@jerryhall is this still an issue, or did the JSON syntax error resolve it?

**Comment by jerryhall** [comment]
Hi Brett,  it's still an issue.  I tried with another geoJson as well with
same results.  The partial Json was my bad as I was setting up the example
to post here but not the overarching issue.
