### ISSUE TITLE
Does tangram supports objects such as trees etc?

### ISSUE THREAD

**Issue by am2222** [tangrams/tangram#501]
Hi,
It is for a while that I am busy with finding a way to illustrate trees or other objects using tangram, I have seen some examples of webgl libraries such as threejs that they have created such objects, But I have no idea whether or not tangram supports these kind of shapes?Can some one gives me some hints?thanks

-

**Comment by meetar** [comment]
Hi @am2222 – we don't support external 3D objects at this time but hope to in the future!
