### ISSUE TITLE
connecting MVT tile service from pgRESTAPI

### ISSUE THREAD

**Issue by aimaps** [tangrams/tangram#502]
If you go to [tangram playground](http://mapzen.com/tangram/play/?#4.862/2.417/32.552) and paste in this yaml config [scene.txt](https://github.com/tangrams/tangram/files/795838/scene.txt)
, there are two types of MVT vector tile services of KenyaAdmin borders made from pgrestAPI, static(made from .mbtiles) and dynamic (looking to a live postgis table). Both are made from same geometry data. You can try to switch these two types of MVT for kenya_admin1 layer.

Static type is drawing content fine. I am having problem with dynamic type of service which is not drawing content although when you look in network there are certainly som pbf files returned with data inside.

Could it be a problem with style definition for the dynamic type service?

Thanks very much.

These are the original services in pgRESTAPI admin:
Dynamic: [http://spatialserver.spatialdev.com/services/tables/kenya_admin1/geom/vector-tiles](http://spatialserver.spatialdev.com/services/tables/kenya_admin1/geom/vector-tiles)
Static: [http://spatialserver.spatialdev.com/services/vector-tiles/dataset?name=kenya_admin1](http://spatialserver.spatialdev.com/services/vector-tiles/dataset?name=kenya_admin1)

**Comment by bcamper** [comment]
It looks like the layer names don't match between your static and dynamic data sources. The dynamic one has layer name `kenya_admin1_geom`, try this in your `layers`:

```
    kenya_admin1_geom:
        data: { source: pgrestapidynamic }
```
