### ISSUE TITLE
schemeless source urls no longer work

### ISSUE THREAD

**Issue by meetar** [tangrams/tangram#507]
This source url:

`url: //vector.mapzen.com/osm/all/{z}/{x}/{y}.topojson?api_key=vector-tiles-P6dkVl4`

Works in v0.10:
https://tangrams.github.io/tangram-frame/?debug&lib=0.10&url=https://raw.githubusercontent.com/tangrams/multiverse/gh-pages/styles/airports.yaml#13/37.6189/-122.3764

But not in v0.11:
https://tangrams.github.io/tangram-frame/?debug&lib=0.11&url=https://raw.githubusercontent.com/tangrams/multiverse/gh-pages/styles/airports.yaml#13/37.6189/-122.3764

```
Tangram v0.11.8 [warn]: tile load error(s) for osm/13/1311/3170/13: Error: Failed to execute 'open' on 'XMLHttpRequest': Invalid URL
    at https://mapzen.com/tangram/0.11/tangram.debug.js:41926:21
    at Object.Utils.io (https://mapzen.com/tangram/0.11/tangram.debug.js:41925:23)
    at https://mapzen.com/tangram/0.11/tangram.debug.js:33368:47
    at TopoJSONTileSource._load (https://mapzen.com/tangram/0.11/tangram.debug.js:33358:20)
    at TopoJSONTileSource.load (https://mapzen.com/tangram/0.11/tangram.debug.js:33158:25)
    at loadTileSourceData (https://mapzen.com/tangram/0.11/tangram.debug.js:32633:50)
    at https://mapzen.com/tangram/0.11/tangram.debug.js:32589:26
```

**Comment by nvkelso** [comment]
(This always caused problems in Tangram ES so I’ve switched to using https:
before all my source urls for Mapzen basemap styles.)

**Comment by bcamper** [comment]
Yes, talked with @meetar more and I don't think we should even try to support schemeless URLs anymore (we never documented it as such, we just had some in our examples). If your data source supports both `http` and `https`, you can just always use `https`. If your data source doesn't support `https`, and someone loads a map under `http`, it won't work anyway. So it probably just gives more of a sense of false security than any real usefulness.

**Comment by pnorman** [comment]
> your data source doesn't support https, and someone loads a map under http, it won't work anyway

Should the http at the end say https?

**Comment by bcamper** [comment]
sorry yes :)
