### ISSUE TITLE
Layer control panel and point stroke

### ISSUE THREAD

**Issue by jerryhall** [tangrams/tangram#512]
I'm looking to add a layer control panel like this example: http://tangrams.github.io/tangram/#40.7053026089413,-74.00976419448854,16. Is there a way to add that and use my own custom layers/style.yaml alongside the Mapzen/OSM data selectors?

Also, I haven't been able to find a way to add a stroke to my points. Is there any way to do this or am I supposed to use sprites? I would definitely encourage including strokes because in high volume point situations they just become a blob. 

Lastly, is there a guide similar to [this](https://www.geofabrik.de/data/geofabrik-osm-gis-standard-0.6.pdf ) that details POIs used in the various scenes (Refill, Walkabout, Cinnabar)? If not is this something that you have heard other requests for and which I can help document? 

Thanks! Am beyond excited to get these maps published!

**Comment by bcamper** [comment]
Point outlines will be available in the upcoming v0.12.0 release! See PRs in #472 and #508. Expect it within the next week or so.

The layer control in that demo is a mix of JS that tweaks the scene config values at run-time, you can see how it's implemented (as an example) here:
https://github.com/tangrams/tangram/blob/master/demos/main.js#L409-L424

Another similar example is:
http://tangrams.github.io/explorer/#16.6/40.7035/-74.0124/kind/major_road
https://github.com/tangrams/explorer/blob/gh-pages/main.js#L58-L75

For POIs, I think you are looking for:
- Mapzen vector tile data: https://mapzen.com/documentation/vector-tiles/layers/#points-of-interest
- Mapzen icons mapped to that data: https://mapzen.com/documentation/cartography/icons/
