### ISSUE TITLE
Icons over everything setting

### ISSUE THREAD

**Issue by jerryhall** [tangrams/tangram#513]
I've read different posts but, can't find a clear method to place all of my icons over all road names. Most all of my points are on business streets and many are covered until I reach a zoom level of 13.5. 

Is there any way to globally set my custom icons over street labels?

Thanks!

**Comment by bcamper** [comment]
@jerryhall can you explain a bit more what it is you're trying to achieve and what isn't working? A screenshot would help.

If you are finding that roads are crowding out or preempting your icons (?), perhaps you need to set a [`priority`](https://mapzen.com/documentation/tangram/draw/#priority) value on your icons so they take precedence (e.g. `priority: 1` should give first precedence in the collision culling pass to your icons).

**Comment by jerryhall** [comment]
Thanks for the help bcamper. Here's a screenshot of when I had the priority: 1 in the icons: level but, it also doesn't stick when putting it on the upper draw: level. 

![labels](https://cloud.githubusercontent.com/assets/3231824/23871041/08c1ce68-07e6-11e7-93c8-9f3f76c985b4.png)

I don't yet understand the prioritization coming from the walkabout-style-more-labels.yaml file so wasn't able to target (deprioritize) those labels from there - if that's even recommended.

Thanks again.

**Comment by bcamper** [comment]
Ah yes, thank you for clarifying.

You can put your own icons **on top of** the other labels using the [`blend_order`](https://mapzen.com/documentation/tangram/styles/#blend_order) parameter on your style. For example, a `blend_order: 4` should place your icons above any Mapzen base map labels. Example:

```
styles:
  icons:
    base: points:
    texture: path/to/texture.png
    blend_order: 4 # put icons above other overlays
```

However, I have some unfortunate news to add: you have run up against a limitation we have yet to fix, which is that *collision is not currently applied between features from different data sources*, only between features from the same data source. So your icons will not collide with the base map (though you can still make sure they draw on top, as explained above). See #365 for info too. It's a priority for us to fix this, but it involves a wide refactor, so you'll need to bear with us (likely a few more months).

Let us know how this works for you.

**Comment by jerryhall** [comment]
Thank you for the blend fix. That did it. 
I may be (am likely) mixed up about the collision discussion. Would that collision issue relate to when a geographic area lays on top of my icons the icon would fail? I can definitley live with the icon laying on the boundary lines as I'm not doing a lot in spatial queries yet. But, it sounds like the collision issue will factor in because I am adding another series of layers that include crime. So, if there's a ton of crime in an area where I have a  ton of icons there will be a fail? 

If that's the case I'll could use choropleth maps to illustrate high crime areas on this existing map, and create a separate map with a flipped perspective, the choropleth map of the existing license density with the crime icons on top. 

Thanks for any help understanding this. I'm in so far over my head a few months is like a few days :)

**Comment by meetar** [comment]
Hi @jerryhall, to clarify: to "collide" in this case means that the icons or labels are aware of each other, and if one is already drawn somewhere then another won't try to draw in the same place. But this is only possible for elements from a single datasource. This means that icons or labels from different data sources will just draw over each other and intersect as in your screenshot.

This only relates to points and text, so shouldn't be related to polygons (assuming that's what you mean by "geographic areas") – and if your crime data is in another datasource then there's no way for those elements to interfere with each other anyway. So if I understand your situation correctly, a chloropleth with icons on top should work fine.
