### ISSUE TITLE
Gzipped MVT tiles support

### ISSUE THREAD

**Issue by speller** [tangrams/tangram#520]
I suggest to add support of gzipped MVT tiles produced by tilemaker.

**Comment by bcamper** [comment]
Hi -- gzip decoding is handled by the browser itself -- if you are serving gzipped content, make sure you have the appropriate server-side headers set so the browser knows to decompress the content, e.g. [Content-Encoding: gzip](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Encoding).

Mapzen's tile service does serve gzipped MVT content, try opening the network tab and look at these responses in more detail for an example: https://mapzen.com/products/maps/bubble-wrap/more-labels/#lat=35.6836&lng=139.7593&z=14. You can also try `curl`'ing the URL directly to see the gzipped content.

Hope that helps.

**Comment by speller** [comment]
I'm using a web server where I can't set custom headers (AWS S3).

**Comment by bcamper** [comment]
Do you have an example Tangram YAML or tile URL you can paste? It's
definitely possible to set that up with S3.

**Comment by speller** [comment]
The example file is: https://s3-ap-northeast-1.amazonaws.com/map-test-25/1/6505.pbf

**Comment by speller** [comment]
I just did it by myself, thanks ))

**Comment by bcamper** [comment]
👍
