### ISSUE TITLE
add version in Mapzen documentation

### ISSUE THREAD

**Issue by katossky** [tangrams/tangram#533]
It is quite difficult to identify to which version the documentation on Mapzen's website refers.

https://mapzen.com/documentation/tangram/Javascript-API/

Since most of the users of `tangram.js` are used to Leaflet, maybe a similar pattern should be used:
http://leafletjs.com/reference-1.0.3.html

Also, it is puzzling for an outsider why one should go Mapzen's site for the documentation but be on an independent Github account for the issues ;)

**Comment by meetar** [comment]
Hi @katossky – you're right, we have a little notice on https://mapzen.com/documentation/tangram/Tangram-Overview/ stating that the documentation always refers to the latest version of the library, but [I've added another](https://github.com/tangrams/tangram-docs/commit/4f4b49257c0e7cf525796112685966b2f699296c) to the docs homepage to make it more prominent. In the future we may version our documentation, but so far we simply make a note in the docs when a method or property is deprecated.

And thanks for the feedback on the documentation! We're in the process of reorganizing and redesigning the website, so hopefully this will be more clear in the future.
