### ISSUE TITLE
create style for bunch of the same POI

### ISSUE THREAD

**Issue by bozzwin** [tangrams/tangram#534]
I have created an simple scene file which contains two styles for points. In my db I have icons and backgrounds for them. I have managed to combine them together but 
I would like to have another style in scene file that will be available for multiple, the same POI close to each other. Please take a look on my screenshots.

![image](https://cloud.githubusercontent.com/assets/1229003/24644554/8ffa55c8-1914-11e7-9468-d3e80b3d03dc.png)

and I would like to replace this bunch of icons just like below:

![image](https://cloud.githubusercontent.com/assets/1229003/24644710/48752696-1915-11e7-940e-9a669329eb85.png)

I have attached my scene file.
[scene.yaml.txt](https://github.com/tangrams/tangram/files/892248/scene.yaml.txt)

Is it possible to achieve it?

**Comment by meetar** [comment]
Hi @bozzwin – it sounds like you're describing "clustering", which is possible with Leaflet's "markercluster" plugin: https://github.com/Leaflet/Leaflet.markercluster

So you should be able to make another Leaflet layer on top of the Tangram map and implement custom cluster markers there: https://github.com/Leaflet/Leaflet.markercluster#customising-the-clustered-markers

Tangram doesn't have any native ability to cluster markers at this time.

**Comment by bozzwin** [comment]
Hi 

Thanks for your suggestion.

Mariusz
