### ISSUE TITLE
Question: Camera view to show "horizon"

### ISSUE THREAD

**Issue by Cadrach** [tangrams/tangram#540]
Hi,

First of all, thanks for your library, it looks really cool!

I have been tampering a bit with it, and I love that it is built around Leaflet. However I was wondering if it was possible to have a camera setup to show an "horizon", like the view below:

**EXPECTED RESULT:**
![image](https://cloud.githubusercontent.com/assets/142103/24866975/13c536b0-1e0c-11e7-9d1f-f3c7e91cada9.png)

Is that possible with Tangram? If so, would you be so kind as to direct me to the camera configuration I should use?

Thanks a lot,

**Comment by meetar** [comment]
Hi @Cadrach – [Tangram-ES](github.com/tangrams/tangram-es) has the ability to modify the camera angle via an API, but Tangram-JS (this repo) does not, and there's currently no support for it via the scene file. Thanks for your interest!

**Comment by bcamper** [comment]
To elaborate, one blocker for this in Tangram JS is that Leaflet itself only supports a "top-down" view concept, so we would need to create a separate non-Leaflet interface for using Tangram for those cases (which we plan to do eventually!)

**Comment by Cadrach** [comment]
Ok, this is what I thought, thanks for the quick answers guys!
