### ISSUE TITLE
RTL curved label text flips order of punctuation/spaces

### ISSUE THREAD

**Issue by dmvaldman** [tangrams/tangram#541]
@mushon pointed this out to me on Twitter. I'll work on fixing this ASAP. Believe it's because we split words into 2-letter segments, and if one of the letters is RTL and the other neutral (like spaces, punctuation, etc) then the order between them is indeterminate (it would depend on what the next strongly-directioned character is). He provided the examples below:

Spaces
![space_bad](https://cloud.githubusercontent.com/assets/796394/24867071/13f3ff2c-1dda-11e7-823f-3bc52166a0e4.jpg)

Apostrophes
![apostrophe](https://cloud.githubusercontent.com/assets/796394/24867079/18bd6192-1dda-11e7-8d95-2c45b6171943.png)

Quotes
![quotes](https://cloud.githubusercontent.com/assets/796394/24867083/1cc4a7b4-1dda-11e7-9272-3976b5d0487a.png)

Parenthesis
![paranethesis](https://cloud.githubusercontent.com/assets/796394/24867095/2460fcfc-1dda-11e7-803c-6429879800ed.jpg)

**Comment by dmvaldman** [comment]
Looks like there are 2 (related) problems happening here. One introduced with curved labels, and the other (for multi-line labels) must have been in Tangram for a while.

The problem occurs when a neutral character, like spaces or punctuation, occur at the end of some bit of text. A neutral character's direction is defined by its surrounding characters, so when it occurs at the end (or beginning), the direction is ambiguous and `Canvas` will place it in a LTR way. 

For curved labels we see this when we cut the words into 2-letter pieces and one of the pieces ends in a neutral character. This is what you see in the first two examples above.

For multi-line labels we see this when we break them up on spaces into segments, and one of the segments ends in a neutral character. This is what you see in the last two examples above.

For curved labels there's a simple fix which is to separate text into individual characters (instead of grouped by 2) whenever the last character is neutral. For multiline labels... I'm still thinking about it.

**Comment by dmvaldman** [comment]
Here's a better example of why the multi-line case is going to be tricky...

<img width="244" alt="screen shot 2017-04-10 at 3 36 09 pm" src="https://cloud.githubusercontent.com/assets/796394/24879071/9689504e-1e03-11e7-9926-ae2eb5667826.png">

here we're taking a piece of the text that ends on a neutral character, the '-', notice it appears on the wrong side.

same for the space

when we take the next character, both the space and '-' flip to the correct side

**Comment by bcamper** [comment]
Fixed in #541, pending v0.12.2 release.

**Comment by dmvaldman** [comment]
Some early work for multi-line labels:

![www gifcreator me_83fsna](https://cloud.githubusercontent.com/assets/796394/25022406/afe562a0-2063-11e7-846f-7685be866287.gif)

**Comment by dmvaldman** [comment]
Let's keep this issue open until multi-line is also fixed

**Comment by bcamper** [comment]
Ah good point, thanks. We can ship v0.12.2 with just the curved label fix if we don't get this one done in time (probably early next week).

**Comment by bcamper** [comment]
Curved labels fix released in [v0.12.2](https://github.com/tangrams/tangram/releases/tag/v0.12.2), keeping this issue open for multi-line fix (WIP).

**Comment by bcamper** [comment]
- Multi-line RTL fix in https://github.com/tangrams/tangram/commit/6e6e0456cfc0d103cf76a3794b862119ccc98dc0
- Fix for additional variant of this issue for curved RTL labels in https://github.com/tangrams/tangram/commit/28abe413ad3eedf04db3b4527a34e5537fb7774a

Scheduling both for v0.12.4

**Comment by bcamper** [comment]
Released in https://github.com/tangrams/tangram/releases/tag/v0.12.4
