### ISSUE TITLE
Non-boundary offset should be consistent relative to line direction

### ISSUE THREAD

**Issue by bcamper** [tangrams/tangram#542]
@jschleuss reported this issue, which is a regression from 0.11.x to 0.12.0.

I suspect this may be a casualty of the dual-sided boundary labels (https://github.com/tangrams/tangram/pull/516), where the offset direction sometimes has to flip internally. However, that should only affect labels explicitly marked as left/right.

For "normal" line labels (those *not* explicitly marked as left/right), a positive offset should always push the label down/below relative to the line, and a negative offset should always push it up/on top.

Here are Jon's examples:

0.12.1 - incorrect - mixed offsets above/below:
![la-mapmaker-04-10-2017-11-42-10](https://cloud.githubusercontent.com/assets/16733/24879056/63c4a2da-1dea-11e7-9a43-f87bc9586f75.png)

0.11.x - correct all offsets above:
![old-tangram](https://cloud.githubusercontent.com/assets/16733/24879047/5fa04f56-1dea-11e7-8773-f1e4039fd7ca.png)

Here's a test I created in Play as well to verify:

v0.12.1: https://mapzen.com/tangram/play/?scene=https%3A%2F%2Fmapzen.com%2Fapi%2Fscenes%2F4%2F482%2Fresources%2Fbasic.yaml#16.72917/37.84889/-122.29377

v0.11.x: https://mapzen.com/tangram/play/?lib=https://mapzen.com/tangram/0.11/tangram.min.js&scene=https%3A%2F%2Fmapzen.com%2Fapi%2Fscenes%2F4%2F482%2Fresources%2Fbasic.yaml#16.72917/37.84889/-122.29377

**Comment by dmvaldman** [comment]
Ongoing work here for a fix: https://github.com/tangrams/tangram/tree/label-offset

**Comment by bcamper** [comment]
Fixed in #545, pending release in v0.12.2

**Comment by bcamper** [comment]
Release in [v0.12.2](https://github.com/tangrams/tangram/releases/tag/v0.12.2)
