### ISSUE TITLE
Minor Road labels Question

### ISSUE THREAD

**Issue by fly2279** [tangrams/tangram#546]
Where can I go to get some help with the YAML style? I have a cinnabar YAML that I've modified but I can't seem to get the minor roads to show up with a zoom level less than 14 (i.e. 13, 12). Sorry for making a new issue....I'm new here and not sure where to ask for help. Is there a slack channel or something else for this kind of thing? Below is what I've set for minor road labels but I'm not able to get labels to show at zoom 13.
`labels-minor_road:
                filter: { $zoom: [13,14,15,16,17] }
                draw:
                    text-blend-order:
                        priority: 59
                        visible: global.text_visible_minor_road_e
                        #text_source: name
                        font:
                            fill: global.text_fill_road_e
                            size: 10px
                            stroke: { color: global.text_stroke_road4, width: 2 }
                labels-minor_road-z13:
                    filter: { $zoom: [13] }
                    draw:
                        text-blend-order:
                            font:
                                size: 10px
                                stroke: { color: global.text_stroke_road4, width: 2 }
                labels-minor_road-z14:
                    filter: { $zoom: [14] }
                    draw:
                        text-blend-order:
                            font:
                                size: 12px
                                stroke: { color: global.text_stroke_road4, width: 3 }`

**Comment by pnorman** [comment]
> I can't seem to get the minor roads to show up with a zoom level less than 14 (i.e. 13, 12)

Does the vector source you're using have the roads at those zooms?

**Comment by fly2279** [comment]
Well I guess I'm not sure. I'm using tangram and mapzen's service (just like the cinnabar repo).

**Comment by nvkelso** [comment]
Hi Ken,

While minor road geometries are shown earlier, their names aren’t included
in Mapzen Vector Tiles until zoom 14:

- https://mapzen.com/documentation/vector-tiles/layers/#roads-transportation

This is done to decrease file size and improve performance.

But there is a delicate balance between minor roads in cities which aren’t
significant, and minor roads in rural areas that actually are significant
(and should be labeled). If you have some specific examples you can note,
please file an issue in this repo:

- https://github.com/tilezen/vector-datasource/issues/new

Cheers,

_Nathaniel

**Comment by bcamper** [comment]
I think this question is answered, so closing the issue, feel free to reopen or open a new one with additional question details.
