### ISSUE TITLE
some centroids in untiled geojson are not being in small polygons

### ISSUE THREAD

**Issue by burritojustice** [tangrams/tangram#550]
**TO REPRODUCE THE ISSUE, FOLLOW THESE STEPS:**

https://mapzen.com/tangram/play/?scene=https://mapzen.com/api/scenes/22/500/resources/scene.yaml#16.52087/37.81997/-122.36418

importing https://gist.githubusercontent.com/burritojustice/f38381ce0dba2ce1908a79b67f1acea9/raw/87bb631aaf286dbdf577512f98a23eb5306c5bde/TI_1939_all.geojson

**RESULT:**

some label centroids generated by `generate_label_centroids: true` are far outside their polygons, generally to the east

**EXPECTED RESULT:**

centroids should be in the center

**ENVIRONMENT:**

Chrome 57.0.2987.133, Safari Version 10.1 (12603.1.30.0.34), Tangram Play, Tangram View

**OTHER:**

Any additional notes, comments, tips, tricks, gifs, suggestions, poetry, recipes, jokes

![image](https://cloud.githubusercontent.com/assets/3979711/25204895/8aabfc50-2514-11e7-94f1-920d155ca317.png)

**Comment by bcamper** [comment]
Turns out this was a precision problem: some small polygons were exceeding the floating point precision because of very small intermediate values.

Fixed in 35d4982ca7af89c46cd50cae3492cd5bc13a15f4.

@matteblair should look at this in ES too?

**Comment by bcamper** [comment]
Release in [v0.12.2](https://github.com/tangrams/tangram/releases/tag/v0.12.2)

**Comment by matteblair** [comment]
Actually, I think tangram-es doesn't implement `generate_label_centroids` yet - I'll create an issue if there isn't one already.
