### ISSUE TITLE
Screenshots include incorrect border color on polygon

### ISSUE THREAD

**Issue by stepps00** [tangrams/tangram#551]
**TO REPRODUCE THE ISSUE, FOLLOW THESE STEPS:**

- Create a Tangram scene that imports a GeoJSON file ([my Tangram scene experiencing the error](https://mapzen.com/api/scenes/3950/350/resources/scene.yaml#10.1328/52.3563/-355.0987))
- Give that GeoJSON a border color and polygon color
- Hover to zoom 10, ([link in Tangram Play](https://mapzen.com/tangram/view/?scene=https://mapzen.com/api/scenes/3950/350/resources/scene.yaml#10.1328/52.3563/-355.0987))
- Click the "Toggle Camera Tools" button
- Click the "Take a Screenshot" button

**RESULT:**

Notice that the resulting screenshot has a thick green border around each polygon.

**EXPECTED RESULT:**

The screenshot should show an orange border, as seen in Tangram Play.

**ENVIRONMENT:**

OS: OS X El Capitan
Browser: Firefox, 52.0.1 (64-bit)

**OTHER:**

Screenshot of the file in Tangram Play:
<img width="354" alt="screen shot 2017-04-20 at 12 20 56 pm" src="https://cloud.githubusercontent.com/assets/18567700/25248621/c1b79092-25c3-11e7-844b-44250fcd10b9.png">

Screenshot taken from the "Take a Screenshot" button:
<img width="418" alt="screen shot 2017-04-20 at 12 21 05 pm" src="https://cloud.githubusercontent.com/assets/18567700/25248620/c17d6818-25c3-11e7-9ae1-ecda77a4fb45.png">

Related (?): https://github.com/tangrams/tangram/issues/375#event-1051069301

**Comment by bcamper** [comment]
Fixed in https://github.com/tangrams/tangram/commit/e5814736cabdf0934b930bd7a79f1a1b66a6687d, for v0.12.5 release.

**Comment by bcamper** [comment]
Released in [v0.12.5](https://github.com/tangrams/tangram/releases/tag/v0.12.5)
