### ISSUE TITLE
Visualising non-metric geometries

### ISSUE THREAD

**Issue by lucas1000** [tangrams/tangram#556]
Is there a way to use Tangram to output a map view where the vertices of every graphical object maintain their geo reference but are drawn such that the view doesn't uniformly conform to the metric WGS84 space? In other words a map view in which the size/ shape/ position of graphical objects aren't tied to a base map. An example would be rendering a road at multiple scales in the same map view (i.e. expanding/ squeezing space). Perhaps using the worldPosition() variable as a reference for displacement vectors?

Help very much appreciated.

**Comment by meetar** [comment]
Hi @lucas1000 – if I understand what you're describing, the answer is "maybe but it might not look like what you're expecting." Our vertex shaders allow all kinds of interesting manipulations, and we've experimented with this in the past: http://meetar.github.io/bendy-map/
code: https://github.com/meetar/bendy-map

Lots more here: https://github.com/meetar/projection-tests

More about these here: https://mapzen.com/blog/escape-from-mercator/

But there are some limitations you'll have to consider – for instance, for now we only fetch tiles which would be shown in the standard web mercator projection of the current view. For example:

http://meetar.github.io/albers/#4.54583/46.678/-96.918

The above map is displaying our web mercator vector tiles with an Albers projection, but the projection is distorting the tiles away from the top edge of the screen, leaving a gap in the tiles. At the moment Tangram doesn't have any way to know that it should be loading more tiles – the vertex shader is the only part of the library that knows about the projection. We plan to implement smarter tile fetching for these kinds of situations in the future.

Additionally, these shaders are operating on a global scale, and when you zoom in past about zoom 15 we start to run out of floating point precision and the vertices get wobbly. But if you're comfortable with these limitations for now, you can do a lot with shaders.

**Comment by lucas1000** [comment]
@meetar thanks so much for the info. I had wondered whether it may be possible to just 'hide' the tiles (maybe just set everything white) and draw over the top  using displacement vectors - obviously not a production solution but in terms of a prototype do you think that is theoretically possible?

**Comment by meetar** [comment]
Maybe? but it might not look like what you're expecting. 😀

It depends a lot on specifics. This isn't what the library was designed for, so you're likely to run into unexpected behavior. My only other suggestion is that it would probably be easier to make a new piece of geometry (maybe using geojson.io or something like it) to "mask" out the area you don't want to see using layering, and then draw your displaced vectors on top of that.

**Comment by lucas1000** [comment]
Ok thanks!

**Comment by meetar** [comment]
Good luck!
