### ISSUE TITLE
How about to publish the package to the npm?

### ISSUE THREAD

**Issue by bigslycat** [tangrams/tangram#561]
**OTHER:**

I see it published, but has not been updated for a [long time](https://www.npmjs.com/~mapzen-tangram).

**Comment by bcamper** [comment]
Yes we will be doing this soon! The version published in npm currently was published by mistake long ago.

We have been ironing out some issues with bundling Tangram with browserify and webpack, but should be ready to publish it to npm shortly.

**Comment by bigslycat** [comment]
Need help?
