### ISSUE TITLE
Polygon lines order

### ISSUE THREAD

**Issue by donflopez** [tangrams/tangram#563]
Is there any way to draw polygon lines in the same order than polygons?

I see that I can draw polygon lines as lines and polygons independently, but I have the following result, lines are over or under the polygons, not "with" the polygon.

![screen shot 2017-05-29 at 09 39 32](https://cloud.githubusercontent.com/assets/463462/26540726/035973c8-4453-11e7-8171-c93f154b5d7b.png)

I want the first example result, but I have the second one.

How can I get the second one?

Thank you guys!

**Comment by bcamper** [comment]
Hi @donflopez, each `draw` block can have its own `order` value. This allows you to interleave the drawing operations in many different orders, which is sometimes desirable (for example, grouping the outlines on all roads when zoomed out, but allowing them to reflect the actual interleaving of roads when zoomed in).

So in your example, you want to assign 4 different order values, for example

- Bottom polygon: 0
- Bottom lines: 1
- Top polygon: 2
- Top lines: 3

Usually this is done programmatically based on a feature property, or with filters that select for groups of features (e.g. you shouldn't generally have to do this manually for specific features).
