### ISSUE TITLE
Bridge rendering error in Paris

### ISSUE THREAD

**Issue by Binnette** [tangrams/tangram#567]
**TO REPRODUCE THE ISSUE, FOLLOW THESE STEPS:**
1. Open http://www.openstreetmap.org/#map=17/48.86368/2.30172
2. Open http://tangrams.github.io/tangram/#18.249999999999993/48.863399701115945/2.301154326850306
3. Compare. Tangram do not render properly one of the road of the bridge "Pont de l'Alma".

OpenStreetMap is correct. Tangram is incorrect.

**RESULT:**
Tangram has a bad rendering of the second road of bridge "Pont de l'Alma".
![ko](https://user-images.githubusercontent.com/6597721/27093046-9e7b4fa2-5065-11e7-8406-6678825e0a2c.png)

**EXPECTED RESULT:**
Tangram have to render the road as OpenStreetMap render it.
![ok](https://user-images.githubusercontent.com/6597721/27092612-3bc19de0-5064-11e7-92fc-928244a59327.png)

**ENVIRONMENT:**
Web

**OTHER/BONUS:**
On those screenshots, you can see the same error for the road "Place de l'Alma", north of the bridge.

Thank you for fixing this issue :blush:

**Comment by meetar** [comment]
Hi @Binnette! Thanks for the issue – we're taking a look at this and will get back to you.

**Comment by bcamper** [comment]
Hi @Binnette, the issue is a data error in the Mapzen vector tiles, relating to the OSM update process - the team has identified a fix and it should be complete within the next day or so.

**Comment by Binnette** [comment]
Great. It seems that Mapzen have fixes those bugs :+1: 

![2017-06-14 22_39_54-tangram_ webgl for openstreetmap](https://user-images.githubusercontent.com/6597721/27153609-6dbc0ab2-5152-11e7-8136-27b0f69454f8.png)

Every thing seems nice now ! Thank you for reporting the bugs to Mapzen. And thanks Mapzen !
