### ISSUE TITLE
Memory leak issue with angular4

### ISSUE THREAD

**Issue by michaelhornak** [tangrams/tangram#573]
Hi, we are using Tangram+Leaflet with angular4 framework. Our app has multiple modules, from which one of them has map in it. You can switch between these modules with standard angular routing. When you switch to a module where the map is, in the initialization of the module every time we create a new L.map and new L.tangramLeaflet layer. It seems, that this initialization is creating a memory/GPU leak, which browser isnt cleaning afterwards. You can easily get to 2GB of memory.

I have created a [plunker ](https://plnkr.co/edit/M43k9m?p=preview) example with default angular routing example to which I added leaflet+tangram to "crisis center" tab. Tangram tiles arent loading due some request errors because of plunker enviroment, but the issue is the same. It seems only calling new Tangram.leafletLayer is doing this. When you swich tabs between "crisis center" and other tabs, you can see the issue.

Is there some "destroy" method we could call on tangram when we leaving angular component to clear the memory and all the things tangram created in the first time?

**Comment by bcamper** [comment]
Hi @michaelhornak -- this sounds like the same root issue [here](https://github.com/tangrams/tangram/issues/495#issuecomment-279859477). Indeed, you do need to ensure that resources are cleaned up. This can be done by removing the entire Leaflet map (e.g. `map.remove()`, appropriate if it shouldn't be shown anymore, as there may be other Leaflet resources that need to be released as well), or by removing the Tangram Leaflet layer from the map (`layer.remove()`), if the map will continue to be displayed, but without the Tangram content.

Can you this a try?

**Comment by michaelhornak** [comment]
yep! that was it! thanks very much and sorry for not searching thoroughly.  

By the way, i wanted to ask, if you are planning something like bundle tangram library to smaller modules divided by functionality, if for example we are using tangram in application only for rendering lines and text labels, we dont need the whole webGL 3d functionality with lightning, animation and so on..so in this case we would prefer to use smaller base functions of tangram. Thanks

**Comment by bcamper** [comment]
Thanks - there are several architectural issues that would make breaker out smaller components difficult at the moment (the lines and labels you're using are also WebGL! :) but it's certainly something we would think about for the future.
