### ISSUE TITLE
this.camera.update - Cannot read property 'update' of undefined

### ISSUE THREAD

**Issue by arthur-clifford** [tangrams/tangram#584]
**TO REPRODUCE THE ISSUE, FOLLOW THESE STEPS:**
I'm not sure if it is 100% reproducable, however, in our environment:

After setting the mapzen api key in an earlier script...

This line is in a dojo.js component that worked yesterday and stopped working today:
this.map = new L.Mapzen.map(this.domNode, {maxZoom: 27}).setView([42.35, -71.08], 13);

this.domNode refers to the dojo widget's dom element.

**RESULT:**
 TypeError: Cannot read property 'update' of undefined
    at e.value (tangram.min.js:formatted:29133)
    at e.value (tangram.min.js:formatted:19167)
    at e.value (tangram.min.js:formatted:19138)
    at e.r.222.Object.assign.onAdd.e.hooks.move (tangram.min.js:formatted:17850)
    at e.fireEvent (leaflet.js:6)
    at e._resetView (leaflet.js:6)
    at e.setView (leaflet.js:9)
    at Object.SetupComponent (Map.js:46) ...

Map.js:46 is the this.map =  line above.

the code around the error line e.value (tangram.min.js:formatted:29133): 
 key: "update",
                        value: function() {
                            this.camera.update(),
                            this.pan_snap_timer = (+new Date - this.panning_stop_at) / 1e3,
                            this.user_input_active = +new Date - this.user_input_at < this.user_input_timeout
                        }
**EXPECTED RESULT:**
No error

**ENVIRONMENT:**
Errors on chrome and edge, seems browser independent, and more an error based on assuming something is set.

**OTHER:**

Our guess is that there needs to be an if statement for this.camera.update to verify there is a camera to update; suggesting a timing issue/race-track/or other case where  update is unexpectedly being called before a camera is set. 

I'm wondering if that camera update line was added in the last release because the code worked fine the day/hours before without a problem and we'd been using https://mapzen.com/tangram/tangram.min.js 

Also, we have a multi sandbox dev environment and while one coder discovered the problem today during development she tested against untouched known functional sandboxes that were unchanged, so that rules out changes on our end.

**Comment by arthur-clifford** [comment]
As a follow up, we downloaded the min js, pretty printed it and wrapped the this.camera.update() call in an if statement and that seems to have solved the problem for us.

**Comment by bcamper** [comment]
Thanks for the report. Fixed in 0b2e58ad6be2fd154f582b7d7d10e986a7e57497, will be in forthcoming v0.13.2 release.

**Comment by bcamper** [comment]
Released in [v0.13.2](https://github.com/tangrams/tangram/releases/tag/v0.13.2)
