### ISSUE TITLE
how to match the correct {x} /{y} in yaml file?

### ISSUE THREAD

**Issue by kengqiangxia** [tangrams/tangram#590]
I try to use tangram to load TopoJSON from GeoServer ( EPSG:4326 ). But I get a problem that map is not on the correct latitude and longitude. For example, TopoJSON of Manhattan (about 40,-73) would appear in Europe(about 62,32 ). I think the url from yaml file is wrong, {x} /{y} is wrong. The question is that how to match the correct {x} /{y} in yaml file ?

Or I need to modify leaflet instead of yaml file ?

![image](https://user-images.githubusercontent.com/10960290/30053405-3f835516-925b-11e7-97b9-5111e5cd6242.png)

_The red map is from mapzen ( tile.mapzen.com/mapzen/vector/v1/all/{z}/{x}/{y}.topojson ), the yellow map is from GeoServer. And the yellow map is not on the correct position Europe instead of Manhattan._

**Comment by bcamper** [comment]
Hi @kengqiangxia -- Tangram only displays tiles in "web Mercator" aka EPSG:3857. I am not familiar with GeoServer config, but you can probably get it to output XYZ tiles with web Mercator coordinates. The TopoJSON data itself *should* be in lat/lon, EPSG:4326.
