### ISSUE TITLE
How can I reference the source code ( js in src ) in my project？

### ISSUE THREAD

**Issue by scriptingmax** [tangrams/tangram#594]
I have been using "tangram.debug.js" in my project, but there were some functions I cannot debug. 

  I have tried to reference the moudle.js, but got "Uncaught SyntaxError: Unexpected token import" in my browser. I think it might because the browser cannot recognize ES6 .
![image](https://user-images.githubusercontent.com/31305728/30475455-7ade38de-9a39-11e7-8f21-4e360974b4eb.png)

  So, how can I reference the source code ( js in src ) in my project？

**Comment by bcamper** [comment]
To build and load Tangram locally, please follow the build instructions: https://github.com/tangrams/tangram/blob/master/CONTRIBUTING.md#building

This should allow you to browse or debug all internal Tangram files.

**Comment by scriptingmax** [comment]
Got error when NPM RUN BUILD

> tangram@0.13.2 watch E:\tangram-master
> $(npm bin)/budo src/module.js:dist/tangram.debug.js --port 8000 --cors --live -- -t [ babelify --presets [ es2015 ] ] -t brfs -s Tangram -p [ './build/quine.js' 'tangram.debug.temp.js.map' ] -p [ mapstraction 'dist/tangram.debug.temp.js.map' ]

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tangram@0.13.2 build-bundle: `$(npm bin)/browserify src/module.js -t [ babelify --presets [ es2015 ] ] -t brfs --debug -s Tangram -p browserify-derequire -p [ './build/quine.js' 'tangram.debug.js.map' ] -p [ mapstraction 'dist/tangram.debug.js.map' ] -o dist/tangram.debug.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the tangram@0.13.2 build-bundle script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tangram@0.13.2 build: `npm run build-bundle && npm run build-minify`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the tangram@0.13.2 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by bcamper** [comment]
Hi - are you on Windows? Looks like it may be this error #569? cc @meetar

**Comment by meetar** [comment]
Copying and pasting that command on its own looks successful – it completes for me with no errors. And running the whole command still works for me as referenced in #569.

**Comment by scriptingmax** [comment]
Yep，win10.@bcamper

**Comment by bcamper** [comment]
@scriptingmax could you please try the command directly as @meetar suggests?

**Comment by scriptingmax** [comment]
Sorry I was off my office yesterday. @bcamper 
It doesn't work after I try the "$(npm bin)/...." command, was I misunderstand? @meetar

**Comment by meetar** [comment]
Can you show us the whole command you tried?

I was talking about this one, as mentioned in #569:

```
$(npm bin)/budo src/module.js:dist/tangram.debug.js --port 8000 --cors
--live -- -t [ babelify --presets [ es2015 ] ] -t brfs -s Tangram -p [
'./build/quine.js' 'tangram.debug.temp.js.map' ] -p [ mapstraction
'dist/tangram.debug.temp.js.map' ]
```

**Comment by meetar** [comment]
Can you show us the whole command you tried?

I was talking about this one, as mentioned in #569:

```$(npm bin)/budo src/module.js:dist/tangram.debug.js --port 8000 --cors --live -- -t [ babelify --presets [ es2015 ] ] -t brfs -s Tangram -p [ './build/quine.js' 'tangram.debug.temp.js.map' ] -p [ mapstraction 'dist/tangram.debug.temp.js.map' ]```

**Comment by scriptingmax** [comment]
I did tried the whole command, but it didn't recognize. @meetar 
![image](https://user-images.githubusercontent.com/31305728/30622352-b0f2f164-9de3-11e7-8ff5-14524c00bbca.png)

**Comment by meetar** [comment]
Looks like budo wasn't installed correctly, can you send us the output of the command `npm install budo`?

(Budo should have been included with `npm install` – you already did that, right?)

**Comment by scriptingmax** [comment]
I have install budo and other moudles by cnpm (a complete npm image provide by Alibaba 淘宝), because the connect with npm doesn't goes well in china.
![image](https://user-images.githubusercontent.com/31305728/30674160-c53b74c6-9eaa-11e7-8ff8-03306bdc3f51.png)
![image](https://user-images.githubusercontent.com/31305728/30674323-ee97ac1c-9eab-11e7-99ba-4f4fcd77a1ee.png)
It should be fine with the install.

**Comment by bcamper** [comment]
Does the command 'npm run build' work for you? It doesn't require budo.

**Comment by scriptingmax** [comment]
@bcamper

**Comment by scriptingmax** [comment]
@bcamper 
no....NPM RUN BUILD turns out like this:
-----------------------------------------------------------------------
> tangram@0.13.2 build-bundle E:\tangram-master
> $(npm bin)/browserify src/module.js -t [ babelify --presets [ es2015 ] ] -t brfs --debug -s Tangram -p browserify-derequire -p [ './build/quine.js' 'tangram.debug.js.map' ] -p [ mapstraction 'dist/tangram.debug.js.map' ] -o dist/tangram.debug.js
'$' is not recognized as an internal or external command,
operable program or batch file.
-----------------------------------------------------------
Copying and pasting that command got same error as NPM START

The error seems be unrelated with budo or browserify, it's the windows powershell can't recognize the syntax.

**Comment by meetar** [comment]
Ah! I should have asked what shell you were using. The npm scripts assume that you are using a bash shell.

Windows Powershell has a number of differences which prevent normal unix-type script evaluation. For instance, it uses backslashes in its paths instead of forward slashes.

Also, it doesn't do inline variable expansion except when the expression is enclosed by double quotes, like so: `"$(npm bin)\budo"` – additionally, by default it doesn't load commands from the current location using a relative path, and instead requires that every executable be referenced using an absolute path.

So just this one command in the script file: `$(npm bin)/budo` must be converted to Powershell style to function: `."$(npm bin)\budo"`

For building Tangram (as well as most other packages in npm) on Windows, I recommend using a bash shell like **git bash**, available in [Git for Windows](https://git-for-windows.github.io/). Although it has its own problems when spawning subprocesses (#569) it can at least run the commands when they are pasted directly into the prompt.
