### ISSUE TITLE
Cross-Layer Collisions and Server Side Layer Compositing

### ISSUE THREAD

**Issue by raosaeedali** [tangrams/tangram#595]
Referring to the issue comprehensively mentioned in this link [#365](https://github.com/tangrams/tangram/issues/365), as of now the only solution, as per all the comments I've read so far, is to combine all the sources and make a composite layer URL so that it can be rendered and the problem of conflicting layers can be avoided.
Is there any possible way like [Server Side Compositing](https://blog.mapbox.com/tuning-for-mobile-and-low-bandwidth-environments-cc502e8ea2ca) so that composite layers can be combined on-the-fly with a script as to ensure seamless rendering of all the layers.
Your timely response would be highly appreciated.

**Comment by meetar** [comment]
Hello @raosaeedali – you're talking about conflicting labels, correct? If so we don't currently offer any such service, and though we're interested in providing one it's not currently on our schedule. #365 remains the best place to watch for updates.

**Comment by raosaeedali** [comment]
Hi @meetar thanks for responding. I am following #365 for updates. But, I am asking for any particular way to make a composite of the sources provided in the scene.yaml file at server side (in yaml or JS). In this way, all the sources could be combined as a single source and rendered once, hence the conflicting labels could be avoided for the time being till a comprehensive solution is devised.

**Comment by nvkelso** [comment]
http://tilestache.org may provide such a config...
