### ISSUE TITLE
Texas bays disappear at zoom 9

### ISSUE THREAD

**Issue by jschleuss** [tangrams/tangram#596]
**TO REPRODUCE THE ISSUE, FOLLOW THESE STEPS:**
- In all each Tangram style (and [in our own Map Maker](https://github.com/datadesk/web-map-maker/issues/170)) we're losing [Matagorda Bay](https://www.openstreetmap.org/relation/5150543#map=11/28.5498/-96.2423) just northeast of Corpus Christi, Texas.
- Zooming from level 8 to 9 causes the bay to turn into earth (I can't see a way to fix it in the yaml styles)

**RESULT:**
Bay disappears. 

![bay](https://user-images.githubusercontent.com/695934/30617075-5e6b3220-9d49-11e7-860b-df16a40418f1.gif)

**EXPECTED RESULT:**

The bay should remain (and get probably more detailed as the data switches to OSM).

**ENVIRONMENT:**

Happening in Mac OS Chrome Version 61.0.3163.91 (Official Build) (64-bit)

**Comment by bcamper** [comment]
@nvkelso likely a data issue (though could be a style thing) :)

**Comment by nvkelso** [comment]
Data problem in OSM, overzealous data editor there.

**Comment by jschleuss** [comment]
Bah! Should they be natural=bay or something else?

**Comment by nvkelso** [comment]
Technically the editor is re-tagging to valid tag. It just breaks most maps as it's an annual data update instead of a minutely diff config. Next mapzen build will update, but esp 6-8 weeks.

I'll relate vector tile issue here when I'm back at computer. Should be tracked there instead of here.

**Comment by jschleuss** [comment]
@nvkelso 10-4 that makes sense. thank you!

**Comment by nvkelso** [comment]
It's this https://github.com/tilezen/vector-datasource/issues/1383.
