### ISSUE TITLE
Does Tangram have a way to adapt to transform in TopoJSON?

### ISSUE THREAD

**Issue by scriptingmax** [tangrams/tangram#597]
The TopoJSON map tiles (WebMercator) was provided by the server, and the transform properties in TopoJSON are as follows:
![image](https://user-images.githubusercontent.com/31305728/30623022-d726e472-9de7-11e7-8dc4-6a3e82479d25.png)

In this case, Tangram cannot load the map correctly. I understand that the correct ones should be as follows:
![image](https://user-images.githubusercontent.com/31305728/30623027-d9499b46-9de7-11e7-834d-2280168ae5e1.png)

I would like to ask if there is any way for Tangram to adapt this situation without changing the TopoJSON provided by the server?
Thanks!

**Comment by meetar** [comment]
That's correct, Tangram expects lat/longs. If you know the proper conversion function, you can manipulate the data after it comes from the server with Tangram's transform function: https://mapzen.com/documentation/tangram/sources/#transform

In this case, it looks as though your server has coordinates encoded as UTM, but you'd need to know the  grid zone in order to properly convert those to lat/long. Although it seems you've converted the data in your example, so maybe you already have the proper method.

**Comment by bcamper** [comment]
That said, you'd be best off getting your server to just encode the data in Mercator projection in the first place :)

**Comment by scriptingmax** [comment]
Thanks！ It works after I use the "Mercator to lat/longs" in transform function. 
![image](https://user-images.githubusercontent.com/31305728/30733698-a125236a-9faa-11e7-8158-9d45a8f84683.png)

Seems like the Tangram expects lat/longs and turn the lat/longs into Mercator, but the topojson I used is EPSG:900913(should already be google Mercator). Tangram change it by "lat/longs to Mercator ", and I return it by "Mercator to lat/longs"...

**Comment by meetar** [comment]
I agree it seems unnecessary to convert back to lat-longs when the result will be Mercator meters anyway, however this is a fairly unusual situation, and according to the GeoJSON spec support for alternate projections and coordinate systems is deprecated, and all coordinates should be in lat/longs: https://tools.ietf.org/html/rfc7946#section-4

So there isn't any parameter to skip this process, and we don't anticipate adding one.

**Comment by scriptingmax** [comment]
Copy that, thanks!@meetar 
If I want to skip this “lat/longs to Mercator” process, where should I change in source code?
(I can't modify the server currently, and the "translate and return" will waste time.)

**Comment by bcamper** [comment]
@scriptingmax you should be able to skip Mercator projection by just commenting this line:

https://github.com/tangrams/tangram/blob/master/src/sources/geojson.js#L250

The `TopJSON` source extends the `GeoJSON` one, so that line will affect both. Hope that helps.
