### ISSUE TITLE
can tangram support openlayers?

### ISSUE THREAD

**Issue by dyh333** [tangrams/tangram#600]
can tangram support openlayers as leaflet?
thanks

**Comment by meetar** [comment]
No, Tangram-JS is technically a Leaflet plugin, and draws raster and vector data in a Leaflet layer, while OpenLayers provides both drawing and interaction functions. So I don't know of any way to use Tangram and OpenLayers together.

OpenLayers does support Mapzen's vector tiles – for more information check out our vector tiles product page: https://mapzen.com/projects/vector-tiles/
Here's an example of OpenLayers drawing Mapzen vector data: https://mapzen.github.io/openlayers-mapzen-vector-tile-example/
Example code: https://github.com/mapzen/openlayers-mapzen-vector-tile-example/
