### ISSUE TITLE
Scene background color renders incorrectly

### ISSUE THREAD

**Issue by stevage** [tangrams/tangram#603]
**TANGRAM VERSION:** 0.13.4

**ENVIRONMENT:**

OSX Chrome.

**TO REPRODUCE THE ISSUE, FOLLOW THESE STEPS:**

Render this scene file:

```
scene:
  background: 'hsl(204, 39%, 95%)'
```

**RESULT:**

The result is rendered on the left side of this image.

<img width="225" alt="screenshot 2017-10-05 12 34 52" src="https://user-images.githubusercontent.com/678344/31207391-c1abcdd6-a9c9-11e7-9ece-f80403cfddfe.png">

**EXPECTED RESULT:**

Expected the color on the right hand side (`hsl(204, 39%, 95%)`).

Any idea what's wrong here? That's a very big colour difference. Do I need to change some lighting settings or something? I'm just creating a regular, static 2D map - no 3D required.

**Comment by stevage** [comment]
Sorry, I'm an idiot. The syntax needs to be:

```
scene:
  background: 
    color: 'hsl(204, 39%, 95%)'
```

**Comment by meetar** [comment]
:+1: easiest bug all day :)

I've added an issue to track a related issue, which is that Tangram syntax errors like the one above example fail silently with no feedback in the browser.
