### ISSUE TITLE
Line dashes undocumented

### ISSUE THREAD

**Issue by stevage** [tangrams/tangram#605]
Judging from the code [here](https://github.com/tangrams/tangram/blob/master/src/styles/lines/lines.js) and issues like #355, it seems that line dash patterns are supported, but I can't see anything in the documentation about them?

**Comment by stevage** [comment]
Hmm, here it is: https://mapzen.com/documentation/tangram/styles/#dash

But seemed to be impossible to find by searching, for some reason. It's also confusing to me as a novice user why some of the style properties are under "styles" and most of them under "draw".

**Comment by meetar** [comment]
Hey @stevage, nice catch! You're right, it's a bit confusing – the docs are organized around the syntax hierarchy, and there are a few things which seem _semantically_ as though they ought to be one place which actually live in another… and our search capabilities could definitely be improved, using Google was very simple to set up but has its disadvantages.

In this case we're actually in the process of adjusting the syntax to allow overrides of a couple of these parameters at the `draw` block level, including `dash` (see https://github.com/tangrams/tangram-docs/pull/229/commits/d112e65ac16cf0ea2cdef08e7d44f7dea60c5213 for a preview) so you'll hopefully be able to find these things in a more expected place as soon as the next docs build is released.
