### ISSUE TITLE
Negative `buffer` value shouldn't be allowed

### ISSUE THREAD

**Issue by bcamper** [tangrams/tangram#610]
See #602. 

A negative `buffer` value has unexpected effects on label collision, and the most straightforward thing to do is to just require that `buffer` be greater than or equal to zero.

A negative `buffer` value will be treated as zero.

**Comment by bcamper** [comment]
cc @matteblair for ES related changes (if needed)

**Comment by nvkelso** [comment]
cc @burritojustice as he's used negative buffer as a feature before in some of his maps.

**Comment by bcamper** [comment]
Yeah, @matteblair and I discussed that a bit, but our feeling is that we need to provide a consistent experience, and there are complications with a negative buffer (like if it shrinks the collision box by more than 100% of the label and it inverts, which may explain some of the weird behavior seen), and we do not feel it is worth the complexity for this use case as-is.

**Comment by bcamper** [comment]
See 19b7474f7c3f1780959d78094dc20986b5e2d724

**Comment by bcamper** [comment]
Note, I forgot the first time to apply the same restrictions to `buffer` on `points` (in addition to standalone `text`). Done in https://github.com/tangrams/tangram/commit/9d770b0e4de3cf0ea88099cddd2daf4a76574512.

**Comment by bcamper** [comment]
Released in [v0.14.0](https://github.com/tangrams/tangram/releases/tag/v0.14.0).
