### ISSUE TITLE
WebGL context lost

### ISSUE THREAD

**Issue by dv343** [tangrams/tangram#614]
**TANGRAM VERSION:**

Reproduced with v0.13.5, master branch, the version on tangram-play and with a one month old master commit.

**ENVIRONMENT:**

Ubuntu 16.04, Chrome 62.0.3202.75 and 61.X, Chromium 62 and 61.X

Intel® Core™ i7-7500U CPU, Intel® HD Graphics 620 (Kabylake GT2)  GPU

I couldn't reproduce it with MacOS X with the same Chrome version, nor in Ubuntu 16.10.

**TO REPRODUCE THE ISSUE, FOLLOW THESE STEPS:**

- Run `npm run test-local` or use tangram in an app.

**RESULT:**

When using an app or tangram-play:
- Computer freezes for ~20 seconds.
- WebGL context is lost: `WebGL: CONTEXT_LOST_WEBGL: loseContext: context lost`
-  If you ran Chrome from the terminal, you will see:
```
[12387:12387:1027/112335.969182:ERROR:gles2_cmd_decoder.cc(16248)] Offscreen context lost via ARB/EXT_robustness. Reset status = GL_GUILTY_CONTEXT_RESET_KHR
[12387:12387:1027/112335.969250:ERROR:gles2_cmd_decoder.cc(4394)]   GLES2DecoderImpl: Context reset detected after MakeCurrent.
[12387:12387:1027/112335.969358:ERROR:gpu_channel_manager.cc(197)] Exiting GPU process because some drivers cannot recover from problems.
[12387:12387:1027/112335.969398:ERROR:gpu_channel_manager.cc(197)] Exiting GPU process because some drivers cannot recover from problems.
```
When running the tests with `npm run test-local` similar results, computers freezes for a while then:
```
27 10 2017 11:47:02.481:WARN [Chrome 62.0.3202 (Linux 0.0.0)]: Disconnected (1 times), because no message in 10000 ms.
Chrome 62.0.3202 (Linux 0.0.0) ERROR
  Disconnected, because no message in 10000 ms.

```

WebGL works well with other apps, but this could be a Chromium/Chrome or even a GPU driver bug. However, it would be nice to avoid triggering it.

**Comment by dv343** [comment]
This is probably an unimportant problem since this can be fixed by updating MESA to the latest stable version through this PPA: https://launchpad.net/~paulo-miguel-dias/+archive/ubuntu/pkppa/

**Comment by meetar** [comment]
Hi @dv343 – glad to hear you were able to resolve it, and thanks very much for the detailed writeup, this will help others in your situation :)

**Comment by dv343** [comment]
You're welcome
