### ISSUE TITLE
in demos > main.js: wrong paramters sequence in  map.setView(...)

### ISSUE THREAD

**Issue by wolfgangvonludwigsburg** [tangrams/tangram#624]
**sort of typo in demos > main.js:**

in demos > main.js:
change
`33:    map.setView(map_start_location);`
to
`33:    map.setView( map_start_location.slice(1, 3), map_start_location[0] );`

leaflet expects [lat, lon], zoom,
**not** zoom, lat, lon

WvL

**Comment by meetar** [comment]
Thanks for the catch!
