### ISSUE TITLE
document.currentScript can be null

### ISSUE THREAD

**Issue by marianoguerra** [tangrams/tangram#625]
**TANGRAM VERSION:**

* 0.14.1 (also master)

**ENVIRONMENT:**

*  firefox 59.0a1 (2017-11-29) (64-bit)
* chrome 62.0.3202.94 (Official Build) (64-bit)
* requirejs

**TO REPRODUCE THE ISSUE, FOLLOW THESE STEPS:**

* include latest mapzen from requirejs's require

**RESULT:**

Load fails with error:

    Uncaught TypeError: Cannot read property 'src' of null

**EXPECTED RESULT:**

Library loads

The problem is here: https://github.com/tangrams/tangram/blob/5df4e7edcc7953d4080566b941c148a163360eca/build/quine.js#L13

specifically this condition:

    document.currentScript !== undefined

in my case document.currentScript is null, not undefined.

the fix is simple, just change the condition to:

    !!document.currentScript

this works in my case.

**Comment by bcamper** [comment]
Thanks - would you like to submit a PR for the fix? If not we will get around to it.
