### ISSUE TITLE
modifyScrollWheel prevents other base layers from scroll wheel zooming

### ISSUE THREAD

**Issue by shua123** [tangrams/tangram#637]
**TANGRAM VERSION:**

0.15.1 with Leaflet 1.3.1

_If you're not using the latest version, please try that first before filing an issue!_

- _Latest version:_ https://mapzen.com/tangram/tangram.min.js
- _Notes for latest version:_ https://github.com/tangrams/tangram/releases/latest

**ENVIRONMENT:**

Windows 10 - Chrome

**TO REPRODUCE THE ISSUE, FOLLOW THESE STEPS:**

- Create Tangram layer
- Create another non-Tangram base layer
- Add layer control to map to allow selection between layers.

Minimum reproducible example: https://shua123.github.io/simple-demo/ https://github.com/shua123/simple-demo/blob/master/index.html

**RESULT:**

In default mode (ie, when modifyScrollWheel = true), scroll wheel zoom works fine when Tangram layer is showing. When you select a different layer, scroll wheel zoom does not work. Console error:
`Uncaught TypeError: Cannot read property 'getZoomScale' of null`
![image](https://user-images.githubusercontent.com/1593537/38439090-ff87a9be-39a1-11e8-8401-20a64f683e07.png)

**EXPECTED RESULT:**

Map should be able to zoom with scrollwheel for any layer.

**Comment by bcamper** [comment]
Released in v0.15.2
