### ISSUE TITLE
support size: % and auto when no sprites set

### ISSUE THREAD

**Issue by meetar** [tangrams/tangram#638]
Support percentage and ratio sizes, eg: `size: 50%` and `size: [16px, auto]` when no sprites set, to match ES implementation.
https://github.com/tangrams/tangram-es/blob/43efd63c69d1c018c80ee00bb8eab33f7788168b/core/src/style/pointStyleBuilder.cpp#L350

Sub-issues: #642, #644

Related:
- https://github.com/tangrams/tangram/issues/438
- https://github.com/tangrams/tangram/pull/234

**Comment by tallytalwar** [comment]
Just a clarification here, no sprite but a texture is used in a draw rule.

**Comment by meetar** [comment]
@tallytalwar Double-checking: this is the current ES behavior, correct?

**Comment by tallytalwar** [comment]
Yes, gone through all the issues you have created, the examples you mentioned in those do work in ES. So yes it is the current ES behavior.

Thanks

**Comment by meetar** [comment]
How about #641? Does 'density' still apply to a texture with no sprites?

**Comment by tallytalwar** [comment]
Yup it does.

Refer: https://github.com/tangrams/tangram-es/blob/master/core/src/style/pointStyleBuilder.cpp#L313

The `size` is set using the `density` if it is determined to have a `texture`. And then is updated based on the sprite information (using the same texture `density`) if a `sprite` is mentioned in the draw rules.
