### ISSUE TITLE
Add Tangram.leafletlayer option modifyZoomBehavior to documentation

### ISSUE THREAD

**Issue by shua123** [tangrams/tangram#655]
modifyZoomBehavior true/false is an available option for a Tangram.LeafletLayer similar to modifyScrollWheel. However, modifyZoomBehavior is currently not mentioned in documentation.

**Comment by shua123** [comment]
Hi @meetar. In our testing so far modifyZoomBehavior=false has been the only way to get the map pan/zoom to work correctly consistently. With the tangram zoom mod on, when we jump to a new portion of the map (usually via fitbounds), everything starts drawing in one place, then the tangram layer and a polyline layer jumps to the right some but our marker layers don't so they become out of position with the map.

**Comment by bcamper** [comment]
It's reasonable to add to the public API.

**Comment by meetar** [comment]
Easily done! https://github.com/tangrams/tangram-docs/commit/ad5f40c14ef082bb4672090d1f4893314ea70b20
