### ISSUE TITLE
Issue with rendering building with building parts

### ISSUE THREAD

**Issue by westnordost** [tangrams/tangram#656]
There seems to be an issue with rendering buildings that have building parts, at least the "Stadthaus" in Mainz doesn't render correctly. 
This issue appears in tangram 0.14 and tangram-es 0.8.1. I am not sure if this is perhaps already fixed or a problem with the style, 

because the building looks fine on your demo map:
http://tangrams.github.io/tangram/#18.58383433024089/50.002429190542124/368.260960742287

but on this map (tangram 0.14), it's missing most of it
https://map-data.de/#map=18.07618459065755/50.002007361945026/8.261264716010315&style=streetcomplete-light

**Comment by meetar** [comment]
Hi @westnordost – thanks for the report! I checked your datasource on tangram.city with a basic scene file, and compared it to the same scene file with the nextzen datasource. As far as I can tell, those building parts aren't in your tiles.

Just to be sure, I checked all of our styles with all Tangram versions that support MVT (everything from 0.12 on) and didn't see any trouble. I also checked your datasource against those Tangram versions and it looks like those building parts are just missing.

Maybe there was some kind of glitch when your datasource was created?

**Comment by westnordost** [comment]
This may very well be the case. I am checking now in my app (that uses tangram-es 0.8.1, where the problem was also observed) what it displays for the same building and the same style...

**Comment by westnordost** [comment]
Alright, the building shows using the nextzen tile source, so it is a glitch in the tile server I use
![screenshot_1531342824](https://user-images.githubusercontent.com/4661658/42599047-529dc7ac-855e-11e8-8e50-3d1019d1c93e.png)

Sorry for the noise, and thank you for looking into it! :-)
