### ISSUE TITLE
YAML parsing when function string begins with "|-"

### ISSUE THREAD

**Issue by guyisra** [tangrams/tangram#657]
when having something like
```
        text_source: |-
          function() { return ""+feature["name:latin"]+"
          "+feature["name:nonlatin"]+"" }
```
the text isn't being rendered. But if the text_source is just a string (`'function(){ .. }'`) it is being rendered

similary 
```
 text_source: |
          function() { return ""+feature["name:latin"]+"-\n-"+feature["name:nonlatin"]+"" }
```
is being rendered well as well (notice the `\n`)

the yaml is being generated from the string `function() { return ""+feature["name:latin"]+"-\n-"+feature["name:nonlatin"]+"" }` via the https://github.com/nodeca/js-yaml module which seems to be the most popular and maintained yaml parser module.

Using tangram 0.15.1 (and tested on tangram play latest version)

**Comment by bcamper** [comment]
I'm not really familiar with YAML `|-` syntax, but putting a line-break within a double-quoted string wouldn't be valid JS anyway, so I'm reluctant to encourage this (even if it should be supported by the YAML parser, if I understand the issue?). 

```
        text_source: |-
          function() { return ""+feature["name:latin"]+"
          "+feature["name:nonlatin"]+"" }
```

I haven't looked for any evidence, but the parsing issue could be us using an older version of js-yaml -- you said you used js-yaml to actually *generate* that string?

**Comment by guyisra** [comment]
I ended up escaping the problematic chars that cause the yaml parser to use the |- (which I think was added in the 1.2 spec), so all works now :D

per your question - yes, I am generating the yaml via code, so features can be added/remove on the fly
