### ISSUE TITLE
Link to choropleth examples broken

### ISSUE THREAD

**Issue by michaelhester** [tangrams/tangram#659]
**TANGRAM VERSION:**

N/A - related to documentation/examples

**ENVIRONMENT:**

N/A - related to documentation/examples

**TO REPRODUCE THE ISSUE, FOLLOW THESE STEPS:**

1. Go to Tangram choropleth examples: https://github.com/tangrams/choropleth-demos
2. Click on link to 3-D choropleth example: tangrams.github.io/?url=poverty 

**RESULT:**

The link seems to be broken. Was wondering if these examples are still maintained - super interested in trying out the 3-D choropleth and would love to see an example live. 

Thanks!!

**Comment by meetar** [comment]
Hi @michaelhester – yep, looks like they need updating, I'll update this thread when they're fixed. Thanks for the catch!

**Comment by michaelhester** [comment]
Thank you!!! Appreciate you responding so quickly. Excited to play around with Tangram.
