### ISSUE TITLE
Road shield funk, missing artwork

### ISSUE THREAD

**Issue by nvkelso** [tangrams/tangram#662]
**TANGRAM VERSION:**

v0.15.2 and 0.14.x

**ENVIRONMENT:**

Mac Chrome Version 68.0.3440.106 (Official Build) (64-bit)

**TO REPRODUCE THE ISSUE, FOLLOW THESE STEPS:**

- Viewing Bubble Wrap in in Canada at 11/49.8643/-97.1439
- This branch: https://github.com/tangrams/bubble-wrap/tree/sensescape/shields-polish
- Checkout the branch locally and preview.

**RESULT:**

Some shield artwork fails to draw (but the text draws fine)

**EXPECTED RESULT:**

The shield artwork and the text should both draw in v0.15.x. It does in Tangram 0.14.x!

v0.15.x

<img width="1149" alt="screen shot 2018-08-18 at 22 59 44" src="https://user-images.githubusercontent.com/853051/44306033-36a54980-a33b-11e8-9c7d-0b2c9629cd5b.png">

v0.14.x
<img width="1225" alt="screen shot 2018-08-18 at 23 06 14" src="https://user-images.githubusercontent.com/853051/44306039-550b4500-a33b-11e8-8df3-c387105fd297.png">

For comparision:

- master Bubble Wrap at same location: http://tangrams.github.io/bubble-wrap/#12/49.9062/-97.1199

<img width="1198" alt="screen shot 2018-08-18 at 23 04 47" src="https://user-images.githubusercontent.com/853051/44306031-3016d200-a33b-11e8-9e63-2e835226758a.png">
<img width="1174" alt="screen shot 2018-08-18 at 23 04 41" src="https://user-images.githubusercontent.com/853051/44306032-3016d200-a33b-11e8-980e-012db1b1fa0d.png">

**Comment by nvkelso** [comment]
Seems to affect both legit shields (like `CA:transcanada`) and "generic" fallback shields.

**Comment by bcamper** [comment]
Should be fixed by 417e4b9cdcfa26b2d5b4a87da1866136d8233c92
Problem was caused by more than one `texture` being used for rendering by the same `style` (multiple sprite sheets for shields in this case).

**Comment by nvkelso** [comment]
This is fix is live in 0.15.3 and I've confirmed it's working for me. Thank you!
