### ISSUE TITLE
Deformed and irregular dots on vector line.

### ISSUE THREAD

**Issue by sk1me** [tangrams/tangram#664]
**TANGRAM VERSION:**

15.2

**ENVIRONMENT:**

Windows 10, Chrome

**TO REPRODUCE THE ISSUE, FOLLOW THESE STEPS:**

Use shader for tangram: http://tangrams.github.io/blocks/#lines-dots

**RESULT:**

Dots on vector line are irregular, deformed and sharp. 
![image](https://user-images.githubusercontent.com/35774692/44521877-f9431200-a6d4-11e8-945f-6f174a32945d.png)
![image](https://user-images.githubusercontent.com/35774692/44521911-14158680-a6d5-11e8-81e4-297e77c4dcff.png)

There is also problem with using dashed lines - irregular chunks of lines.

**EXPECTED RESULT:**

Beautiful, smooth and placed within regular space dots.

**Comment by nvkelso** [comment]
@sk1me That's an old example with raw shader code.

Try the newer implementation as documented here:

- https://tangrams.readthedocs.io/en/latest/Syntax-Reference/draw/#dash

**Comment by meetar** [comment]
Note that the `dash` parameter is for dashes only – there's no equivalent "dots" line style. For dots you'll still need a custom shader. For smooth dots you'll need a shader with antialiasing built in, but spacing will still be an issue, as UV coordinates are not consistent between features or across tiles.

**Comment by meetar** [comment]
@sk1me Just saw your reaction emoji 😅 If you let me know which parts of this are confusing I can try to shed some more light on the issue for you… Regardless, as this seems to be an issue with this particular shader and not the library, I'll close it.

If you have any more implementation questions feel free to throw a message into the gitter channel: https://gitter.im/tangrams/tangram-chat
