### ISSUE TITLE
Library on CDNJS

### ISSUE THREAD

**Issue by leopoiroux** [tangrams/tangram#666]
Hello, can you reference your very good library on cdnjs (https://cdnjs.com/libraries) ? 
Thank you very much

**Comment by bcamper** [comment]
The currently supported CDN is unpkg.com - what do you think are compelling reasons to support others?

**Comment by leopoiroux** [comment]
A good practice is to use the same CDN for all these JS files in order to reduce the number of DNS resolutions. While waiting for your answer, I modified all my JS so that they are now on https://www.jsdelivr.com (Tangram is there).

I didn't realize you were on unpkg.com.

Thanks
