### ISSUE TITLE
Allow Bearer authentication 

### ISSUE THREAD

**Issue by pakore** [tangrams/tangram#668]
Allow OAuth2 Bearer authentication ( http://self-issued.info/docs/draft-ietf-oauth-v2-bearer.html ) for the backend.

Or at least, allow sending custom headers to the backend.

Use Case:
I am a customer and I have a backend that provides tiles but it needs an OAuth2 token in the header ( "Authorization: Bearer <token>" header). I would like to use tangram to render the tiles, so I need a way to give tangram my Oauth2 credentials or at least be able to tell tangram to pass this custom header with a provided token.

**Comment by bcamper** [comment]
Yep, I remember I looked at this a couple times. If I recall, one issue is that for CORS requests, custom headers need to be whitelisted by the server with [`Access-Control-Allow-Headers`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Headers). And some more info/example [here](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#Preflighted_requests).

The Netzen tiles do not directly support this concept (though I suppose they could, and could mimic back the list of headers requested by the client, for example). But if the client is serving their own tiles (or maybe proxying another source), I believe it would work if configured properly. Worth trying a prototype.

**Comment by pakore** [comment]
Allowing sending custom headers as @matteblair  proposes would be the more generic solution, that will solve Auth problems, CORS problems, etc...

For the usecase: the user could manage getting a proper token and refresh it in custom code meanwhile.

**Comment by bcamper** [comment]
@pakore re: my comments about `Access-Control-Allow-Headers`, that makes sense and fits into your workflow?

**Comment by pakore** [comment]
I currently don't have any problems with CORS because my server accepts all, but I think definitely is a use case that needs to be solved for other users also and allowing custom headers could be a solution.

**Comment by bcamper** [comment]
See #670 for an implementation of this.

**Comment by bcamper** [comment]
Released in v0.16.0
