### ISSUE TITLE
selectionEvent works fine only for first click

### ISSUE THREAD

**Issue by martinko94** [tangrams/tangram#700]
**TANGRAM VERSION:**

Any version after 0.15.5 to latest included. Tried every newer release.

**ENVIRONMENT:**

macOS Mojave / Chrome 72.0.3626.96

**TO REPRODUCE THE ISSUE, FOLLOW THESE STEPS:**

In our project we have a map with vector layers (Tangram.leafletLayer) which are interactive (clicking on a feature highlights it and shows some data). For registering the click listener I use `vectorLayer.setSelectionEvents()`. In the first click, everything is ok, event listener is notified with all data. But the event in the second (or any next) click does not contain the `feature` property (TangramFeature) of `selectionEvent`. Everything worked fine with tangram version 0.15.4 and below. Fun fact - when you change the zoom of map, first click works fine again.

**RESULT:**

The feature is not present in the selectionEvent object.

**EXPECTED RESULT:**

Feature should be present in the event object.

**Comment by bcamper** [comment]
Hi - thanks for your report. I haven't been able to reproduce this yet - would you be able to provide a streamlined demo? I've tried setting a click listener with `setSelectionEvents()`, and I still get a `feature` object on multiple clicks; I also tried making changes to the scene with `updateConfig()`, and loading a new scene with `load()`, and still getting callbacks. So there must be something more specific about your case that is interfering, and any further help diagnosing is appreciated.

**Comment by bcamper** [comment]
@martinko94 are you able to provide an update here to assist with debugging?

**Comment by martinko94** [comment]
Hi @bcamper, thank you for the answer. I will try to make a demo as soon as possible, sorry for the inactivity.

**Comment by martinko94** [comment]
Hello @bcamper, after longer time we finally got to fix the problem. In our codebase we were using the updateConfig() method this way `this.vectorLayer.scene.updateConfig().then(() => this.vectorLayer.scene.rebuild());` due to some ancient bug. But in the new tangram version this particular code caused the weird behavior, as everything works just fine with using just the `this.vectorLayer.scene.updateConfig()` without then hook. Thank you for your time, and hopefully this helps someone who has similar problem :)
