### ISSUE TITLE
Add support for underline text style

### ISSUE THREAD

**Issue by nvkelso** [tangrams/tangram#723]
I'd like to add underline text treatment to callout country and regional capitals in map styles. We adding better support for both in the new v1.8 Tilezen schema, but right now the only way to call them out visually is to change the color. One common technique in cartography is to underline capital text.

There are two options for the underline – if there is letter spacing (or spaces) the underline should optionally continue as one "line"... but the default is usually to only do it under word blocks. The weight of the line (thickness or stroke) should match the weight of the text.

**Comment by nvkelso** [comment]
Similar text highlight boxes: https://github.com/tangrams/tangram/issues/724

**Comment by bcamper** [comment]
released in v0.21.0
