### ISSUE TITLE
Zoom and tilt

### ISSUE THREAD

**Issue by skerit** [tangrams/tangram#725]
I'm trying to implement a zoom-and-tilt feature, much like how you can navigate around the map in Pokemon Go or Ingress, but I can't seem to find a way to manipulate the tilt as I'm zooming in or out.

Is it possible to do so in tangram?

**Comment by bcamper** [comment]
Unfortunately there is no native tilt capability in Tangram JS (there is in the native [Tangram ES](http://github.com/tangrams/tangram-es)). There are some [WIP branches](https://github.com/tangrams/tangram/tree/camera-rotation) for JS along these lines, but definitely not ready for primetime.
