### ISSUE TITLE
HTTP response code 204 emits warnings

### ISSUE THREAD

**Issue by Zaitsev** [tangrams/tangram#729]
**TANGRAM VERSION:**

all affected

**ENVIRONMENT:**

**TO REPRODUCE THE ISSUE, FOLLOW THESE STEPS:**
load tile resource with response [HTTP code 204](https://httpstatuses.com/204) (Empty content)

**RESULT:**
Warning in console: 
backend.js:6 Tangram v0.19.0 [warn]: Texture 'https://b.tiles.utility.opt-net.eu/tiles/11/1212/684@2x?url=https://cf2.cloudferro.com:8080/swift/v1/AUTH_1b559b704bc9420394103adcfde3e258/optoss-pipeline/DBF2_34F6_IW1_cropclass-z10d-complex-4315154040-pol-16c.tiff&rgb=1,2,3&': failed to load url: 'https://b.tiles.utility.opt-net.eu/tiles/11/1212/684@2x?url=https://cf2.cloudferro.com:8080/swift/v1/AUTH_1b559b704bc9420394103adcfde3e258/optoss-pipeline/DBF2_34F6_IW1_cropclass-z10d-complex-4315154040-pol-16c.tiff&rgb=1,2,3&' Event {isTrusted: true, type: "error", target: img, currentTarget: img, eventPhase: 2, …} {filtering: undefined, sprites: undefined, url: "https://b.tiles.utility.opt-net.eu/tiles/11/1212/6…s-z10d-complex-4315154040-pol-16c.tiff&rgb=1,2,3&", element: undefined, data: undefined, …}
Describe the result here.

**EXPECTED RESULT:**

No warnings

Some tile services could return response code 204 if there are no Data in the requested tile.
On such case this is valid not-error code so tangram could silently discard such tiles without any warnings

**Comment by bcamper** [comment]
Thanks, this is a reasonable addition, we can look at it for the next minor release.

**Comment by bcamper** [comment]
Fixed in https://github.com/tangrams/tangram/releases/tag/v0.19.1
