### ISSUE TITLE
Export map as svg?

### ISSUE THREAD

**Issue by stefaneidelloth** [tangrams/tangram#735]
Is it possible to export maps/layers as svg file?

**Comment by meetar** [comment]
Yes, but not using built-in functionality. There have been a few examples of this using other libraries, including the https://github.com/hanbyul-here/svg-exporter repo, but I'm not sure if any of them are still working. :/

But that's where I'd start – good luck!

(For other questions feel free to drop by our gitter channel: https://gitter.im/tangrams/tangram-chat)

**Comment by bcamper** [comment]
Note that the SVG example linked is geared towards the underlying Tilezen vector tiles, but not Tangram specifically, so wouldn't include any Tangram styling, etc. Tangram renders with WebGL, which has a very different method of expressing geometry and styling compared to SVG, and unfortunately the two aren't easily compatible.
