### ISSUE TITLE
https://tangrams.github.io/heightmapper/#6/68.034/-152.849

### ISSUE THREAD

**Issue by MartialArts** [tangrams/tangram#743]
For some reason, the picture https://pastenow.ru/7R9LG does not load, it worked fine yesterday, it downloads only parts today, I try to copy the entire earth elevation map to draw up a detailed landscape. Page refresh does not fix the problem. https://pastenow.ru/7R9OL

**Comment by MartialArts** [comment]
> Thanks for the report – it appears that the nextzen tile service is occasionally throwing an error:
> 
> > 503 Service Temporarily Unavailable
> 
> We'll look into it and I'll let you know what we find.

Thanks. It seems you have fixed the service.

**Comment by meetar** [comment]
👍 Thank you @iandees!
