### ISSUE TITLE
Transition from one data source to another

### ISSUE THREAD

**Issue by Shanki1** [tangrams/tangram#752]
Hi 
I have two data sources.
first i load png source till certain zoom level and after that the vector data source 
the issue is the png is still on the page while the vector is loading 
so is there a way to refresh or erase the png's on the map after certain zoom level and get a specific data source 

thank you

**Comment by bcamper** [comment]
Try using the `max_display_zoom` parameter on your raster data source: https://tangrams.readthedocs.io/en/master/Syntax-Reference/sources/#max_display_zoom-min_display_zoom

**Comment by Shanki1** [comment]
Hi 

Thank you so much 
it worked !!!!
