### ISSUE TITLE
Outdated "An open-source project sponsored by Mapzen." at https://github.com/tangrams

### ISSUE THREAD

**Issue by matkoniecz** [tangrams/tangram#756]
Not sure where I should report this but https://github.com/tangrams has outdated description

> An open-source project sponsored by Mapzen.

If it is intention to refer to past history and honor Mapzen? maybe "An open-source project started by Mapzen." would be better?

Because it is certainly not referring to Mapzen as community ( https://www.mapzen.com/blog/mapzen-is-now-a-linux-foundation-project/ ) - sponsored is a poor word here.

**Comment by meetar** [comment]
Thanks @matkoniecz! I've updated the description.
