### ISSUE TITLE
Why do you prune iles?

### ISSUE THREAD

**Issue by sheikh-iffi** [tangrams/tangram#760]
**TANGRAM VERSION: 20.1**

I have a question. Why do you guys discard tiles which are far from current zoom or out of view port. [pruneTilesForView](https://github.com/tangrams/tangram/blob/111be09dee0088f39d09ffce15ca94c68856a4f3/src/scene/view.js#L270-L304)
Isn't it better to retain those tiles since one may want to go back to his previous selected location. In current scenario, tangram would download those tiles again. 
Or it has to do something with the performance?

**Comment by bcamper** [comment]
Tile retain a significant amount of memory. If you were to let them grow unbounded, eventually your browser tab will crash (or at the least you are not being responsible as an app); mobile device browsers are particularly strict about this. As you can see from the linked code, there is logic to retain tiles based on factors including how far away they are in zoom or pan from current location. There's always room to tweak that behavior, but Tangram is an inherently high-memory-use application.

Re: "download those tiles again", in some cases the underlying data for the tile is cached and preprocessed but the styling info may not be, and in others, while it is technically a network request, the response should be cached and essentially a no op.
