### ISSUE TITLE
Geo.metersPerPixel is valid only on latitude 0°

### ISSUE THREAD

**Issue by EugeneKarpenko** [tangrams/tangram#780]
In Mercator projection Geo.metersPerPixel should be latitude dependent. Currently scene.view.size.meters shows invalid values.

**Comment by EugeneKarpenko** [comment]
I'm using leaflet's distance function instead.

**Comment by bcamper** [comment]
That's an internal function in Web Mercator meters, which corresponds to the projection of the vector tiles. It's exposed to users in some specific cases like styling functions, but as a means to style tiles in the local space they're stored in -- not intended as a means of geographically accurate measurement. So using a utility like Leaflet's for true distance is more appropriate.
