### ISSUE TITLE
Introduce u_map_zoom

### ISSUE THREAD

**Issue by predragdukanac** [tangrams/tangram#795]
Hi, development team! Maybe you would consider introducing another program uniform that would expose current map zoom level. It would take one additional line in view.js (line 340: program.uniform('1f', 'u_map_zoom', this.zoom);)

This comes handy when we want to apply slightly different shading for various zoom levels. At the moment, there is no handy way to acquire zoom level in shader block function.

**Comment by matteblair** [comment]
I believe `u_map_position.z` represents the current zoom value (https://tangrams.readthedocs.io/en/main/Syntax-Reference/shaders/#built-in-uniforms). Have you tried using that?
