### ISSUE TITLE
Question - any possible way to use with maplibre-gl?

### ISSUE THREAD

**Issue by openSourcerer9000** [tangrams/tangram#807]
These examples look wild, I would love to be able to use these as basemaps and learn this GL/JS yaml syntax. However, I've abandoned leaflet from my webmapping stack and have settled on maplibre-gl with react. Could this somehow be used without leaflet? Thanks

**Comment by bcamper** [comment]
Hi @openSourcerer9000, apologies for the delay. As you may have noticed from the activity here, this project is essentially in maintenance mode. It's quite stable and has been used for high-volume apps, but it is not in active development, and there is currently no easy way to overlay it on top of Maplibre. Good luck!
